src/externalsystems/Clearinghouse.Library/BusinessLogic/ClearinghouseBusinessLogic.cs
tests/externalsystems/Clearinghouse.Library.Tests/ClearinghouseBusinessLogicTests.cs

override clearinghouse will trigger a restart clearinghouse process
Reviewed-By: Evelyn Gurschler <evelyn.gurschler@bmw.de>

bugfix: override clearinghouse process fixed

---

CHANGELOG.md
src/Directory.Build.props
src/provisioning/Provisioning.Library/Service/ServiceAccountCreation.cs
tests/provisioning/Provisioning.Library.Tests/ServiceAccountCreationTests.cs

- fix(serviceAccount): fix naming of service account
- update changelog (known knowns) and version

release: finalize v1.3.0

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Add pull request template.
n/a
To improve the quality of pull requests.

chore: add pull request template

---

src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppChangeBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppChangeController.cs
src/marketplace/Apps.Service/Controllers/AppsController.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppChangeControllerTest.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs

moved deactivate endpoint to appChange controller.
implements https://jira.catena-x.net/browse/CPLP-2644
Ref: CPLP-2644

feat(appService): moved deactivate endpoint to appChange controller

---

src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Apps.Service/ViewModels/AppDetailResponse.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferDetailsData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs

added technicaluser detail in response body of endpoint
for the app marketplace need to get enhanced to support the technical user details.
https://jira.catena-x.net/browse/CPLP-2651 

feat(apps):- get apps appid

---

src/marketplace/Offers.Library/Models/OfferServiceAutoSetupData.cs
src/marketplace/Offers.Library/Service/OfferSetupService.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs

Added technicalUserPermissions and clienturl in response body
to support the FE/user with additional information
https://jira.catena-x.net/browse/CPLP-2665

feat(apps & services):- Post autosetup

---

src/registration/Registration.Service/Controllers/RegistrationController.cs

swagger documentation description updated for forbidden exception
Currently swagger documentation was showing the message only for one scenario and was missing for other two scenario .It was not clear that this message is for which forbidden exception 
https://jira.catena-x.net/browse/CPLP-2721

fix(registration):- Post submitregistration

---

src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppsController.cs

Mark method as obsolete.
This method no longer in use
https://jira.catena-x.net/browse/CPLP-2787

feat(apps):-PUT {appId}/subscription/company/{companyId}/activate

---

src/marketplace/Offers.Library/Service/OfferService.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferReleaseData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/PortalBackend.DBAccess.Tests.csproj
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offer_assigned_privacy_policies.test.json
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offers.test.json
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/technical_user_profile_assigned_user_roles.test.json
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/technical_user_profiles.test.json
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/user_roles.test.json

Ref: CPLP-2732
added validation for submit endpoint
to validate the privacy policy and  Technical user profile for the app user , before performing submit endpoint
[Link to Github issue.](https://jira.catena-x.net/browse/CPLP-2732)

feat(app) : adding validation for submit endpoint

---

src/marketplace/Offers.Library/Service/IOfferService.cs
src/marketplace/Offers.Library/Service/OfferService.cs
src/marketplace/Services.Service/BusinessLogic/IServiceChangeBusinessLogic.cs
src/marketplace/Services.Service/BusinessLogic/ServiceChangeBusinessLogic.cs
src/marketplace/Services.Service/Controllers/ServiceChangeController.cs
src/marketplace/Services.Service/Program.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceChangeBusinessLogicTests.cs
tests/marketplace/Services.Service.Tests/Controllers/ServiceChangeControllerTest.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs

Ref: CPLP-2790
an endpoint to deactivate service
new endpoint is created to deactivate the service by serviceId
[CPLP-2790](https://jira.catena-x.net/browse/CPLP-2790)

feat(service): an endpoint to deactivate service

---

src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs

remove DocumentTypeIds which are not used anymore
Resolving the currently occuring error on the dev environment
N/A: - Jira Ticket: CPLP-2344

chore: fix app settings

---

src/administration/Administration.Service/BusinessLogic/IServiceAccountBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
src/administration/Administration.Service/Controllers/ServiceAccountController.cs
src/administration/Administration.Service/Models/ServiceAccountConnectorOfferData.cs
src/administration/Administration.Service/Models/ServiceAccountDetails.cs
src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountData.cs
src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountDetailedData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs

Add offer and connector data in response body of  technicaluser endpoint
Enahnce the existing endpoint to know whether service account has offer and connector data or not
https://jira.catena-x.net/browse/CPLP-2785

Feat(serviceaccount):- get owncompany service accounts

---

src/framework/Framework.Linq/GenericSelectExtension.cs
src/framework/Framework.Linq/IfAnyExtension.cs
src/framework/Framework.Models/Configuration/UserRoleConfig.cs
src/framework/Framework.Models/Validation/DistinctValuesValidation.cs
src/framework/Framework.Models/Validation/EnumEnumerableValidation.cs
src/mailing/Mailing.Template/TemplateSettings.cs
src/marketplace/Apps.Service/appsettings.json
src/marketplace/Offers.Library/Models/UploadDocumentConfig.cs
tests/framework/Framework.Linq.Tests/IfAnyTests.cs
tests/framework/Framework.Models.Tests/ValidationTests.cs

changed the records to class for settings
add reference of specific type to genericSelectExtension
Binding of the configuration wasn't working correctly
N/A - Jira Issues: CPLP-2891

fix(config): fixed config binding

---

.github/workflows/release.yml
.github/workflows/release_candidate.yml
CHANGELOG.md
src/Directory.Build.props
src/marketplace/Apps.Service/appsettings.json
src/marketplace/Services.Service/appsettings.json

merge release branch in main for 1.5.1 version.
to wrap up release process for 1.5.1 version.
n/a

hotfix(1.5.1): merge release in main

---

.dockerignore
docker/Dockerfile-administration-service
docker/Dockerfile-maintenance-service
docker/Dockerfile-marketplace-app-service
docker/Dockerfile-notification-service
docker/Dockerfile-portal-migrations
docker/Dockerfile-processes-worker
docker/Dockerfile-provisioning-migrations
docker/Dockerfile-registration-service
docker/Dockerfile-services-service
src/administration/Administration.Service/Administration.Service.csproj
src/maintenance/Maintenance.App/Maintenance.App.csproj
src/marketplace/Apps.Service/Apps.Service.csproj
src/marketplace/Services.Service/Services.Service.csproj
src/notifications/Notifications.Service/Notifications.Service.csproj
src/portalbackend/PortalBackend.Migrations/PortalBackend.Migrations.csproj
src/processes/Processes.Worker/Processes.Worker.csproj
src/provisioning/Provisioning.Migrations/Provisioning.Migrations.csproj
src/registration/Registration.Service/Registration.Service.csproj

add legal information to distribution / include NOTICE.md, LICENSE and DEPENDENCIES file in output
[TRG 7.05 - Legal information for distributions](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05)
n/a

chore(trg): add legal information to distribution

---

src/portalbackend/PortalBackend.Migrations/PortalBackend.Migrations.csproj
src/portalbackend/PortalBackend.Migrations/Seeder/BatchUpdateSeeder.cs
src/portalbackend/PortalBackend.Migrations/Seeder/Data/verified_credential_external_type_use_case_detail_versions.consortia.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/verified_credential_external_type_use_case_detail_versions.json
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanySsiDetailsRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/verified_credential_external_type_use_case_detail_versions.test.json

Adding seeding data for the ssi versions and changing some existing values
Adding the ssi version to the batch update seeder
Some of the already existing values did change, some new ones were added
N/A - Jira Issue: CPLP-2937

chore(ssi): add SSI Versions to seeding

---

.github/workflows/dependencies.yaml
NOTICE.md
scripts/check-dependencies.md

update notice file for portal-shared-components
update dash-tool
new repository added
more recent dash tool version available
n/a

chore: update notice file and dash-tool

---

.github/workflows/test-automation.yml

@evegufy please take a look. I created a draft PR in order to test workflow.
Add test automation workflow.
To start e2e tests manually in GitHubActions.

test(e2e): add test-automation workflow

---

src/administration/Administration.Service/Controllers/ConnectorsController.cs

updated swagger summary and description.
Description and summary was not providing clear picture of usage.
CPLP-2931

fix(connector): get discovery

---

src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
src/administration/Administration.Service/Controllers/ConnectorsController.cs
src/administration/Administration.Service/appsettings.json
src/externalsystems/Daps.Library/DapsService.cs
src/externalsystems/Daps.Library/DapsSettings.cs
src/framework/Framework.Logging/LoggingExtensions.cs
src/portalbackend/PortalBackend.DBAccess/Models/ConnectorData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IConnectorsRepository.cs
src/portalbackend/PortalBackend.Migrations/appsettings.json
tests/externalsystems/Daps.Library.Tests/DapsServiceTests.cs
tests/registration/ApplicationActivation.Library.Tests/ApplicationActivation.Library.Tests.csproj

Disabled daps calls
Daps should get removed in the long run, this PR is the first iteration.
N/A - Jira Issue: CPLP-2702
[#43](https://github.com/eclipse-tractusx/portal-cd/pull/43)

feat(daps): add config to disable daps calls

---

src/administration/Administration.Service/Controllers/ConnectorsController.cs

Remove obsolete connector endpoints.
Change routing of the existing connector creation endpoints
The daps service will be removed in the nearest future, therefore the endpoints got aligned.
N/A - Jira Issue: CPLP-2961

chore(connectors): remove obsolete endpoints

---

src/administration/Administration.Service/BusinessLogic/IStaticDataBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/StaticDataBusinessLogic.cs
src/administration/Administration.Service/Controllers/StaticDataController.cs
src/portalbackend/PortalBackend.DBAccess/Models/OperatorBpnData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/StaticDataBusinessLogicTest.cs
tests/administration/Administration.Service.Tests/Controllers/StaticDataControllerTest.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs

add /api/administration/staticdata/operator-bpn endpoint to receive the operator bpn
To provide the operator bpns to the frontend
N/A - Jira Ticket: CPLP-2956

feat(bpn): add endpoint to get operator bpns

---

src/framework/Framework.HttpClient/HttpAsyncResponseMessageExtension.cs
tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
tests/framework/Framework.Token.Tests/TokenServiceTests.cs
tests/shared/Tests.Shared/HttpMessageHandlerMock.cs

Enhanced the error response message for application Checklist 
Added URI details for Error Response Message for Application Checklist
[CPLP-2822](https://jira.catena-x.net/browse/CPLP-2822)

feat(applicationChecklist) : application checklist comment enhancement

---

src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
src/administration/Administration.Service/Controllers/CompanyDataController.cs
src/portalbackend/PortalBackend.DBAccess/Models/CredentialDetailData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanySsiDetailsRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanySsiDetailsRepositoryTests.cs

add optional search options for the company name and credential type
add company name to response
To be able to display the name of the company on the frontend and specifically search for ssi details by company name
N/A - Jira Ticket: CPLP-2978

feat(ssi): enhance GET credentials endpoint

---

src/portalbackend/PortalBackend.DBAccess/Models/CompanyAddressDetailData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs

added companyRole filed to ownCompanyDetails endpoint
added companyRole filed to ownCompanyDetails endpoint
[CPLP-2940](https://jira.catena-x.net/browse/CPLP-2940)

feat(adminisration)! : added companyRole filed to ownCompanyDetails endpoint

---

CHANGELOG.md
src/Directory.Build.props
src/externalsystems/Custodian.Library/CustodianService.cs
src/externalsystems/Custodian.Library/Models/WalletErrorResponse.cs
src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
src/marketplace/Offers.Library.Web/OfferDocumentService.cs
src/marketplace/Offers.Library/Service/OfferService.cs
src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Models/CompanyAddressDetailData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
tests/marketplace/Offer.Library.Web.Tests/OfferDocumentServiceTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs

release(1.6.0-RC3): merge release into main

---

CHANGELOG.md
src/Directory.Build.props
src/externalsystems/Custodian.Library/CustodianService.cs
src/externalsystems/Custodian.Library/Models/WalletErrorResponse.cs
src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
src/marketplace/Offers.Library.Web/OfferDocumentService.cs
src/marketplace/Offers.Library/Service/OfferService.cs
src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Models/CompanyAddressDetailData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
tests/marketplace/Offer.Library.Web.Tests/OfferDocumentServiceTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs

Merge the latest main to dev
To have the latest main changes available in dev
N/A

release(1.6.0-RC3): merge main to dev

---

src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs

Change appInstanceId to iamClientId for provider endpoint
The frontend needs the iamClientId
N/A - Jira Issue: CPLP-2983

fix(app): change appInstanceId to iamClientId for provider endpoint

---

src/administration/Administration.Service/appsettings.json
src/marketplace/Apps.Service/appsettings.json
src/marketplace/Services.Service/appsettings.json
src/notifications/Notifications.Service/appsettings.json
src/portalbackend/PortalBackend.Migrations/appsettings.json
src/processes/Processes.Worker/appsettings.json
src/provisioning/Provisioning.Migrations/appsettings.json
src/registration/Registration.Service/appsettings.json

Adjust overrides for serilog logging
Currently the overrides are not taken correctly, with this PR thats fixed.
N/A
[#46](https://github.com/eclipse-tractusx/portal-cd/pull/46)

chore: adjust logging for serilog

---

CHANGELOG.md
src/Directory.Build.props

bump version for v1.6.0-RC6
update changelog for v1.6.0-RC6
to have the latest version and a up to date changelog
N/A

release: bump version for v1.6.0-RC6

---

CHANGELOG.md
src/Directory.Build.props
src/externalsystems/Custodian.Library/Custodian.Library.csproj
src/externalsystems/Custodian.Library/CustodianService.cs
src/externalsystems/Custodian.Library/Models/WalletErrorResponse.cs
src/keycloak/Keycloak.Authentication/ControllerExtensions.cs
src/mailing/Mailing.Template/EmailTemplates/portal_welcome_email.html
src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppsController.cs
src/marketplace/Offers.Library/Service/IOfferSetupService.cs
src/marketplace/Offers.Library/Service/OfferSetupService.cs
src/portalbackend/PortalBackend.DBAccess/Models/TriggerProviderInformation.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
src/portalbackend/PortalBackend.PortalEntities/Enums/VerifiedCredentialExternalTypeId.cs
src/processes/OfferSubscription.Executor/OfferSubscriptionProcessTypeExecutor.cs
tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
tests/processes/OfferSubscription.Executor.Tests/OfferSubscriptionProcessTypeExecutorTests.cs

merge release branch to main
to have the latest version available in the main branch
N/A

release(1.6.0-RC6): merge release into main

---

CHANGELOG.md
src/Directory.Build.props
src/externalsystems/Custodian.Library/Custodian.Library.csproj
src/externalsystems/Custodian.Library/CustodianService.cs
src/externalsystems/Custodian.Library/Models/WalletErrorResponse.cs
src/keycloak/Keycloak.Authentication/ControllerExtensions.cs
src/mailing/Mailing.Template/EmailTemplates/portal_welcome_email.html
src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppsController.cs
src/marketplace/Offers.Library/Service/IOfferSetupService.cs
src/marketplace/Offers.Library/Service/OfferSetupService.cs
src/portalbackend/PortalBackend.DBAccess/Models/TriggerProviderInformation.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
src/portalbackend/PortalBackend.PortalEntities/Enums/VerifiedCredentialExternalTypeId.cs
src/processes/OfferSubscription.Executor/OfferSubscriptionProcessTypeExecutor.cs
tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
tests/processes/OfferSubscription.Executor.Tests/OfferSubscriptionProcessTypeExecutorTests.cs

merge main to dev
to have the latest changes from main available in dev as well
N/A

release(1.6.0-RC6): merge main to dev

---

src/administration/Administration.Service/Controllers/UserController.cs
src/administration/Administration.Service/appsettings.json
src/framework/Framework.Logging/LoggingExtensions.cs
src/maintenance/Maintenance.App/appsettings.json
src/marketplace/Apps.Service/appsettings.json
src/marketplace/Offers.Library/Service/OfferSetupService.cs
src/marketplace/Services.Service/appsettings.json
src/notifications/Notifications.Service/appsettings.json
src/processes/Processes.Worker/appsettings.json
src/registration/Registration.Service/appsettings.json
tests/administration/Administration.Service.Tests/Controllers/UserControllerTest.cs
tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs

remove machine name, processId, threadId from the logging message
rendered message included in log
to steamline the logging message
N/A - Jira Issue: CPLP-3089
[#64](https://github.com/eclipse-tractusx/portal-cd/pull/64)

feat(logging): adjust logging configuration

---

LICENSES/CC-BY-4.0.txt
src/mailing/Mailing.Template/Images/Catena-X long.license
src/mailing/Mailing.Template/Images/User Icon Picture.license

- change license notice for images
- add second license
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07
n/a

chore(trg-7-07): change license notice for images

---

src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppReleaseBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs

removed appRelease-UpdateApp endpoint
removed old endpoint appRelease-UpdateApp currently not using.
[CPLP-3026.](https://jira.catena-x.net/browse/CPLP-3026)

feat(appRelease)!: removed appRelease-UpdateApp endpoint

---

src/externalsystems/Bpdm.Library/BpdmService.cs
src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityDto.cs
tests/externalsystems/Bpdm.Library/BPNAccessTest.cs
tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs

fix legal-entity by bpn endpoint
Currently when requesting the bpn endpoint the json deserialization fails, with this pr this is fixed
N/A - Jira Issue: CPLP-3164

fix(bpdm): fix legal-entity by bpn endpoint

---

.tractusx
CHANGELOG.md
src/Directory.Build.props

bump version for v1.6.0-RC7
update changelog for v1.6.0-RC7
add file headers
to prepare the release branch for the latest release
N/A

release: bump version for v1.6.0-RC7

---

src/administration/Administration.Service/Controllers/UserController.cs

removing the obsolete endpoints
removing the obsolete endpoints, which are not in use
[CPLP-3024.](https://jira.catena-x.net/browse/CPLP-3024)

chore: removing the obsolete endpoints

---

src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppsController.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionStatusData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs

removed pagination for app subscription-Status
removed pagination function for app subscription-Status to support FE
[CPLP-3047](https://jira.catena-x.net/browse/CPLP-3047)

fix(apps)!: removed pagination for app subscription-Status

---

docker/notice-iam-seeding.md
src/administration/Administration.Service/Models/SsiCertificateData.cs
src/externalsystems/Bpdm.Library/Models/BpdmSharingState.cs
src/framework/Framework.Seeding/JsonHelper/SnakeCaseNamingPolicy.cs
src/framework/Framework.Token/GetTokenSettings.cs
src/marketplace/Apps.Service/Extensions/AppExtensions.cs
src/marketplace/Offers.Library/Models/OfferDeclineRequest.cs
src/portalbackend/PortalBackend.DBAccess/Models/AppUseCaseData.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferDocumentContentData.cs
src/portalbackend/PortalBackend.DBAccess/Models/OperatorBpnData.cs
src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditConnector20230405.cs
src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditConnector20230503.cs
src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditConnector20230803.cs
src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditIdentity20230526.cs
src/portalbackend/PortalBackend.PortalEntities/Entities/Identity.cs
src/portalbackend/PortalBackend.PortalEntities/Entities/OfferSubscriptionProcessData.cs
src/portalbackend/PortalBackend.PortalEntities/Entities/VerifiedCredentialExternalType.cs
src/portalbackend/PortalBackend.PortalEntities/Entities/VerifiedCredentialExternalTypeUseCaseDetailVersion.cs
src/portalbackend/PortalBackend.PortalEntities/Enums/MediaTypeId.cs
src/portalbackend/PortalBackend.PortalEntities/Enums/VerifiedCredentialExternalTypeId.cs
src/provisioning/Provisioning.Library/Extensions/ProtocolMapperSettings.cs
src/provisioning/Provisioning.Library/Models/CompanyNameIdpAliasData.cs
tests/administration/Administration.Service.Tests/Usings.cs
tests/framework/Framework.Web.Tests/Usings.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/ContentTypeMapperExtensionsTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/InvitationRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/PortalDbContextTests.cs
tests/provisioning/Provisioning.Library.Tests/FlurlSetup/FlurlSetupExtensions.cs

- add file header
- change name in Docker Hub notice for seeding iam image
https://github.com/eclipse-tractusx/portal-backend/issues/220

chore: add file header

---

.github/workflows/release.yml
.github/workflows/release_iam-seeding.yml

change trigger for iam release workflow
prefix of tag doesn't comply with SemVer requirement 
https://github.com/eclipse-tractusx/portal-backend/issues/207#issuecomment-1686565406

fix(release): change trigger for iam workflow

---

src/marketplace/Offers.Library/Models/OfferSubscriptionStatusDetailData.cs
src/marketplace/Offers.Library/Service/OfferService.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionStatusData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs

added subscription id to subscriptionStatus endpoint
added subscriptionId to Subscription-Status for app service endpoint
[CPLP-3178](https://jira.catena-x.net/browse/CPLP-3178)

feat(app& service): added subscription id to subscriptionStatus endpoint

---

CHANGELOG.md
src/Directory.Build.props

- update changelog
- bump version for v1.6.0
to prepare the branch for the release 1.6.0
N/A

release: bump version for v1.6.0

---

src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/connector_assigned_offer_subscriptions.test.json

added connector details for subscriber endpoint
enhanced existing endpoint with connector details
[CPLP-3177](https://jira.catena-x.net/browse/CPLP-3177)

feat(app&Service) : added connector details for subscriber endpoint

---

src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppsController.cs
src/marketplace/Apps.Service/ViewModels/AppStatusIdFilter.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs

Apply filter and sort.
Apply filter and sort by date search record by name.
CPLP-3206.

feat(apps): add status filter to GET: apps/provided

---

SECURITY.md

update security.md
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01/#security-file

docs: update security.md

---

src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Models/ConnectorData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IConnectorsRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/connectors.test.json

Added TechnicalUser Data.
added TechnicalUser Data to Connector endpoints
[CPLP-3201](https://jira.catena-x.net/browse/CPLP-3201)

feat(connector): Added technicalUser Data

---

src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Models/AllOfferStatusData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs

added leadiamge id and datelastchanged fields
Additional fields added to existing endpoint
[CPLP-3169](https://jira.catena-x.net/browse/CPLP-3169)

fix(service) : added leadiamge id and datelastchanged fields

---

src/mailing/Mailing.Template/Enums/EmailTemplateType.cs
src/mailing/Mailing.Template/Mailing.Template.csproj
src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
src/marketplace/Apps.Service/appsettings.json
src/marketplace/Offers.Library/Service/IOfferService.cs
src/marketplace/Offers.Library/Service/OfferService.cs
src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
src/marketplace/Services.Service/ServiceSettings.cs
src/marketplace/Services.Service/appsettings.json
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
tests/marketplace/Apps.Service.Tests/appsettings.IntegrationTests.json
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
tests/marketplace/Services.Service.Tests/appsettings.IntegrationTests.json

added Activation Email Notification
added Activation email Notification for approveApp and approveService endpoints
N/A Ref : [CPLP-3202](https://jira.catena-x.net/browse/CPLP-3202)
[Link to pull request from other repository.](https://github.com/eclipse-tractusx/portal-cd/pull/87)

feat(app&service) : added Activation email Notification for approveApp and approveService endpoints

---

src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
src/administration/Administration.Service/Models/IdentityProviderDetails.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IIdentityProviderRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
src/portalbackend/PortalBackend.Migrations/Seeder/Data/iam_identity_providers.consortia.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/identity_providers.consortia.json
tests/administration/Administration.Service.Tests/BusinessLogic/IdentityProviderBusinessLogicTests.cs

fix GET: api/administration/identityprovider/owncompany/identityproviders
fix GET: api/administration/identityprovider/owncompany/identityproviders/{identityTypeId}
currently when requesting one of the above endpoints with an idp not existing in keycloak the request fails
N/A - Jira Issue: CPLP-3247

fix(idp): adjust get idps endpoints

---

src/marketplace/Services.Service/Controllers/ServicesController.cs

Updated roles for service endpoint
Updated roles for the service endpoint
N/A Ref: CPLP-3198

feat(service): updated roles

---

src/administration/Administration.Service/Controllers/CompanyDataController.cs

Adjusting the swagger documentation for the ssi endpoints
To have a better understandable description for users of the swagger
N/A - Jira Issue: CPLP-3199

fix(ssi): adjust swagger documentation

---

src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
src/marketplace/Services.Service/ServiceSettings.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
tests/marketplace/Apps.Service.Tests/appsettings.IntegrationTests.json
tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
tests/marketplace/Services.Service.Tests/appsettings.IntegrationTests.json

added ActivationPortalAddress url
added ActivationPortalAddress url for activation Email Notification
N/A Ref: CPLP-3202
[Link to pull request from other repository.](https://github.com/eclipse-tractusx/portal-cd/pull/93)

chore(app&service): added ActivationPortalAddress url

---

src/registration/Registration.Service/BusinessLogic/INetworkBusinessLogic.cs
src/registration/Registration.Service/BusinessLogic/NetworkBusinessLogic.cs
src/registration/Registration.Service/Controllers/NetworkController.cs
src/registration/Registration.Service/Program.cs
tests/registration/Registration.Service.Tests/BusinessLogic/NetworkBusinessLogicTests.cs
tests/registration/Registration.Service.Tests/Controller/NetworkControllerTests.cs

Add NetworkBusinessLogic Registration
Currently the submit endpoint is failing
N/A - Jira Issue: CPLP-3197

fix: add networkBl registration

---

src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs

Saving the notifications when subscribing to an offer
Currently the created notifications are never saved to the database.
N/A - Jira Issue: CPLP-3288

fix(subscriptions): fix notification save

---

src/marketplace/Services.Service/Controllers/ServicesController.cs
src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json

fixed typo and updated userRole for service endpoint
fixed typo in seeding data and updated userRole for service endpoint
N/A Ref: Test-1177,CPLP-3269

fix : fixed typo in seeding data and updated userRole for service endpoint

---

src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs

Add logging for endpoints that get called by external services
To be able to see what the external services send us.
N/A - Jira Issue: CPLP-2998

chore: add logging to external callable endpoints

---

src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Offers.Library/Models/OfferCompanySubscriptionStatusResponse.cs
src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferCompanySubscriptionStatusData.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offer_subscriptions.test.json
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/process_steps.test.json
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/processes.test.json

added processStepTypeId to existing endpoints
added processStepTypeId to an existing endpoints to fetch latest subscription processStepTypeId
N/A Ref : CPLP-3251

feat(app&Service) : added processStepTypeId to existing endpoints

---

src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
src/administration/Administration.Service/Models/CompanyInvitationData.cs
src/administration/Administration.Service/Models/OwnCompanyUserEditableDetails.cs
src/administration/Administration.Service/Models/UserCreationInfoIdp.cs
src/framework/Framework.Models/ValidationExpressions.cs
src/provisioning/Provisioning.Library/Models/UserCreationInfo.cs
tests/administration/Administration.Service.Tests/Administration.Service.Tests.csproj
tests/administration/Administration.Service.Tests/BusinessLogic/InvitationBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/BusinessLogic/NetworkBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/Models/CompanyInvitationDataTests.cs
tests/administration/Administration.Service.Tests/Models/OwnCompanyUserEditableDetails.cs
tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
tests/shared/Tests.Shared/Extensions/IFixtureExtensions.cs

Add email validation to invitation, network registration and user invitation
currently the email validation is not correctly validating an email correctly, with this change we switched to use the EmailAddress Attribute
N/A - Jira Issue: CPLP-3358

feat(validation): add email validation

---

src/mailing/Mailing.Template/EmailTemplates/osp_welcome_email.html
src/processes/NetworkRegistration.Library/Models/UserMailInformation.cs
src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs

replace the idpAlias with the companyName for the osp mail
To give the user a better understandable mail
N/A - Jira Issue: CPLP-2639

fix(osp): add companyName to osp mail

---

CHANGELOG.md
src/Directory.Build.props

bump version for v1.7.0-RC2
update changelog for v1.7.0-RC2
To have a new version available
N/A

release: bump version for v1.7.0-RC2

---

src/administration/Administration.Service/BusinessLogic/UserRolesBusinessLogic.cs
src/framework/Framework.Async/AsyncIfAnyExtensions.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs

Adjusting the handling of user role assignments with multiple client ids.
Currently assigning roles to an offer with multiple client ids fails
Refs: N/A - Jira Issue: TEST-1537

fix(userrole): fix user role assignment

---

CHANGELOG.md
src/Directory.Build.props

update changelog  for v1.7.0-RC3
bump version for v1.7.0-RC3
To have a new version available
N/A

release: bump version for v1.7.0-RC3

---

src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_assigned_collections.consortia.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_descriptions.consortia.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_roles.consortia.json

Adjusted the seeding to add the new irs management role and the assignments to the company roles
To have the new role available in the portal
N/A - Jira Issue: CPLP-3475

feat(seeding): add irs management role

---

.github/workflows/release_candidate_iam-seeding.yml

add release candidate workflow for iam-seeding
enable iam-seeding for release candidate phase
relates to https://github.com/eclipse-tractusx/portal-backend/pull/346

build(iam-seeding): add release candidate workflow

---

CHANGELOG.md
src/Directory.Build.props

* update changelog for v1.7.0-RC4
* bump version for v1.7.0-RC4
To have the latest changes of the release in the change log
N/A

release: update changelog for v1.7.0-RC4

---

src/framework/Framework.ProcessIdentity/DependencyInjection/ProcessIdentityServiceCollectionExtensions.cs
src/keycloak/Keycloak.Authentication/KeycloakClaimsTransformation.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
src/processes/Processes.Worker/Program.cs

We're validating the identityType or companyId for most of our endpoints, therefore the values must be present in the claims, currently they are not correctly set. With this fix the identityType and companyId are set correctly.
Currently most of the endpoints return a 403.
N/A - Jira Issue: CPLP-3102

fix(claims): add identityType and CompanyId claim

---

CHANGELOG.md
src/Directory.Build.props

* update the changelog for release v1.7.0
* bump version for release v1.7.0
To have all changes which were introduced since release v1.6.0
N/A

release: update changelog for v1.7.0

---

src/framework/Framework.ErrorHandling.Web/GeneralHttpErrorHandler.cs
tests/framework/Framework.ErrorHandling.Web.Tests/GeneralHttpErrorHandlerTests.cs

Fixing inner exception handling in the general error handling
there was an infinity loop introduced in #315
N/A - Jira Issue: CPLP-3590

fix(errorHandling): fix innerException handling

---

src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_descriptions.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_roles.json

added seeding data for userRole
added seeding data for technical user in userRole
N/A  Ref: CPLP-3582

feat(portal): added seeding data for userRole

---

src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
src/maintenance/Maintenance.App/BatchDeleteService.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/AgreementRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRolesRepository.cs
src/portalbackend/PortalBackend.Migrations/Migrations/20240102115525_CPLP-3469-AddAgreementView.Designer.cs
src/portalbackend/PortalBackend.Migrations/Migrations/20240102115525_CPLP-3469-AddAgreementView.cs
src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.consortia.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json
src/portalbackend/PortalBackend.PortalEntities/Entities/Agreement.cs
src/portalbackend/PortalBackend.PortalEntities/Entities/AgreementStatus.cs
src/portalbackend/PortalBackend.PortalEntities/Enums/AgreementStatusId.cs
src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
src/portalbackend/PortalBackend.PortalEntities/Views/AgreementView.cs
src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/AgreementRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/AgreementViewTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRolesRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/agreements.test.json
tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs

added agreementStatus and agreementView.
Added agreementStatus  column to display active agreements and to create consent records for only active agreements
and created a agreementView to display agreementId, agreementName, agreementRole, agreementStatus and mandatory fields
N/A Ref: CPLP-3469

feat(Agreement): added agreementStatus and agreementView

---

CHANGELOG.md
src/mailing/Mailing.Template/EmailTemplates/decline_registration.html

Created Decline Registration template
When user decline the request then this template will be sent
n/a

feat(email template): created decline registration template

---

src/administration/Administration.Service/BusinessLogic/UserRolesBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Models/ClearinghouseData.cs
src/portalbackend/PortalBackend.DBAccess/Models/CompanyUserRoleWithId.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRolesRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/registration/Registration.Service/Controllers/RegistrationController.cs
tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
tests/endtoend/InterfacePartnerHealthCheck/BpdmEndToEndTests.cs
tests/endtoend/InterfacePartnerHealthCheck/SdFactoryEndPointTests.cs
tests/endtoend/InterfacePartnerHealthCheck/WalletEndPointTests.cs
tests/endtoend/NotificationInitScenario/ModifyCoreUserRoleScenario.cs
tests/endtoend/PortalHealthCheck/BaseDataLoadCheck.cs
tests/endtoend/PortalHealthCheck/RegistrationHealthCheck.cs
tests/endtoend/RegistrationScenarios/BpdmContent.cs
tests/endtoend/RegistrationScenarios/RegistrationEndpointHelper.cs
tests/endtoend/RegistrationScenarios/RegistrationScenarios.cs
tests/endtoend/ServiceAccountCUDScenarios/AdministrationEndpointHelper.cs
tests/endtoend/ServiceAccountCUDScenarios/ServiceAccountCUDScenarios.cs
tests/endtoend/appsettings.EndToEndTests.json

Fix end to end tests
Currently the end to end tests are running on an error on dev as well as int
N/A - Jira Ref: CPLP-3328

fix(e2e): adjust end to end tests

---

src/externalsystems/Custodian.Library/Custodian.Library.csproj
src/framework/Framework.ErrorHandling.Web/Framework.ErrorHandling.Web.csproj
tests/endtoend/EndToEnd.Tests.csproj

Fix security vulnerability for referenced external packages
There were some critical and high findings in the referenced package versions, those have now been updated.
[Dependabot finding](https://github.com/eclipse-tractusx/portal-backend/security/dependabot/3)
[Dependabot finding](https://github.com/eclipse-tractusx/portal-backend/security/dependabot/4)

chore: fix security vulnerability findings

---

.vscode/settings.json
DEPENDENCIES

update dependencies file and file header template
necessary chores

chore: update dependencies file and file header template

---

src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
src/administration/Administration.Service/ErrorHandling/AdministrationServiceAccountErrorMessageContainer.cs
src/administration/Administration.Service/Program.cs
src/provisioning/Provisioning.Library/ErrorHandling/ProvisioningServiceErrorMessageContainer.cs
src/provisioning/Provisioning.Library/Service/ServiceAccountCreation.cs
tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
tests/provisioning/Provisioning.Library.Tests/Extensions/ServiceAccountCreationTests.cs

Implement new error handling for the service controller
Implement for all POST and PUT endpoints the new error handling.
N/A Ref: CPLP-3589

feat(errorhandling): error handling service account controller

---

src/framework/Framework.Models/ValidationExpressions.cs
src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppsController.cs
src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
src/marketplace/Services.Service/Controllers/ServicesController.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionViewTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offer_subscriptions.test.json

Enhance endpoint in apps and services for offer subscription with filter company name
By providing the chance to search by customer company name
N/A - Jira Issue: CPLP-3459

feat(search): offer subscription enable search by company name

---

.github/workflows/release.yml
.github/workflows/release_iam-seeding.yml
.github/workflows/release_release_candidate.yml

add additional image tags of type semver
https://github.com/eclipse-tractusx/portal-backend/issues/358

build(release): add additional image tags of type semver

---

CHANGELOG.md

Update the changelog for the latest release
To give an overview of what was done since the last release
N/A

build: update changelog for v1.8.0-rc1

---

CHANGELOG.md
src/Directory.Build.props
src/portalbackend/PortalBackend.Migrations/Migrations/20240115113526_1.8.0-rc1.cs

Fix the last migration
The current migration is failing when upgrading from v1.7.0-RC4
N/A

fix(migration): add insert script to migration

---

CHANGELOG.md
src/Directory.Build.props

* update changelog for v1.8.0-RC2
* bump version for v1.8.0-RC2
To have the latest changes available in the changelog
N/A

build: update changelog for v1.8.0-RC2

---

CHANGELOG.md
src/Directory.Build.props
src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/registration/Registration.Service/Controllers/RegistrationController.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/notifications.test.json
tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs

Merge release into main
To have the latest changes available in main
N/A

build: merge release to main

---

CHANGELOG.md
src/Directory.Build.props
src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/registration/Registration.Service/Controllers/RegistrationController.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/notifications.test.json
tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs

Merge the latest changes from main to dev
To have the latest changes from main available in dev
N/A

build: merge main to dev

---

src/administration/Administration.Service/Administration.Service.csproj
src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/IdentityProviderSettings.cs
src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/administration/Administration.Service/Program.cs
src/administration/Administration.Service/appsettings.json
src/mailing/Mailing.Service/IRoleBaseMailService.cs
src/mailing/Mailing.Service/Mailing.Service.csproj
src/mailing/Mailing.Service/RoleBaseMailService.cs
src/mailing/Mailing.Template/EmailTemplates/deactivate_managed_idp.html
src/mailing/Mailing.Template/EmailTemplates/delete_managed_idp.html
src/mailing/Mailing.Template/Enums/EmailTemplateType.cs
src/marketplace/Offers.Library/DependencyInjection/OfferSetupServiceExtensions.cs
src/marketplace/Offers.Library/Service/OfferService.cs
src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IIdentityProviderRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IIdentityRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/IdentityProviderBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
tests/mailing/Mailing.Service.Tests/RoleBaseMailServiceTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/IdentityProviderRepositoryTests.cs

* enable delete of managed idps
* enable deactivation of managed idps
to have the possibility to delete or deactivate the managed idps
N/A - Jira Issue: CPLP-3329
[#135](https://github.com/eclipse-tractusx/portal-cd/pull/135)

feat(idp): adjust delete idp endpoint

---

.github/workflows/release.yml
.github/workflows/release_iam-seeding.yml
.github/workflows/release_release_candidate.yml

add additional image tag of type semver
https://github.com/eclipse-tractusx/portal-backend/issues/358

build(release): add additional image tag of type semver

---

src/keycloak/Keycloak.Authentication/Keycloak.Authentication.csproj
src/maintenance/Maintenance.App/Maintenance.App.csproj
tests/endtoend/EndToEnd.Tests.csproj
tests/framework/Framework.Web.Tests/JwtBearerConfigurationHealthCheckTests.cs

Upgrade packages with security vulnerabilities security findings
Because they have security vulnerabilities
N/A - Jira Issue: CPLP-3653

chore: update package dependencies

---

src/maintenance/Maintenance.App/Maintenance.App.csproj

Upgrade packages with security vulnerabilities security findings
Because they have security vulnerabilities
N/A - Jira Issue: CPLP-3653

chore: update external package

---

src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs

Fix sonar cloud finding to use the correct pagination params
Sonar found two code smells
#430

fix(user): fix pagination of GetOwnCompanyUserDatasAsync

---

src/externalsystems/Bpdm.Library/BpdmService.cs
src/externalsystems/Bpdm.Library/BusinessLogic/BpdmBusinessLogic.cs
src/externalsystems/Bpdm.Library/IBpdmService.cs
src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityOutputData.cs
tests/externalsystems/Bpdm.Library/BpdmBusinessLogicTests.cs
tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs

* set sharing state to ready
* ignore nullable values for bpdm push
The bpdm push is returning a 400, therefor the nullable values are ignored
#450

fix(bpdm): fix bpdm push

---

docker/Dockerfile-maintenance-service
docker/Dockerfile-portal-migrations
src/framework/Framework.Async/Framework.Async.csproj
src/framework/Framework.Cors/Framework.Cors.csproj
src/framework/Framework.DBAccess/Framework.DBAccess.csproj
src/framework/Framework.DateTimeProvider/Framework.DateTimeProvider.csproj
src/framework/Framework.DependencyInjection/Framework.DependencyInjection.csproj
src/framework/Framework.ErrorHandling.Web/Framework.ErrorHandling.Web.csproj
src/framework/Framework.ErrorHandling/Framework.ErrorHandling.csproj
src/framework/Framework.HttpClientExtensions/Framework.HttpClientExtensions.csproj
src/framework/Framework.IO/Framework.IO.csproj
src/framework/Framework.Linq/Framework.Linq.csproj
src/framework/Framework.Logging/Framework.Logging.csproj
src/framework/Framework.Models/Framework.Models.csproj
src/framework/Framework.Seeding/Framework.Seeding.csproj
src/framework/Framework.Swagger/Framework.Swagger.csproj
src/framework/Framework.Token/Framework.Token.csproj
src/framework/Framework.Web/Framework.Web.csproj

Adjust maintenance and migration docker build file
The build for maintenance and migration currently fails
N/A - Jira Issue: CPLP-3400

fix(nuget): adjust docker images

---

.github/workflows/administration-service.yml
.github/workflows/maintenance-service.yml
.github/workflows/marketplace-app-service.yml
.github/workflows/notification-service.yml
.github/workflows/portal-migrations.yml
.github/workflows/processes-worker.yml
.github/workflows/provisioning-migrations.yml
.github/workflows/registration-service.yml
.github/workflows/services-service.yml
docker/Dockerfile-provisioning-migrations

Adjust docker entry point for provisioning.migration
the provisioning migration was renamed but the docker entry point wasn't adjusted
N/A

fix(docker): adjust docker entry point

---

CHANGELOG.md
src/Directory.Build.props

* update changelog for v1.8.0-RC5
* bump version for v1.8.0-RC5
to have the latest changes available in the changelog
[#166](https://github.com/eclipse-tractusx/portal-cd/issues/166)

build: bump version for v1.8.0-RC5

---

.github/workflows/nuget-package-push.yml
scripts/get_current_version.sh
scripts/no_suffix_version_check.sh

Adjusted the nuget push script
Currently the action is failing
N/A

fix(nuget): fix nuget package push

---

CHANGELOG.md
src/Directory.Build.props

* update changelog for v1.8.0-RC6
* bump version to v1.8.0-RC6
To have the latest changes in the changelog
Refs: https://github.com/eclipse-tractusx/portal-cd/issues/167

build: change log 1.8.0-RC6

---

CHANGELOG.md
src/Directory.Build.props

* update changelog for v1.8.0-RC7
* bump version for v1.8.0-RC7
To prepare the latest release
[#168](https://github.com/eclipse-tractusx/portal-cd/issues/168)

build: update changelog for v1.8.0-RC7

---

.github/workflows/administration-service.yml
.github/workflows/maintenance-service.yml
.github/workflows/marketplace-app-service.yml
.github/workflows/notification-service.yml
.github/workflows/portal-migrations.yml
.github/workflows/processes-worker.yml
.github/workflows/provisioning-migrations.yml
.github/workflows/registration-service.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/release_release_candidate.yml
.github/workflows/services-service.yml
.tractusx
NOTICE.md
README.md

change portal-cd references to portal
TRG-2.04 compliance
https://github.com/eclipse-tractusx/portal-cd/issues/131

chore(trg-2.04): change portal-cd references to portal

---

.github/workflows/administration-service.yml
.github/workflows/maintenance-service.yml
.github/workflows/marketplace-app-service.yml
.github/workflows/notification-service.yml
.github/workflows/portal-migrations.yml
.github/workflows/processes-worker.yml
.github/workflows/provisioning-migrations.yml
.github/workflows/registration-service.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/release_release_candidate.yml
.github/workflows/services-service.yml
.tractusx
NOTICE.md
README.md

change portal-cd references to portal
TRG-2.04 compliance
Ref: https://github.com/eclipse-tractusx/portal-cd/issues/131

chore(trg-2.04): change portal-cd references to portal (#542)

---

src/administration/Administration.Service/Controllers/CompanyDataController.cs

Updated swagger doc for endpoint  GET /api/administration/companydata/companyCertificates
Changed swagger doc for dummy example of  result.
#470 

docs(swagger): updated swagger endpoint doc

---

CHANGELOG.md
FILEHEADER.md
README.md
docker/notice-administration-service.md
docker/notice-iam-seeding.md
docker/notice-maintenance-service.md
docker/notice-marketplace-app-service.md
docker/notice-notification-service.md
docker/notice-portal-migrations.md
docker/notice-processes-worker.md
docker/notice-provisioning-migrations.md
docker/notice-registration-service.md
docker/notice-services-service.md
docs/nuget/update-nuget-packages.md
scripts/check-dependencies.md
src/Directory.Build.props
src/keycloak/Keycloak.Library/Models/Clients/ClientConfig.cs
src/keycloak/Keycloak.Library/Models/ProtocolMappers/Config.cs
src/keycloak/Keycloak.Seeding/BusinessLogic/ClientsUpdater.cs
src/keycloak/Keycloak.Seeding/BusinessLogic/ProtocolMappersUpdater.cs

Merge the latest release changes into dev
To have the latest changes from main available in the dev branch
Refs: https://github.com/eclipse-tractusx/portal-cd/issues/188

build: merge main into dev

---

src/administration/Administration.Service/Models/CompanyInvitationData.cs

Changed the CompanyInvitationData to class instead of record
The EmailAddress Attribute in record data types lead to an error
Refs: CPLP-3383

fix(invitation): adjust invitation model

---

src/web/Web.Identity/Web.Identity.csproj
tests/framework/Framework.Tests.Shared/Framework.Tests.Shared.csproj

remove unused deprecated packages
https://github.com/eclipse-tractusx/portal-backend/issues/581

chore(dependencies): remove unused deprecated packages

---

src/portalbackend/PortalBackend.DBAccess/Models/ConnectorData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs

add ConnectorURL inside the response body (fetched from portal.connectors).
Endpoint:  /api/administration/Connectors
Endpoint:  /api/administration/Connectors/managed
Endpoint:  /api/administration/Connectors/{connectorID}
Update Connector controller and respective api endpoint bodies to provide extended information to the user.
add ConnectorURL inside the response body (fetched from portal.connectors).
#548 

feat(connector): connector controller add connectorUrl parameter in response body

---

.github/workflows/codeql.yml
.github/workflows/dependencies.yaml
.github/workflows/pre-checks.yml
.github/workflows/sonarcloud.yml
CONTRIBUTING.md
README.md
scripts/check-dependencies.md

- chore(pre-checks and sonar): run only on changes to src/**
- docs: remove shared components reference --> not relevant for backend readme
- docs(CONTRIBUTING.md): link to contribution details
- chore(codeql): run workflow on push to dev branch
- chore: update eclipse dash tool
na
https://github.com/eclipse-tractusx/portal-frontend/issues/566

chore: improve workflows and docs

---

src/administration/Administration.Service/Controllers/ConnectorsController.cs
src/administration/Administration.Service/Models/ConnectorInputModel.cs
src/portalbackend/PortalBackend.DBAccess/Models/ConnectorData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs

Connector controller endpoints summary and parameter name description changed.
Update Connector controller and respective api endpoint bodies due to latest changes made in the SSINext solution.
Endpoint:  /api/administration/Connectors
Method: GET
Endpoint:  /api/administration/Connectors
Method: POST
Endpoint:  /api/administration/Connectors/managed
Method: GET
Endpoint:  /api/administration/Connectors/managed
Method: POST
Endpoint:  /api/administration/Connectors/{connectorID}
Method: GET
Endpoint: /api/administration/Connectors/discovery
Method: POST
Endpoint: /api/administration/Connectors/clearinghouse/selfDescription
Method: POST
#546 

feat(summary): connector controller refactoring description and endpoint details

---

src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_assigned_collections.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_descriptions.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_roles.json
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRoleCollectionRolesViewTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs

remove:
- BPDM Gate Read
- BPDM Gate Read & Write
- BPDM Partner Gate
- BPDM Management
- BPDM Pool
add:
- BPDM Sharing Admin
- BPDM Sharing Input Manager
- BPDM Sharing Input Consumer
- BPDM Sharing Output Consumer
- BPDM Pool Admin
- BPDM Pool Consumer
https://github.com/eclipse-tractusx/portal-iam/issues/66

chore(roles-seeding): update bpdm roles

---

src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/IAppChangeBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppChangeController.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferRoleInfos.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRolesRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppChangeControllerTest.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs

created endpoint to fetch activeAppRoleDetails
An endpoint to fetch active App user role details
Ref : #573

fix: created endpoint to fetch activeAppRoleDetails

---

CHANGELOG.md
src/Directory.Build.props

* adjust changelog for v2.0.0-RC1
* bump version for v2.0.0-RC1
To have the latest changes in the changelog
[#211](https://github.com/eclipse-tractusx/portal/issues/211)

build: bump version for v2.0.0-RC1

---

src/externalsystems/Bpdm.Library/BpdmService.cs
src/externalsystems/Bpdm.Library/BpnAccess.cs
src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityDto.cs
src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityOutputData.cs
src/externalsystems/Bpdm.Library/Models/BpdmSharingState.cs
tests/externalsystems/Bpdm.Library/BPNAccessTest.cs
tests/externalsystems/Bpdm.Library/BpdmBusinessLogicTests.cs
tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs

* adjust bpdm urls
* adjust bpdm response types
* adjust bpdm request types
The bpdm service did change its implementation and adjusted some endpoints.
Refs: #636

fix(bpdm): adjust bpdm urls and requests

---

src/externalsystems/Bpdm.Library/BpdmService.cs
src/externalsystems/Bpdm.Library/BpnAccess.cs
tests/externalsystems/Bpdm.Library/BPNAccessTest.cs

bdpm: move api path out of codeand into config / helm chart
see https://github.com/eclipse-tractusx/portal/pull/251 for change in helm chart
https://github.com/eclipse-tractusx/portal/issues/248

chore(bdpm): move api path out of code

---

src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/CompanyDataSettings.cs
src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
src/administration/Administration.Service/Controllers/CompanyDataController.cs
src/administration/Administration.Service/Models/DimUrlsResponse.cs
src/administration/Administration.Service/appsettings.json
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
src/portalbackend/PortalBackend.Migrations/Seeder/BatchInsertSeeder.cs
tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_wallet_data.test.json

* add GET: api/administration/companydata/decentralidentity/urls endpoint
To give the user the information of the company wallet
Refs: #643

feat(dim): add get dim service urls endpoint

---

src/externalsystems/Dim.Library/Schemas/DidDocument.schema.json
tests/externalsystems/Dim.Library.Tests/DimBusinessLogicTests.cs

adjust did json schema validation
To match the current schema
N/A

feat(did): adjust did schema

---

src/portalbackend/PortalBackend.Migrations/Migrations/20240423033553_2.0.0-rc3.Designer.cs
src/portalbackend/PortalBackend.Migrations/Migrations/20240423033553_2.0.0-rc3.cs

Merge all migrations since rc2 into one
To have one migration for the rc
Refs: #659

build(2.0.0-rc3): merge migrations

---

CHANGELOG.md
src/Directory.Build.props

*  bump version for v2.0.0-RC3
* adjust changelog for v2.0.0-RC3
To have a new version for the release
Refs: https://github.com/eclipse-tractusx/portal/issues/264

build: bump version for v2.0.0-RC3

---

src/externalsystems/Bpdm.Library/DependencyInjection/BpdmServiceCollectionExtension.cs
src/externalsystems/BpnDidResolver.Library/BpnDidResolverService.cs
src/externalsystems/BpnDidResolver.Library/DependencyInjection/BpnDidResolverServiceCollectionExtension.cs
src/externalsystems/Clearinghouse.Library/ClearinghouseServiceCollectionExtension.cs
src/externalsystems/Custodian.Library/CustodianServiceCollectionExtension.cs
src/externalsystems/Dim.Library/DependencyInjection/DimServiceCollectionExtension.cs
src/externalsystems/IssuerComponent.Library/DependencyInjection/IssuerComponentServiceCollectionExtensions.cs
src/framework/Framework.Async/Directory.Build.props
src/framework/Framework.Cors/Directory.Build.props
src/framework/Framework.DBAccess/Directory.Build.props
src/framework/Framework.DateTimeProvider/Directory.Build.props
src/framework/Framework.DependencyInjection/Directory.Build.props
src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
src/framework/Framework.ErrorHandling.Web/Directory.Build.props
src/framework/Framework.ErrorHandling/Directory.Build.props
src/framework/Framework.HttpClientExtensions/Directory.Build.props
src/framework/Framework.HttpClientExtensions/HttpClientExtensions.cs
src/framework/Framework.IO/Directory.Build.props
src/framework/Framework.Linq/Directory.Build.props
src/framework/Framework.Logging/Directory.Build.props
src/framework/Framework.Models/Directory.Build.props
src/framework/Framework.Seeding/Directory.Build.props
src/framework/Framework.Swagger/Directory.Build.props
src/framework/Framework.Token/Directory.Build.props
src/framework/Framework.Web/Directory.Build.props

Only setting the base url for needed services
The SdFactory doesn't expect a trailing slash when calling the service
N/A

fix(sdFactory): adjust base url setup

---

CHANGELOG.md
src/Directory.Build.props
src/portalbackend/PortalBackend.Migrations/Migrations/20240424073406_2.0.0-rc4.Designer.cs
src/portalbackend/PortalBackend.Migrations/Migrations/20240424073406_2.0.0-rc4.cs

* merge migrations for v2.0.0-RC4
* adjust changelog for v2.0.0-RC4
* bump version for v2.0.0-RC4
To have a new version for the latest release
https://github.com/eclipse-tractusx/portal/issues/276

build: bump version for v2.0.0-RC4

---

src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
src/administration/Administration.Service/Controllers/ServiceAccountController.cs
src/marketplace/Offers.Library/Service/OfferSetupService.cs
src/portalbackend/PortalBackend.DBAccess/Models/ServiceAccountData.cs
src/portalbackend/PortalBackend.DBAccess/Models/SubscriptionData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IProcessStepRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ProcessStepRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
src/processes/Processes.Worker/Processes.Worker.csproj
src/processes/Processes.Worker/Program.cs
src/provisioning/Provisioning.Library/Service/IServiceAccountCreation.cs
src/provisioning/Provisioning.Library/Service/ServiceAccountCreation.cs
tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
tests/provisioning/Provisioning.Library.Tests/Extensions/ServiceAccountCreationTests.cs

* adjust technical user process
* adjust authorisation policy type
* adjust database query
To have a running service account creation process for dim users
N/A

fix(technicalUser): adjust dim technical user creation 

---

CHANGELOG.md
src/Directory.Build.props

* adjust changelog for v2.0.0-RC5
* bump version for v2.0.0-RC5
To have a new version for the release
Refs: https://github.com/eclipse-tractusx/portal/issues/283

build: bump version for v2.0.0-RC5 

---

src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/CompanyDataSettings.cs
src/administration/Administration.Service/Models/DimUrlsResponse.cs
src/administration/Administration.Service/appsettings.json
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs

* enhance endpoint with issuer did, bpnl and did of the holder and url for the bpn did resolver
To return the necessary data to the customer
Refs: #683

feat(dim): adjust decentralidentity url endpoint

---

CHANGELOG.md
src/Directory.Build.props

bump version and update docs
https://github.com/eclipse-tractusx/portal/issues/308

build(v2.0.0-RC7): bump version and update docs

---

src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
src/administration/Administration.Service/Models/ServiceAccountDetails.cs
src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountWithRoleDataClientId.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
src/provisioning/Provisioning.Library/Extensions/ClientManager.cs
src/provisioning/Provisioning.Library/Models/ClientConfigData.cs
tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
tests/endtoend/ServiceAccountCUDScenarios/AdministrationEndpointHelper.cs
tests/endtoend/ServiceAccountCUDScenarios/ServiceAccountCUDScenarios.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs

Adjust the selection of the dim service account information
The dim service account does not have service account data set therefor a null error is thrown
Refs: #593

fix(dim-sa): adjust dim service account selection

---

DEPENDENCIES
src/framework/Framework.Seeding/Framework.Seeding.csproj
src/portalbackend/PortalBackend.PortalEntities/PortalBackend.PortalEntities.csproj
src/processes/Processes.ProcessIdentity/Processes.ProcessIdentity.csproj
src/provisioning/Provisioning.ProvisioningEntities/Provisioning.ProvisioningEntities.csproj

upgrade Npgsql and EntityFrameworkCore packages
EntityFrameworkCore only if necessary
https://github.com/eclipse-tractusx/portal-backend/issues/731

chore: upgrade packages

---

src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_assigned_collections.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_descriptions.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_roles.json
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRoleCollectionRolesViewTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs

add:
- Business Partner Data Manager
- BPDM Pool Sharing Consumer
and remove `- description tbd` from other BPDM roles description
https://github.com/eclipse-tractusx/portal-iam/issues/102
follow up to https://github.com/eclipse-tractusx/portal-backend/pull/623
relates to https://github.com/eclipse-tractusx/portal-backend/pull/707

chore(roles-seeding): add bpdm roles

---

CHANGELOG.md
README.md
src/Directory.Build.props

finalize version 2.0.0
https://github.com/eclipse-tractusx/sig-release/issues/671

build(2.0.0): bump version and update docs

---

CONTRIBUTING.md
DEPENDENCIES
LICENSE_non-code
NOTICE.md

- update licensing and legal docs
#784

chore(TRG-7): update licensing and legal docs

---

.github/dependabot.yml
.github/workflows/administration-service.yml
.github/workflows/codeql.yml
.github/workflows/dependencies.yaml
.github/workflows/iam-seeding.yml
.github/workflows/kics.yml
.github/workflows/maintenance-service.yml
.github/workflows/marketplace-app-service.yml
.github/workflows/notification-service.yml
.github/workflows/portal-migrations.yml
.github/workflows/pre-checks.yml
.github/workflows/processes-worker.yml
.github/workflows/provisioning-migrations.yml
.github/workflows/registration-service.yml
.github/workflows/release.yml
.github/workflows/services-service.yml
.github/workflows/sonarcloud.yml
.github/workflows/trivy-main.yml

get rid of dev branch: adjust workflows
https://github.com/eclipse-tractusx/portal/issues/243

chore(dev-flow): maintain latest changes in main branch

---

.github/workflows/iam-seeding.yml
.github/workflows/maintenance-service.yml
.github/workflows/marketplace-app-service.yml
.github/workflows/notification-service.yml
.github/workflows/portal-migrations.yml
.github/workflows/processes-worker.yml
.github/workflows/provisioning-migrations.yml
.github/workflows/registration-service.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/release_iam-seeding.yml
.github/workflows/release_release_candidate.yml
.github/workflows/services-service.yml
docker/Dockerfile-administration-service
docker/Dockerfile-iam-seeding
docker/Dockerfile-maintenance-service
docker/Dockerfile-marketplace-app-service
docker/Dockerfile-notification-service
docker/Dockerfile-portal-migrations
docker/Dockerfile-processes-worker
docker/Dockerfile-provisioning-migrations
docker/Dockerfile-registration-service
docker/Dockerfile-services-service

- change from emulation to cross-compile for building multi-platform images
- also, improve dockerfiles by removing unnecessary base stage and aligning environment variables
https://github.com/eclipse-tractusx/portal-backend/issues/802
https://docs.docker.com/build/building/multi-platform
https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support

fix(image-build): change from emulation to cross-compile

---

src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/registration/Registration.Service/Controllers/RegistrationController.cs
tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs

Remove the mail process creation of the decline registration mail if a user self triggered the decline.
Since the user is declining the registration by himself he shouldn't receive a mail.
Refs: #797

fix(decline): remove mail sending when user declines registration

---

CHANGELOG.md
src/Directory.Build.props
src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/ConnectorsSettings.cs
src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/externalsystems/SdFactory.Library/BusinessLogic/SdFactoryBusinessLogic.cs
src/externalsystems/SdFactory.Library/SdFactoryService.cs
src/externalsystems/SdFactory.Library/SdFactorySettings.cs
src/marketplace/Apps.Service/Controllers/AppChangeController.cs
src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
src/portalbackend/PortalBackend.Migrations/Migrations/20240527114938_2.1.0-rc1.Designer.cs
src/portalbackend/PortalBackend.Migrations/Migrations/20240527114938_2.1.0-rc1.cs
src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/registration/Registration.Service/Controllers/RegistrationController.cs
tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
tests/externalsystems/SdFactory.Library.Tests/SdFactoryBusinessLogicTests.cs
tests/externalsystems/SdFactory.Library.Tests/SdFactoryServiceTests.cs
tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs

https://github.com/eclipse-tractusx/portal/issues/350

build(2.1.0-rc1): merge main into main

---

src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
src/marketplace/Offers.Library/Extensions/CompanySubscriptionStatusExtensions.cs
src/marketplace/Offers.Library/Extensions/ProcessStepExtensions.cs
src/marketplace/Offers.Library/Service/OfferService.cs
src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
tests/marketplace/Offer.Library.Web.Tests/OfferDocumentServiceTests.cs
tests/marketplace/Offers.Library.Tests/Service/ExtensionsTest.cs
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs

namespace Offers.Library.Extensions has been changed to Org.Eclipse.TractusX.Portal.Backend.Offers.Library.Extensions
propper errorhandling has been added to ProcessStepExtensions and unit-tests were added.
Improve maintainability and adherence to standards.
#694 

chore(code-quality): fix various findings

---

src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_role_descriptions.json
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs

Fixed the typo 'particiapte' and 'contributer' to 'participate' and 'contributor'
Spelling mistake
NA

fix(registration): Fix the typo

---

CHANGELOG.md

Add changelog entries for v2.1.0
To document the changes of the last version
N/A

docs(2.1.0): update changelog

---

CHANGELOG.md
src/Directory.Build.props

https://github.com/eclipse-tractusx/portal/issues/379

build(2.1.0): merge release into main

---

src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
tests/administration/Administration.Service.Tests/BusinessLogic/NetworkBusinessLogicTests.cs

When onboarding a company through the osp process the company users are added to the invitation table to support the application activation process.
Users of companies that were onboarded via the osp process still have the Role `CX1-Cl-Registration -> Company Admin` instead of `CX2-Cl-Portal -> Company Admin` and don'T have the business_partner_attribute in the idp.
Refs: #892

fix(osp): add companyUsers to invitation for osp process

---

scripts/sql/GetApplicationChecklistForBpn.sql
scripts/sql/GetRegistrationProcessStepsByBpn.sql

Added scripts to query the application checklist data
To have the statements available for everybody
N/A

docs: add sql scripts to query application checklist data

---

src/Directory.Build.props

bump version for v2.2.0-RC2 
To have a new version for the release
N/A

build(v2.2.0-RC2): bump version for v2.2.0-RC2

---

CHANGELOG.md

Update the changelog with the latest changes since v2.1.0-RC1
To have the latest changes available in the changelog
N/A

chore(v2.2.0-RC2): update changelog for v2.2.0-RC2

---

src/portalbackend/PortalBackend.Migrations/Seeder/BatchUpdateSeeder.cs
src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_descriptions.json

There were some typos in German translation which have been changed.
To fix the typos of German translations
[Ref: #930](https://github.com/eclipse-tractusx/portal-backend/issues/930)

chore(TechnicalIntegrationCheckpoints): Correction of German translation

---

CHANGELOG.md
src/Directory.Build.props

* update the changelog
* bump version
To have the latest version available
N/A

build: bump version for v2.2.0-RC3

---

CHANGELOG.md
src/Directory.Build.props

* bump version for v2.2.0-RC4
* adjust changelog for v2.2.0-RC4
To be able to create the new version
N/A

build: bump version for v2.2.0-RC4

---

CHANGELOG.md
src/Directory.Build.props
src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs

Merge the latest release into the main branch
To have the latest release available in main
N/A

build(v2.2.0): merge release into main 

---

src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs

Send mails to provider when a customer subscribed an offer (app or service)
To provide information to the provider that a new subscription request is available
Refs: #878

fix(mails): send mails for subscription

---

CHANGELOG.md
src/Directory.Build.props

https://github.com/eclipse-tractusx/portal/issues/433

build(2.3.0-alpha.1): merge release into main

---

src/portalbackend/PortalBackend.Migrations/Seeder/Data/application_checklists.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_applications.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/process_steps.json
src/portalbackend/PortalBackend.Migrations/Seeder/Data/processes.json

Add seeding for the initial operator wallet
To have a wallet configured for the operator
Refs: #1003
https://github.com/SAP/ssi-dim-middle-layer/pull/100

feat: adjust seeding for initial wallet

---

docs/api/administration-service.yaml
src/externalsystems/Bpdm.Library/DependencyInjection/BpnAccessCollectionExtension.cs
src/externalsystems/Bpdm.Library/Models/BpdmAccessSettings.cs
src/processes/OfferSubscription.Executor/DependencyInjection/OfferSubscriptionsProcessSettings.cs

* adjust bpnAccess settings
* remove dimUserRoles from OfferSubscriptionsProcessSettings
to fix the startup problem of the administration / registration service and process worker
Refs: #1056

fix(startup errors): adjust settings

---

CHANGELOG.md
src/Directory.Build.props

* adjust changelog for the release
* adjust version for the release
To set things up for the release v2.3.0-alpha.2
https://github.com/eclipse-tractusx/portal/issues/444

build(v2.3.0-alpha.2): adjust version for the release

---

src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs

Fixing the codeQl build
The codeql build currently runs into error e.g. see: https://github.com/eclipse-tractusx/portal-backend/actions/runs/11289433649/job/31399288145
N/A

fix(codeql): fix codeql finding

---

.tractusx
CHANGELOG.md
docs/api/administration-service.yaml
docs/api/apps-service.yaml
docs/api/notifications-service.yaml
docs/api/registration-service.yaml
docs/api/services-service.yaml
src/Directory.Build.props

https://github.com/eclipse-tractusx/portal/issues/463

build(2.3.0-alpha.3): bump version and update docs

---

.tractusx
CHANGELOG.md
docs/api/administration-service.yaml
docs/api/apps-service.yaml
docs/api/notifications-service.yaml
docs/api/registration-service.yaml
docs/api/services-service.yaml
src/Directory.Build.props

* bump version
* update changelog
to have the newest version available
N/A

build: prepare branch for release

---

.tractusx
CHANGELOG.md
docs/api/administration-service.yaml
docs/api/apps-service.yaml
docs/api/notifications-service.yaml
docs/api/registration-service.yaml
docs/api/services-service.yaml
src/Directory.Build.props

Merge the latest release into main
to have the latest changes available in main
N/A

build: merge release into main (#1116)

---

src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
src/administration/Administration.Service/Program.cs

add registration for IIdentityProviderBusinessLogic
The current application is not starting
#1144

fix: add registration for IIdentityProviderBusinessLogic

---

src/framework/Framework.Async/Directory.Build.props
src/framework/Framework.Cors/Directory.Build.props
src/framework/Framework.DBAccess/Directory.Build.props
src/framework/Framework.DateTimeProvider/Directory.Build.props
src/framework/Framework.DependencyInjection/Directory.Build.props
src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
src/framework/Framework.ErrorHandling.Controller/Framework.ErrorHandling.Controller.csproj
src/framework/Framework.ErrorHandling.Web/Directory.Build.props
src/framework/Framework.ErrorHandling/Directory.Build.props
src/framework/Framework.HttpClientExtensions/Directory.Build.props
src/framework/Framework.IO/Directory.Build.props
src/framework/Framework.Linq/Directory.Build.props
src/framework/Framework.Logging/Directory.Build.props
src/framework/Framework.Models/Directory.Build.props
src/framework/Framework.Seeding/Directory.Build.props
src/framework/Framework.Swagger/Directory.Build.props
src/framework/Framework.Token/Directory.Build.props
src/framework/Framework.Web/Directory.Build.props
src/framework/Framework.Web/Framework.Web.csproj
src/web/Web.PublicInfos/Web.PublicInfos.csproj
tests/framework/Framework.Tests.Shared/Framework.Tests.Shared.csproj
tests/shared/Tests.Shared/Tests.Shared.csproj

* upgrade System.Text.Encodings.Web
* upgrade System.Net.Http
in both packages was a security vulnerability
N/A

build: upgrade nuget packages

---

.tractusx
CHANGELOG.md
docs/api/administration-service.yaml
docs/api/apps-service.yaml
docs/api/notifications-service.yaml
docs/api/registration-service.yaml
docs/api/services-service.yaml
src/Directory.Build.props

https://github.com/eclipse-tractusx/portal/issues/482

build(2.3.0): bump version and update docs

---

src/portalbackend/PortalBackend.Migrations/Migrations/20241213081306_2.4.0-alpha.1.Designer.cs
src/portalbackend/PortalBackend.Migrations/Migrations/20241213081306_2.4.0-alpha.1.cs

Merge all migrations since the last release
To have on migrations for the release
Refs: #1205

feat(migrations): merge migrations

---

CHANGELOG.md

update the changelog with the latest changes
To have all changes since the last release in the changelog
Refs: https://github.com/eclipse-tractusx/portal/issues/489

docs(v2.4.0-alpha.1): update changelog for v2.4.0-alpha.1

---

.tractusx
docs/api/administration-service.yaml
docs/api/apps-service.yaml
docs/api/notifications-service.yaml
docs/api/registration-service.yaml
docs/api/services-service.yaml
src/Directory.Build.props

merge the latest changes into main
to have all the latest changes in the main branch
Refs: https://github.com/eclipse-tractusx/portal/issues/489

chore(v2.4.0-alpha.1): merge release into main

---

CHANGELOG.md

update the changelog with the latest changes
To have all changes since the last release in the changelog
Refs: https://github.com/eclipse-tractusx/portal/issues/492

docs(v2.4.0-alpha.2): update changelog for v2.4.0-alpha.2

---

src/portalbackend/PortalBackend.DBAccess/PortalRepositoriesStartupServiceExtensions.cs

add registration for irepository
the process worker isn't starting
N/A

fix(processWorker): add registration for IRepository

---

.tractusx
CHANGELOG.md
docs/api/administration-service.yaml
docs/api/apps-service.yaml
docs/api/notifications-service.yaml
docs/api/registration-service.yaml
docs/api/services-service.yaml
src/Directory.Build.props

Merge the latest changes in the main branch
https://github.com/eclipse-tractusx/portal/issues/524

build(2.4.0): bump version and update docs

---

CHANGELOG.md

Update CHANGELOG.md for 2.5.0-RC1
Release 2.5.0-RC1
Refs: eclipse-tractusx/portal#541

chore(2.5.0-RC1): update changelog

---

.tractusx
docs/api/administration-service.yaml
docs/api/apps-service.yaml
docs/api/notifications-service.yaml
docs/api/registration-service.yaml
docs/api/services-service.yaml
src/Directory.Build.props

* bump version
* update docs
To prepare the branch for the release v2.5.0-rc.1
[#541](https://github.com/eclipse-tractusx/portal/issues/541)

build(2.5.0-RC1): bump version and update docs

---

src/externalsystems/OfferProvider.Library/OfferProviderService.cs
src/externalsystems/OnboardingServiceProvider.Library/OnboardingServiceProviderService.cs

Added grant type in token generation in auto setup.
Token generation was failing as most of the IDP requires grant type
#1375 

fix(auto-setup): fixed grant type
