eclipse-tractusx/portal-backend

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
- src/marketplace/Services.Service/Controllers/ServicesController.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
the following endpoints have been moved from /api/apps/ to:
- GET: /api/apps/appreleaseprocess/{appId}/technical-user-profiles
- PUT: /api/apps/appreleaseprocess/{appId}/technical-user-profiles the following endpoints have been moved from /api/services/ to:
- GET: /api/services/servicerelease/{serviceId}/technical-user-profiles
- PUT: /api/services/servicerelease/{serviceId}/technical-user-profiles fix: swagger documentation edited for put endpoints
endpoints were located in incorrect controller not belonging to the the app creation process
Jira-ticket CPLP-2719 (no Github issue yet).
> feat!: move offer technical user profile endpoints

- src/marketplace/Offers.Library/Models/OfferSubscriptionDetailData.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
the following endpoints now return the offerSubscriptionStatus instead of the offer status
/apps/{appId}/subscription/{subscriptionId}/subscriber 
/apps/{appId}/subscription/{subscriptionId}/provider
The frontend needs to be able to access the offer subscription state id
N/A - Jira Ticket: CPLP-2626
> feat(subscription): change offer status to offer subscription status

- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
Add validation for ServiceTypeId and Title to make it mandatory field during service creation
Added validation so that service cannot be created without those mandatory field
https://jira.catena-x.net/browse/CPLP-2733
> feat(servicerelease):Post AddService

- src/marketplace/Offers.Library/Service/OfferService.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
Ref: CPLP-2799
Fix(offerService) : setting documentStatus to Pending Status
when the declineService or declineApp endpoint triggered the documentStatus set to INACTIVE, instead to PENDING.
[CPLP-2799](https://jira.catena-x.net/browse/CPLP-2799)
> Fix(offerService) : setting documentStatus to Pending Status

- src/externalsystems/OfferProvider.Library/OfferProvider.Library.csproj
Nuget Packages with a reference to asp.net has been removed from dependent projects of the process worker
to use a leaner base image the process worker must not have any references to asp.net
N/A - Jira Ticket:  CPLP-2344
> chore: remove asp.net dependencies from process worker

- src/framework/Framework.Web/StartupServiceExtensions.cs
registration added for newly introduced auth handlers
the newly created enumTypeClaimHandler and GuidClaimHandler were not registered correctly, thus a user will always get a 403.
N/A - Jira Issue: CPLP-2553
> fix(identity): add policy handler registration

- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
Swagger clean up of technical user profile endpoint for app and services.
swagger documentation was missing the response body.
https://jira.catena-x.net/browse/CPLP-2809.
> fix(app & services):- get technical user profile

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ServiceAccountController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IServiceAccountRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
Map ServiceAccount Deletion to Connector and throw exception message if connectorstatus is pending or  active
To ensure that service account deletion will happen only when connector is in inactive state
https://jira.catena-x.net/browse/CPLP-2778
-- [ ] I have performed a self-review of my own code
> feat(serviceaccount):- Delete  serviceaccount

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ConnectorsController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
Delete connector for scenarios like when daps,DS and statusid flag are false, true and active pending etc
For connector registrations where the daps registration was unsuccessful, the deletion is currently blocked.
https://jira.catena-x.net/browse/CPLP-2780
> feat(connectors):- Delete Connector

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_assigned_collections.json
Added seeding data for the linking of company role participants and some needed user roles
The base seeding should include the roles for the participants
N/A - Jira Ticket: CPLP-2874
> chore: add seeding data for Partipants

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- tests/registration/Registration.Service.Tests/Controller/RegistrationControllerTest.cs
Passing the userId instead of the companyId to check the application association
The current implementation will always fail because the check for the application association is executed with the companyId, but the check will validates the user
N/A - Jira Ticket: CPLP-2873
> fix(invitation): fix application association check

- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
- src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/registration/Registration.Service.Tests/Controller/RegistrationControllerTest.cs
The query that is used to check for an existing user email-address in the calling users company has been refactored to make use of the calling users identity companyId instead of identityId.
The preexisting-query did a complex join as it was required when using the iamUserId. The refactored query is now both more efficient and more easy to understand.
https://jira.catena-x.net/browse/CPLP-2873
> chore(Invitation): refactor user-validation-query

- src/registration/Registration.Service/appsettings.json
Adding the new setting SubmitDocumentTypeIds as template to registration-service appsettings.json. This was forgotten when merging https://github.com/eclipse-tractusx/portal-backend/pull/56
Missing setting causes error on service-startup
No GH Issue
CPLP-2736
> fix(registration): add missing template setting SubmitDocumentTypeIds

- src/mailing/Mailing.Template/EmailTemplates/password.html
change from span to p tag to remove extra space issue
password filed having extra space in some email client
NA
> bugfix(password template): space issue fix

- src/marketplace/Offers.Library.Web/OfferDocumentService.cs
- src/marketplace/Offers.Library/Models/UploadDocumentConfig.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Offer.Library.Web.Tests/OfferDocumentServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
* use enum-values in uploadDocumentTypeIds setting
change of uploadDocumentTypeIds settings values type from string to MediaTypeIds enum
using string-values in config is not typesafe and can be more easily be validated on startup.
N/A (CPLP-2891)
https://github.com/eclipse-tractusx/portal-cd/pull/30
> fix(config): marketplace uploadDocumentTypeIds

- docker/Dockerfile-portal-migrations
fix dockerfile of portal.migrations not including dependency on framework.logging
implementation of CPLP-1849 structured logging was lacking adaption of portal.migrations dockerfile. That causes the build of the respective image to fail.
N/A (CPLP-1849)
- [X ] I have checked that new and existing tests pass locally with my changes
> bugfix(migrations): fix dockerfile for portal-migrations

- CHANGELOG.md
- src/Directory.Build.props
- src/marketplace/Apps.Service/appsettings.json
- src/marketplace/Services.Service/appsettings.json
Refs: CPLP-2903
fixed mail sending when acivating the subscription within the manual auto setup process
when sending the mail within the manual auto setup endpoints, the template couldn't be found.
N/A - Jira Issue: CPLP-2903
> fix(autoSetup): manual autoSetup process fixed

- src/notifications/Notifications.Service/BusinessLogic/NotificationBusinessLogic.cs
- src/notifications/Notifications.Service/Controllers/NotificationController.cs
- src/notifications/Notifications.Service/Models/NotificationFilters.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/INotificationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
- tests/notifications/Notifications.Service.Tests/BusinessLogic/NotificationBusinessLogicTests.cs
- tests/notifications/Notifications.Service.Tests/Controllers/NotificationControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/notifications.test.json
Added done state filter for notification detail endpoint
To filter the record based on done state value like null, true and false
CPLP-2837
> Fix(notification): get notification details

- .github/workflows/dependencies.yaml
- DEPENDENCIES
- scripts/check-dependencies.md
- add workflow to check 3rd party dependencies with the [Eclipse Dash License Tool](https://github.com/eclipse/dash-licenses)
run with  dependencies file not changed: https://github.com/eclipse-tractusx/portal-backend/actions/runs/5375054212/jobs/9751059140
example run with dependencies file changed (repurposed unit testing und formatting workflow for testing): https://github.com/eclipse-tractusx/portal-backend/actions/runs/5374531262/jobs/9749999098
- change dependencies file to '-summary' format from Dash Tool
**Due to the new format in the dependencies file: once this PR is merged into dev, all open feature branches should be rebased to dev, as the dependencies check will fail otherwise.**
Dependencies check should be automated.
n/a
> chore: add workflow to check dependencies

- docker/Dockerfile-portal-migrations
add copy of module Framework.Models and Framework.Linq to dockerfile of Module Portal.Migrations
PR #84 for CPLP-2853 does add a new dependency to module Framework.Models and Framework.Linq to module Portal.Migrations. Copying those dependencies was not added to the respective dockerfile. The image of portal.migrations therefore fails to build and thus the required migration is not applied to the database.
N/A (CPLP-2853)
> fix (Migrations) add dependeny Framework.Models to dockerfile

- src/administration/Administration.Service/BusinessLogic/ConnectorsSettings.cs
- src/administration/Administration.Service/BusinessLogic/DocumentSettings.cs
- src/administration/Administration.Service/BusinessLogic/InvitationSettings.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationSettings.cs
- src/administration/Administration.Service/BusinessLogic/UserSettings.cs
- src/externalsystems/OfferProvider.Library/DependencyInjection/OfferProviderServiceCollectionExtension.cs
- src/framework/Framework.Models/Validation/BaseOptionEnumerableValidation.cs
- src/framework/Framework.Models/Validation/DistinctValuesValidation.cs
- src/framework/Framework.Models/Validation/EnumEnumerableValidation.cs
- src/framework/Framework.Models/Validation/SettingValidation.cs
- src/framework/Framework.Web/WebApplicationBuildRunner.cs
- src/mailing/Mailing.Template/TemplateSettings.cs
- src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
- src/marketplace/Services.Service/ServiceSettings.cs
- src/processes/OfferSubscription.Executor/DependencyInjection/OfferSubscriptionProcessCollectionExtensions.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationSettings.cs
- tests/framework/Framework.Models.Tests/ValidationTests.cs
validation for custom attributes EnumEnumerable and DistinctValues extended to validate Properties of properties as well added base implementation for custom enumerable validators
The current validatio implmentation only validates properties within the given class, but doesn't validate properties of properties.
N/A - Jira Issue: CPLP-2698
> fix(config): extend validation to all properties

- docker/Dockerfile-maintenance-service
ADding missing dependencies to build the docker image of the maintenance service
Currently the docker image action is failing for the maintenance service
N/A - Jira Issue: CPLP-2930
> fix: add missing dependencies for maintenance service

- src/provisioning/Provisioning.Migrations/Migrations/20230613120413_230629.Designer.cs
- src/provisioning/Provisioning.Migrations/Migrations/20230613120413_230629.cs
- add sql to latest provisioning migration to delete contents of table user_password_resets before migrating to new identitymodel
- rename latest migration removing reference to JIRA-ticket replacing by current date.
remark: on DEV environment the entries of table __efmigrations_history_provisioning must be manually migrated by applying this sql command:
```
update __efmigrations_history_provisioning
set migration_id = '20230613120413_230629'
where migration_id = '20230613120413_CPLP-2553-AlignUsers';
```
- table provisioning.user_password_resets is being changed by latest migration in such a way that existing data is in conflict with new pk-constraint. The migration therefore fails to run in case the table does contain entries. As the entries are of low value (the table exists to track …
> bugfix(provisioning): fix migration

- src/framework/Framework.Seeding/CustomSeederRunner.cs
- src/framework/Framework.Seeding/SeederHelper.cs
- src/framework/Framework.Seeding/SeederSettings.cs
- src/marketplace/Apps.Service/ViewModels/AppDetailResponse.cs
- src/marketplace/Apps.Service/ViewModels/InReviewAppDetails.cs
- src/marketplace/Services.Service/ViewModels/ServiceData.cs
- src/marketplace/Services.Service/ViewModels/ServiceDetailResponse.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
- src/portalbackend/PortalBackend.Migrations/Seeder/BatchInsertSeeder.cs
- src/portalbackend/PortalBackend.Migrations/Seeder/BatchUpdateSeeder.cs
- src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditCompanySsiDetail.cs
- src/portalbackend/PortalBackend.PortalEntities/Entities/VerifiedCredentialExternalType.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Setup/TestDbFixture.cs
- tests/portalbackend/PortalBackend.Migrations.Tests/ConsortiaDataDbFixture.cs
The path of the seeding data is now configurable
To be able to seed ones own data and don't have the need to edit the json files within the Seeder/Data directory one can now mount a directory which than can be configured to be used for the seeding as well.
N/A - Jira Issue:  CPLP-2788
[#37](https://github.com/eclipse-tractusx/portal-cd/pull/37)
> feat(seeding): add configurable path for seeding data

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/Models/CompanyWithAddressData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/RegistrationData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/Model/CompanyDetailData.cs
- src/registration/Registration.Service/Model/CompanyRegistrationData.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Ref: CPLP-2795
removing CountryDe fields in Registration Service and Administration Service
removing the CountryDe fields for particular endpoints in registration service and administration service
Note : It is a dependent task with Frontend , so don't merge to dev until its completed
[CPLP-2795](https://jira.catena-x.net/browse/CPLP-2795)
> feat: removing CountryDe field

- src/marketplace/Offers.Library/Service/OfferService.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
Adding Validation and Removing technical user profiles
Added Validation before creation of Technical User Profiles.
Removing existing Technical User Profiles without User Role Ids.
[CPLP-2738](https://jira.catena-x.net/browse/CPLP-2738)
> feat(OfferService)!: adding validation and removing technical user profile

- docker/Dockerfile-provisioning-migrations
- src/framework/Framework.Seeding/DependencyInjection/DatabaseInitializerExtensions.cs
- src/framework/Framework.Seeding/Framework.Seeding.csproj
- src/framework/Framework.Seeding/SeederSettings.cs
- src/portalbackend/PortalBackend.Migrations/appsettings.json
adding validation on application startup for the seeder settings
Currently we're receiving an NullReferenceExecption when for example forgetting the DataPaths configuration for the seeder settings, to check if the settings are configured correctly the validation happens on startup to receive a more descriptive error message.
N/A
> chore: adding validation for seeder settings

- src/notifications/Notifications.Service/BusinessLogic/NotificationBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/INotificationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
- tests/notifications/Notifications.Service.Tests/BusinessLogic/NotificationBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
isRead flag was not updating if we update the value to false/true
isRead value first time updated to true but when updating to false it was not updating. It was due to comparison of bool value in entity framework which was set default value.
CPLP-2916.
> fix(notification): fix put notification by Id endpoint

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
Enhanced the logic to unassign the CompanyRoles and Consent
Added an logic to unassign the CompanyRole and set inactive to respective agreements in Consent 
[CPLP-2813](https://jira.catena-x.net/browse/CPLP-2813)
> feat(CompanyDataBusinessLogic)! : enhanced logic to unassign the CompanyRole and Consent

- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/administration/Administration.Service/Models/UseCaseParticipationCreationData.cs
Adjusted the roles for the ssi endpoints
Rename response properties for the get endpoints of ssi
The role setup changed
N/A - Jira Issue: CPLP-2853
> chore: adjust roles for ssi endpoints

- src/portalbackend/PortalBackend.DBAccess/Repositories/INotificationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/notification_type_assigned_topic.json
- tests/notifications/Notifications.Service.Tests/BusinessLogic/NotificationBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
fixed 500 error for notification count.
If there is no matching notification topic id in table notification_type_assigned_topics for notificationtypeid so null was returning through query due to which nullable exception was throwing 500 error.
CPLP--2939
> bug(notification): fix get notification count endpoint

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IConnectorsBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ConnectorsController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionConnectorData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.PortalEntities/Entities/ConnectorAssignedOfferSubscription.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/ConnectorsControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/addresses.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/companies.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/connector_assigned_offer_subscriptions.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/connectors.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offer_subscriptions.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offers.test.json
add /api/administration/connectors/offerSubscriptions to get all offerSubscriptions for the connector view
To provide a selection of the current offer subscriptions for the user to be able to create a managed connector the endpoint is needed.
N/A - CPLP-2947
This PR depends on #129 please review this PR after 129 was reviewed and merged.
> feat(offerSubscription): add get endpoint to get offerSubscriptions

- src/externalsystems/SdFactory.Library/Models/SdFactoryRequestModel.cs
- src/externalsystems/SdFactory.Library/SdFactoryService.cs
Change the Type field of the SD-Factory call from legal person to legal participant
The expected request object has changed.
N/A - Jira Ticket: CPLP-2962
> chore: change LegalPerson to LegalParticipant for SD call

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
an inactive subscription now won't be activated, instead a new subscription will be created
the following endpoints have been changed from appId to subscriptionId:
/api/apps/supscription/{subscriptiondId}/activate
/api/apps/{subscriptionId}/unsubscribe
Since the subscription is linked to a technical user and an app instance we don't want to reactivate an inactive subscription. Instead we want to create a new one.
N/A - Jira Issue: CPLP-2911
> feat(app)!: change app subscription process

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/externalsystems/Clearinghouse.Library/BusinessLogic/ClearinghouseBusinessLogic.cs
- src/externalsystems/SdFactory.Library/BusinessLogic/SdFactoryBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Models/VerifyChecklistData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationChecklistRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationChecklistRepository.cs
- src/processes/ApplicationChecklist.Executor/ApplicationChecklistProcessTypeExecutor.cs
- src/processes/ApplicationChecklist.Library/ApplicationChecklistService.cs
- src/processes/ApplicationChecklist.Library/IApplicationChecklistService.cs
- src/processes/ApplicationChecklist.Library/VerifyApplicationChecklistDataExtensions.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/externalsystems/Clearinghouse.Library.Tests/ClearinghouseBusinessLogicTests.cs
- tests/externalsystems/SdFactory.Library.Tests/SdFactoryBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationChecklistRepositoryTests.cs
- tests/processes/ApplicationChecklist.Executor.Tests/ApplicationChecklistProcessTypeExecutorTests.cs
- tests/processes/ApplicationChecklist.Library.Tests/ApplicationChecklistServiceTests.cs
Update comment ,when retrigger the application Checklist type
when ever the process step failed for the particular application checklist type and the failed message is updated in comment field.
So, when we manually retrigger the failed application checklist type. comment need to set to null 
[CPLP-2823](https://jira.catena-x.net/browse/CPLP-2823)
> feat(applicationChecklist)! : retriggerProcessSteps update comments for applicationChecklist type

- src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
Add AppInstanceId to the /{appId}/subscription/{subscriptionId}/provider endpoint
AppInstanceId is needed by the frontend
N/A - Jira Issue: CPLP-2983
> feat(app): extend app provider endpoint with appInstanceId

- src/externalsystems/Custodian.Library/CustodianService.cs
- src/externalsystems/Custodian.Library/Models/WalletErrorResponse.cs
- tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
updated the createWallet responce message
Store only DID id and CreatedAt fields when CreateWallet responce message is success
[CPLP-2840](https://jira.catena-x.net/browse/CPLP-2840)
> feat(applicationChecklist)! : updated the createWallet responce message

- src/administration/Administration.Service/Controllers/CompanyDataController.cs
swagger documentation for companyData endpoints
swagger documentation for  missing companyData endpoints
[CPLP-2946](https://jira.catena-x.net/browse/CPLP-2946)
> fix(administration) : add swagger documentation for companyData endpoints

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
resolved apps-business endpoint empty results
For apps/business endpoint , we passed CompanyId as parameter to fetch the result. because of that result is empty.
Now by changing the passing parameter to UserId, we able to fetch appropriate result.
[CPLP-3048](https://jira.catena-x.net/browse/CPLP-3048)
> fix: resolved apps-business endpoint empty results

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferAgreementConsent.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/AgreementRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
aoi/apps/appreleaseproces/consent/appid/agrremntconsent and aoi/apps/appreleaseproces/consent/appid/agrremntconsent 
was throwing 500 internal service error due to foreign key constraint .
The exception was thrown due to qury condtion of providercompany.idenriries .companyuserid singleordefault which never ensure the comparison.if companyuserid is null then it will give foreign key issue.
CPLP-3018
> fix(apps and services):- post offerId/agreementconsent

- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanySsiDetailsRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_ssi_details.test.json
ignore inactive ssi entries when creating a new entry
Currently it is not possible to create a second ssi certificate even if the first one is inactive
N/A - Jira Issue: CPLP-3022
> fix(ssi): ignore existing inactive ssi entries

- src/administration/Administration.Service/BusinessLogic/IServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ServiceAccountController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IServiceAccountRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
Added clientId and isOwner to filter the record from serviceaccount
Added filter so that we can search based on specified clientclientId and if service account is of owner or provider 
CPLP-3011.
> feat(serviceaccount): get owncompany-serviceaccount

- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/identities.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
added validation for companyserviceaccount while deleting account whether  serviceaccount is of provider or owner
If companyuser account is not of provider or owner then don't allow to execute the endpoint and throw messages
N/A - Jira Issue: CPLP-3034
> feat(serviceaccount): enhance delete serviceaccount

- src/administration/Administration.Service/appsettings.json
- src/maintenance/Maintenance.App/appsettings.json
- src/marketplace/Apps.Service/appsettings.json
- src/marketplace/Services.Service/appsettings.json
- src/notifications/Notifications.Service/appsettings.json
- src/portalbackend/PortalBackend.Migrations/appsettings.json
- src/processes/Processes.Worker/appsettings.json
- src/provisioning/Provisioning.Migrations/appsettings.json
- src/registration/Registration.Service/appsettings.json
adjusting log level configuration for the portal services
Currently the overrides are not correctly taken, because of the default log level
N/A - Jira Issue: CPLP-2998
[#58](https://github.com/eclipse-tractusx/portal-cd/pull/58)
> fix(logging): adjust logger config

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/marketplace/Offers.Library/Service/IOfferSetupService.cs
- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- src/portalbackend/PortalBackend.DBAccess/Models/TriggerProviderInformation.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- src/processes/OfferSubscription.Executor/OfferSubscriptionProcessTypeExecutor.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
- tests/processes/OfferSubscription.Executor.Tests/OfferSubscriptionProcessTypeExecutorTests.cs
ckanged app activation process for single instance apps.
add enpoint PUT: /api/apps/subscription/activate-single-instance to manually activate single instance apps.
currently the activation off the app subscription happens automatically, now the provider needs to trigger it manually.
N/A - Jira Issue: CPLP-3046
> fix(app): add single app subscription activation

- src/externalsystems/Custodian.Library/Custodian.Library.csproj
- src/externalsystems/Custodian.Library/CustodianService.cs
- src/externalsystems/Custodian.Library/Models/WalletErrorResponse.cs
- tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
Fixed the logging for the custodian response
Currently the did value is not saved in the comments
N/A - Jira Issue: CPLP-3110
> fix(custodian): log custodian response

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanySsiDetailsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanySsiDetailsRepositoryTests.cs
enhance businessLogic of the GET /administration/companydata/certificateTypes to return only the possible certificateTypes
To show the user only the possible certificates he can request
N/A - Jira Issue: CPLP-3002
> feat(ssi): adjust certificateTypes endpoint

- src/mailing/Mailing.Template/EmailTemplates/portal_welcome_email.html
show bpnl number next to user name in the email template
bpnl is missing
NA
> updates(welcome email): show bpnl number next to user name

- src/portalbackend/PortalBackend.PortalEntities/Enums/VerifiedCredentialExternalTypeId.cs
Adjust the VerifiedCredentialExternalTypeId for Sustainability Credential
currently the wrong value is send to the external service
N/A
> fix(ssi): adjust external type value

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
Adjust naming for the technical user which is used to run the process worker to system-internal
To not get confused with same naming schema for the technical user
N/A
> chore(sa): adjust naming of service account for process worker

- src/keycloak/Keycloak.Authentication/ControllerExtensions.cs
Changed the bearer check to get the access token for the user to case insensitive check
When requesting the API with an lowercase bearer Authorization header the endpoint throws an error.
N/A - Jira Issue: CPLP-3131
> fix(auth): change bearer check to case insensitive

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/administration/Administration.Service/Models/SsiCertificateData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanySsiDetailsRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_ssi_details.test.json
fix Get: api/administration/companydata/certificates when multiple certificates are in the database for a specific company introduce IIdentityService to CompanyDataController
currently an error is thrown if more than one certificate is in the database for a specific company when executing the Get: api/administration/companydata/certificates endpoint
N/A - Jira Issue: CPLP-3124
> feat(certificates): fix get certificates endpoint

- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
- src/provisioning/Provisioning.Library/Service/ServiceAccountCreation.cs
- src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
- tests/provisioning/Provisioning.Library.Tests/Extensions/ServiceAccountCreationTests.cs
- tests/provisioning/Provisioning.Library.Tests/UserProvisioningServiceCreateUsersTests.cs
The correct identity Type Id is now set for serviceAccounts
Currently the serviceAccounts are created with identityTypeId = 1 (companyUser), with that Pr the correct identityTypeId (2 - serviceAccount) is set.
N/A - Jira Ticket: CPLP-3112
> fix(serviceAccount): set correct identityTypeId for serviceAccounts

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServicesController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/connector_assigned_offer_subscriptions.test.json
unsubscribe OfferSubscription for apps and service
when we trigger unsubscribe endpoint for Apps and Service , we put offerSubscription to Inactive. 
[CPLP-3027](https://jira.catena-x.net/browse/CPLP-3027)
> feat(OfferService)! : unsubscribe OfferSubscription for apps and service

- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/companies.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/identities.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offer_subscriptions.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offers.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
Added provider and owner instead of identity companyid in query
Response was returning serviceaccounts only for logged in user company not for provider and owner.
CPLP-3113.
> fix(serviceaccount): get owncompany serviceaccount

- src/externalsystems/Bpdm.Library/BpdmService.cs
- src/externalsystems/Bpdm.Library/BusinessLogic/BpdmBusinessLogic.cs
- src/externalsystems/Bpdm.Library/IBpdmService.cs
- src/externalsystems/Bpdm.Library/Models/BpdmSharingState.cs
- tests/externalsystems/Bpdm.Library/BPNAccessTest.cs
- tests/externalsystems/Bpdm.Library/BpdmBusinessLogicTests.cs
- tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs
add sharing-state request before pulling the bpn from bpdm service
To be able to display the error message from bpdm we first request the sharing-state endpoint to get the state of the bpn creation, if an error happend we're saving the error inside the process step and application checklist entry.
N/A - Jira Issue: CPLP-3160
> fix(bpdm): add errormessage for bpdm fetch

- src/portalbackend/PortalBackend.Migrations/Seeder/BatchUpdateSeeder.cs
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/identities.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
- change client_id of service accounts in seeding data
sa-cl5-custodian-1 https://github.com/eclipse-tractusx/portal-iam/blob/chores-3.2-release/import/realm-config/generic/catenax-central/CX-Central-realm.json#L4366C14-L4366C50
sa-cl5-custodian-2 https://github.com/eclipse-tractusx/portal-iam/blob/chores-3.2-release/import/realm-config/generic/catenax-central/CX-Central-realm.json#L4486
sa-cl3-cx-1 https://github.com/eclipse-tractusx/portal-iam/blob/chores-3.2-release/import/realm-config/generic/catenax-central/CX-Central-realm.json#L4242C14-L4242C50
sa-cl7-cx-5 https://github.com/eclipse-tractusx/portal-iam/blob/chores-3.2-release/import/realm-config/generic/catenax-central/CX-Central-realm.json#L4606C14-L4606C50
sa-cl2-01 https://github.com/eclipse-tractusx/portal-iam/blob/chores-3.2-re …
> fix(seeding): change client_id of service accounts

- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
adrole assigned to technicaluser profile.
The check was added so that if technical user has role then allow to create the record elase return.
CPLP-2829.
> feat:(apps and services) technical user creation in autosetup

- src/notifications/Notifications.Service/BusinessLogic/NotificationBusinessLogic.cs
- src/notifications/Notifications.Service/Controllers/NotificationController.cs
- src/notifications/Notifications.Service/Models/NotificationFilters.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/INotificationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
- tests/notifications/Notifications.Service.Tests/BusinessLogic/NotificationBusinessLogicTests.cs
- tests/notifications/Notifications.Service.Tests/Controllers/NotificationControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/notifications.test.json
Enable search ability of notification content
To give the possibility to the frontend to search the content of notifications
N/A - Jira Issue: CPLP-3045
> feat(notification): enable notification search

- docker/Dockerfile-iam-seeding
- docker/Dockerfile-portal-migrations
- docker/Dockerfile-provisioning-migrations
change dotnet base image for jobs
was mistakenly set to aspnet even though only runtime is needed
n/a
> fix(container): change dotnet base image for jobs

- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
adding validation for offerUrl to not contain hash
keycloak can't handle urls with hashes
N/A - Jira Issue: CPLP-1189
> fix(autosetup): add validation for hash

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_role_descriptions.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
Spelling mistake correction in seed data.
While rendering it should display correct information.
CPLP-1177
> fix: correction spelling mistake in seeder file

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IServiceAccountRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
Added validation for serviceaccount to not allow to deactivate if it has active subscription.
Dont allow company user to deleye a service account if it has active sunscription show the required error message if try to delete the account with active subscription
CPLP-3136
> feat:(serviceaccount): adjust delete owncompany serviceaccount by id

- src/marketplace/Services.Service/Controllers/ServiceChangeController.cs
- src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
- tests/provisioning/Provisioning.Library.Tests/UserProvisioningServiceAuxiliaryMethodsTests.cs
namecreatedby null check handled and ServiceChange controller url fixed
nameCreatedBy not handled for null value, in email template body the value is null, now it is handled
ServiceChange service url is mismatched, now it is fixed 
[CPLP-2790](https://jira.catena-x.net/browse/CPLP-2790)
[TEST-1142](https://jira.catena-x.net/browse/TEST-1142)
> fix(userprovisioning & Service) : namecreatedby null check handled and ServiceChange controller url fixed

- tests/portalbackend/PortalBackend.DBAccess.Tests/PortalDbContextTests.cs
removed asserts in db-unittests that depend on synchronization of clocks in unit-test and database-container and .
in PR #203 unit-tests were added for the trigger-framework. While those tests run fine most of the time they eventually fail whenever the trigger on the database runs more than 1 second later than the point in time the unit-tests creates a new entiy in the dotnet-runtime.
N/A
> bugfix (unittests): remove asserts depending on db's timing of execution.

- docker/Dockerfile-maintenance-service
- docker/Dockerfile-portal-migrations
the dependency to framework.DateTimeProvider was added to dockerfiles of modules 'Migrations' and 'Maintenance'
PR #203 (CPLP-2897) did add new dependencies to modules 'maintenance' and 'migrations'. The respective dockerfiles were not adjusted accordingly. Therefore the github-action 'build-and-push-image' of 'migrations' and 'maintenance' fails.
N/A
> bugfix (docker): fix docker dependencies

- tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
remove a dependency on 'DateTimeOffset.OffsetNow()' in custodian unit-test by replacing that dynamic testdata by a constant value.
The unit-test CreateWallet_WithValidData_DoesNotThrowException() would eventually fail because Json-formating and assert would not produce the same string in case the dateTimeOffset would have trailing zeros. This breaks the build.
N/A
> bugfix(custodian): fix runtime-dependency of unit-test-assert

- src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
Added InActive Status to the default Filter
When we hit the app/provider/subscription-status or service/provider/subscription-status with offerSubscription status set as default , now it  fetches Inactive data also 
[CPLP-3175](https://jira.catena-x.net/browse/CPLP-3175)
> feat(App&Service) : Added InActive Status to the default Filter

- src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionStatusData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
added subscriptionId field to activeSubscription Endpoint
added subscriptionId field to activeSubscription Endpoint for FE
[CPLP-3233](https://jira.catena-x.net/browse/CPLP-3233)
> feat(app) : added subscriptionId field to activeSubscription Endpoint

- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
no error is thrown when the appInstanceSetup is missing
Currently the autoSetup throws an 500 error when trying to start the autoSetup for an subscription with an offer that doesn't have an appInstanceSetup configured.
N/A - Jira Issue: CPLP-3238
> fix(autoSetup): adjust autoSetup query

- src/administration/Administration.Service/BusinessLogic/IRegistrationStatusBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationStatusBusinessLogic.cs
- src/administration/Administration.Service/Controllers/RegistrationStatusController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OnboardingServiceProviderCallbackData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- src/portalbackend/PortalBackend.Migrations/Seeder/BatchInsertSeeder.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationStatusBusinessLogicTest.cs
- tests/administration/Administration.Service.Tests/Controllers/RegistrationStatusControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/addresses.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/companies.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_assigned_roles.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/onboarding_service_provider_details.test.json
add endpoint to get the callback url of an osp
add endpoint to set the callback url of an osp
To enable the osps to set a callback url. If the callback url is set the osp will be informed when the status of an application changed
N/A - Jira Issue: CPLP-2638
> feat(n2n): add osp callback endpoints

- src/administration/Administration.Service/appsettings.json
- src/keycloak/Keycloak.Factory/IKeycloakFactory.cs
- src/keycloak/Keycloak.Factory/KeycloakFactory.cs
- src/keycloak/Keycloak.Factory/KeycloakSettingData.cs
- src/keycloak/Keycloak.Library/Common/Extensions/FlurlRequestExtensions.cs
- src/keycloak/Keycloak.Library/KeycloakClient.cs
- src/keycloak/Keycloak.Seeding/appsettings.json
- src/marketplace/Apps.Service/appsettings.json
- src/marketplace/Services.Service/appsettings.json
- src/notifications/Notifications.Service/appsettings.json
- src/processes/Processes.Worker/appsettings.json
- src/provisioning/Provisioning.Library/Extensions/IdentityProviderManager.cs
- src/provisioning/Provisioning.Library/Provisioning.Library.csproj
- src/provisioning/Provisioning.Library/ProvisioningManager.cs
- src/provisioning/Provisioning.Library/ProvisioningSettings.cs
- src/registration/Registration.Service/appsettings.json
- tests/provisioning/Provisioning.Library.Tests/Extensions/ClientManagerTests.cs
- tests/provisioning/Provisioning.Library.Tests/Extensions/RoleManagerTests.cs
- tests/provisioning/Provisioning.Library.Tests/FlurlSetup/FlurlSetupExtensions.cs
- tests/provisioning/Provisioning.Library.Tests/ProvisioningManagerTests.cs
- tests/provisioning/Provisioning.Library.Tests/UserManagerTests.cs
Make the auth path of keycloak configureable
With the keycloak upgrade the /auth path in the urls of keycloak was removed, to be able to still use older versions its now configurable
N/A - Jira Issue: CPLP-3214
[#95](https://github.com/eclipse-tractusx/portal-cd/pull/95)
> feat(kc): add configurable auth path for keycloak requests

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/addresses.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/application_checklist.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/companies.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_applications.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_assigned_roles.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_identity_providers.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_role_assigned_role_collections.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_users.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/consents.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/iam_identity_providers.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/identities.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/identity_assigned_roles.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/identity_providers.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/process_steps.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/processes.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_assigned_collections.json
Add seeding for the osp realm and company including users
To be able to test the osp features we want to have a test company including a user and own realm.
N/A - Jira Issue: CPLP-3145
> feat(n2n): add seeding for osp idp

- src/processes/NetworkRegistration.Executor/DependencyInjection/NetworkRegistrationProcessCollectionExtensions.cs
Network process worker has been registered
To be able to run the network processes the worker needs to be registered
N/A
> fix(n2n): register network process worker

- .github/workflows/administration-service.yml
- .github/workflows/iam-seeding.yml
- .github/workflows/maintenance-service.yml
- .github/workflows/marketplace-app-service.yml
- .github/workflows/notification-service.yml
- .github/workflows/portal-migrations.yml
- .github/workflows/processes-worker.yml
- .github/workflows/provisioning-migrations.yml
- .github/workflows/registration-service.yml
- .github/workflows/release.yml
- .github/workflows/release_candidate.yml
- .github/workflows/release_iam-seeding.yml
- .github/workflows/release_release_candidate.yml
- .github/workflows/services-service.yml
- docker/Dockerfile-administration-service
- docker/Dockerfile-iam-seeding
- docker/Dockerfile-maintenance-service
- docker/Dockerfile-marketplace-app-service
- docker/Dockerfile-notification-service
- docker/Dockerfile-portal-migrations
- docker/Dockerfile-processes-worker
- docker/Dockerfile-provisioning-migrations
- docker/Dockerfile-registration-service
- docker/Dockerfile-services-service
- src/administration/Administration.Service/Properties/launchSettings.json
- src/marketplace/Apps.Service/Properties/launchSettings.json
- src/marketplace/Services.Service/Properties/launchSettings.json
- src/notifications/Notifications.Service/Properties/launchSettings.json
- src/registration/Registration.Service/Properties/launchSettings.json
- build images also for arm64, in addition to amd64
- improve dockerfiles - 'dotnet build' not needed as implicit of 'dotnet publish'
- change launchsettings
- cors for localdev env
- align applicationUrl for apps service
enable localdev umbrella chart: arm64 images needed for usage on Mac
[localdev](https://github.com/eclipse-tractusx/portal-cd/pull/90)
> chore(localdev):  enhance image image build and launchsettings

- docker/Dockerfile-administration-service
- docker/Dockerfile-iam-seeding
- docker/Dockerfile-maintenance-service
- docker/Dockerfile-marketplace-app-service
- docker/Dockerfile-notification-service
- docker/Dockerfile-portal-migrations
- docker/Dockerfile-processes-worker
- docker/Dockerfile-provisioning-migrations
- docker/Dockerfile-registration-service
- docker/Dockerfile-services-service
fix image build enabling for arm64
docker build and push fails after https://github.com/eclipse-tractusx/portal-backend/pull/277
n/a
> fix(arch): build arm64 images

- tests/endtoend/EndToEnd.Tests.csproj
exclude e2e tests from sonar coverage
coverage from ci sonar scan decreased significantly with e2e test project.
apparently tests project are also part of the coverage analysis.
n/a
> chore(e2e): exclude e2e tests from sonar coverage

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/identities.json
change to correct user_entity_id's of the CX-Central realm (centralidp) for the following service accounts:
- sa-cl2-01
- sa-cl2-02
- sa-cl8-cx-1
service account policy is failing.
was missed during previous check: https://github.com/eclipse-tractusx/portal-backend/pull/210
manual update statement:
```sql
UPDATE portal.identities
SET user_entity_id = CASE id
WHEN '7e85a0b8-0001-ab67-10d1-0ef508201026' THEN 'f0c69a64-dfbe-46e4-92db-75f6f4670909'
WHEN '7e85a0b8-0001-ab67-10d1-0ef508201027' THEN '18c3a6b3-ecfe-4572-bbb4-af0c1823f206'
WHEN '7e85a0b8-0001-ab67-10d1-0ef508201028' THEN 'dcb9a153-e1b4-4fac-bc51-7032023e9db9'
ELSE user_entity_id
END
WHERE id IN ('7e85a0b8-0001-ab67-10d1-0ef508201026', '7e85a0b8-0001-ab67-10d1-0ef508201027', '7e85a0b8-0001-ab67-10d1-0ef508201028');
```
> fix(seeding-data): change user_entity_id

- .github/workflows/sonarcloud.yml
- .github/workflows/unit.tests-formatting.yml
adjust filter for dotnet tests to exclude endtoend tests by their category since the FullyQualifiedName filter filters all unit tests
currently the sonarcloud workflow doesn't executes the unit tests
N/A
> fix(sonar): adjust sonarcloud workflow

- src/keycloak/Keycloak.Factory/IKeycloakFactory.cs
- src/keycloak/Keycloak.Factory/KeycloakFactory.cs
- src/provisioning/Provisioning.Library/ProvisioningManager.cs
- src/provisioning/Provisioning.Library/ProvisioningSettings.cs
- tests/provisioning/Provisioning.Library.Tests/Extensions/ClientManagerTests.cs
- tests/provisioning/Provisioning.Library.Tests/ProvisioningManagerTests.cs
- tests/provisioning/Provisioning.Library.Tests/UserManagerTests.cs
Remove the auth trail from the provisioning settings and use the keycloak settings to set the correct useAuthTrail value.
With the current setting we'd need an extra configuration value where it is not needed.
N/A
> fix: set correct useAuthTrail

- src/administration/Administration.Service/BusinessLogic/IIdentityProviderBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
- src/administration/Administration.Service/Controllers/IdentityProviderController.cs
- src/administration/Administration.Service/Models/IdentityProviderDetailsWithConnectedCompanies.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ConnectedCompanyData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IIdentityProviderRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/IdentityProviderBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/IdentityProviderControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/IdentityProviderRepositoryTests.cs
add /api/administration/identityprovider/network/identityproviders/managed/{identityProviderId} endpoint to get idp information with the connected companies
to enable the osp to see which companies are connected to an idp
N/A - Jira Issue: CPLP-3194
> feat(connector): add osp idp detail endpoint

- src/externalsystems/Bpdm.Library/BusinessLogic/BpdmBusinessLogic.cs
- src/externalsystems/Bpdm.Library/Models/BpdmSharingState.cs
- tests/externalsystems/Bpdm.Library/BpdmBusinessLogicTests.cs
Adjust bpdm pull process to handle an unset SharingProcessStarted and retry the process.
Currently the pull fails because the value of SharingProcessStarted isn't expected to be null.
N/A - Jira Issue: CPLP-3226
> fix(bpdm): handle nullable SharingProcessStarted

- DEPENDENCIES
- src/Portal.Backend.sln
- src/framework/Framework.Logging/Framework.Logging.csproj
- src/framework/Framework.Logging/LoggingExtensions.cs
- src/framework/Framework.Logging/MaskingOperator/SecretOperator.cs
- tests/framework/Framework.Logging.Tests/Framework.Logging.Tests.csproj
- tests/framework/Framework.Logging.Tests/SecretOperatorTests.cs
- tests/framework/Framework.Logging.Tests/Usings.cs
Mask sensitive information in our logs
Currently secrets and passwords are written in cleartext to the logs.
N/A - Jira Issue: CPLP-3255
> chore: mask sensitive log data

- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationSettings.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
update dateLastChange of companyApplication
update dateLastChange of companyApplication for some endpoints in registrationService
N/A Ref : CPLP-3313
> feat(registration) : update dateLastChange companyApplication

- src/administration/Administration.Service/appsettings.json
- src/processes/Processes.Worker/appsettings.json
Move the OSPWelcome Mail Template from Administration to ProcessWorker
Currently no mails are send out for the registered users when executing an osp registration
N/A - Jira Issue: CPLP-3355
> chore: added mail template for osp registration

- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/identities.test.json
Only sync active service accounts instead of all service accounts
currently all service accounts are synced which results in a failing worker since the inactive / deleted service accounts do not exist in keycloak anymore
N/A - Jira Issue: CPLP-3312
> fix(sa): only sync active service accounts

- src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityOutputData.cs
- tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs
Adjusted the json property name for bpn within the BpdmLegalEntityOutputData
Currently the bpn fetch process will always be retriggered to a wrong conversion of the bpn which results in bpn will always be null. With this fix the bpn will be converted correctly and if set isn't null
N/A
> fix(bpdm): adjust conversion for bpdm fetch

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/ErrorHandling/AdministrationRegistrationErrorMessageContainer.cs
- src/administration/Administration.Service/Program.cs
- src/framework/Framework.ErrorHandling.Library/ConfigurationException.cs
- src/framework/Framework.ErrorHandling.Library/ConflictException.cs
- src/framework/Framework.ErrorHandling.Library/ControllerArgumentException.cs
- src/framework/Framework.ErrorHandling.Library/DetailException.cs
- src/framework/Framework.ErrorHandling.Library/ErrorDetails.cs
- src/framework/Framework.ErrorHandling.Library/ForbiddenException.cs
- src/framework/Framework.ErrorHandling.Library/Library/ErrorMessageService.cs
- src/framework/Framework.ErrorHandling.Library/Library/ErrorResponse.cs
- src/framework/Framework.ErrorHandling.Library/Library/IErrorMessageContainer.cs
- src/framework/Framework.ErrorHandling.Library/Library/IErrorMessageService.cs
- src/framework/Framework.ErrorHandling.Library/NotFoundException.cs
- src/framework/Framework.ErrorHandling.Library/ServiceException.cs
- src/framework/Framework.ErrorHandling.Library/UnexpectedConditionException.cs
- src/framework/Framework.ErrorHandling.Library/UnsupportedMediaTypeException.cs
- src/framework/Framework.ErrorHandling.Web/GeneralHttpErrorHandler.cs
- tests/framework/Framework.ErrorHandling.Web.Tests/GeneralHttpErrorHandlerTests.cs
Exceptions in Framework.ErrorHandling have been enhanced. They now may contain an error-type, an error-code, a message-template and multiple parameters. This allows structured logging of error-details and a more precise display of errors in the frontend (and optionally internationalization by including multi-language error-message-resources for specific errorcodes into the frontend). As those details are optional this change is fully backwards-compatible and api-endpoints may be adjusted on an 'as needed' basis.
error-messages being returned from api-endpoints are just application-identifier (often a fully qualified class-name) plus string-message. This cannot easily be parsed by the frontend to map to more detailed (and optionally multilingual) help-texts. Parameters of methods throwing …
> feat(errorhandling)! enhance exceptions with details for errortype, errorcode and parameters

- src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
- src/administration/Administration.Service/Models/IdentityProviderUpdateStats.cs
- src/administration/Administration.Service/Models/UserCreationStats.cs
- src/administration/Administration.Service/Program.cs
- src/provisioning/Provisioning.Library/ErrorHandling/ProvisioningServiceErrorMessageContainer.cs
- src/provisioning/Provisioning.Library/Extensions/UserManager.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/IdentityProviderBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
- tests/provisioning/Provisioning.Library.Tests/UserProvisioningServiceCreateUsersTests.cs
Error-messages in bulk-user-upload have been enhanced. In case an error happens creating the user in keycloak the new ErrorDetails type is being used to pass information about the userName and realm of the user to be created in conjunction with an errorcode for the precise error-condition.
error-responses in file-upload based user-creation are not easily parseable by the frontend. The user only gets to see the url of the POST-request but not the payload containing the user-creation-parameters
N/A (CPLP-3189)
> feat(administration)! add errordetails to bulk-user-creation response

- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/connectors.test.json
Fix the pagination of /api/administration/connectors endpoint
Currently the pagination of connectors fails as soon as there are connectors with the same provider but different hosts. which this PR this error is fixed
N/A - Jira Issue: CPLP-3240
> fix(connector): fix /api/administration/connectors ep

- src/mailing/Mailing.Template/EmailTemplates/osp_welcome_email.html
- src/processes/NetworkRegistration.Library/Models/UserMailInformation.cs
- src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
- src/provisioning/Provisioning.Library/Extensions/IdentityProviderManager.cs
- src/provisioning/Provisioning.Library/IProvisioningManager.cs
- tests/processes/NetworkRegistration.Executor.Tests/NetworkRegistrationProcessTypeExecutorTests.cs
- tests/processes/NetworkRegistration.Library.Tests/NetworkRegistrationHandlerTests.cs
- tests/provisioning/Provisioning.Library.Tests/ProvisioningManagerTests.cs
Change the companyName to the idp display name in the osp welcome mail
To give the user which got registered to Catena an easy to understand introduction the company name has been changed to the idp display name
N/A - Jira Issue: CPLP-3470
> fix(osp): change company name to idp display name

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_assigned_collections.json
Adjust user role mapping to company role
Currently the osp role has to much roles and the App Provider / Service Provider have missing roles, with this PR this is fixed
N/A - Jira Issue: CPLP-3509
[#196](https://github.com/eclipse-tractusx/portal-assets/pull/196)
> fix(roles): adjust role mapping for company roles

- src/portalbackend/PortalBackend.Migrations/Migrations/20231122165021_1.7.0-rc4.Designer.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20231122165021_1.7.0-rc4.cs
Merge all migrations since release v1.7.0-RC3 into one migration
To have only one migration per releasee
N/A
> chore: merge migrations into one

- src/keycloak/Keycloak.Seeding/BusinessLogic/ClientsUpdater.cs
set the correct base url for keycloak clients when seeding them
currently the root url was set as baseurl which led to an 400 error in the keycloak seeding
N/A
> fix(seeding): set correct baseUrl for keycloak clients

- src/keycloak/Keycloak.Library/ScopeMappings/KeycloakClient.cs
- src/keycloak/Keycloak.Seeding/BusinessLogic/ClientScopeMapperUpdater.cs
- src/keycloak/Keycloak.Seeding/BusinessLogic/IClientScopeMapperUpdater.cs
- src/keycloak/Keycloak.Seeding/BusinessLogic/ISeedDataHandler.cs
- src/keycloak/Keycloak.Seeding/BusinessLogic/KeecloakSeeder.cs
- src/keycloak/Keycloak.Seeding/BusinessLogic/SeedDataHandler.cs
- src/keycloak/Keycloak.Seeding/Program.cs
Extend the keycloak seeding to seed the clientScopeMappers
if the initial seeding was already done and an update is made with the seeding all clientScopeMappers would be deleted
N/A - Jira Issue: CPLP-3530
> feat(keycloak): add seeder for clientScopeMappers

- src/maintenance/Maintenance.App/BatchDeleteService.cs
- excluding the documents which are linked to one of the following entities from the cleanup job:
- companies
- connector
- consents
- companySsiDetail
When deleting an active connector, the connector and the linked self description document will be set to inactive. The maintenance job was searching for all inactive documents which are older than 80 days. Therefor even still linked documents were selected and tried to be deleted. This resulted in an database error because the documents were still linked.
N/A - Jira Issue: CPLP-3511
> fix(maintenance): only delete not linked documents

- docker/Dockerfile-maintenance-service
adjusted the path for  portal backend dbaccess in the maintenance docker image
currently the action to build the docker image fails because the given path cannot be found
N/A
> fix: adjust dbaccess path for maintenance docker

- src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/identity_assigned_roles.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
Return clientClientId instead of the serviceAccount name for endpoint: GET /api/Services/{serviceId}/subscription/{subscriptionID}/provider
the service account name is getting responded 
N/A - Jira Ref: CPLP-3505
> fix(name): Wrong name property value

- src/administration/Administration.Service/BusinessLogic/IServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ServiceAccountController.cs
- src/administration/Administration.Service/Models/ServiceAccountConnectorOfferData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountDetailedData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IServiceAccountRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/ServiceAccountControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/identities.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
Added filter and lastEditor Data for serviceAccount
Added filter to fetch active and inactive ServiceAccountdetails and added lasteditor fields for a specific service account
N/A Ref : CPLP-3137
> feat(serviceAccount): added filter and lasteditorData

- src/framework/Framework.Swagger/SwaggerGenConfiguration.cs
support nonnullable referenceTypes
In Swagger Document schema, even the fields are non nullable type it shows as nullable, now it is fixed
N/A Ref : CPLP-3407
> feat(swagger): support nonnullable referenceTypes

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IIdentityProviderRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
When declining an application the idp of the company is set to disabled
When declining an application a user is still able to login for the idp of the declined company, this shouldn't be possible
N/A - Jira Issue: TEST-1642
> fix(registration): delete idp on application decline

- src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationWithStatus.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationSettings.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- src/registration/Registration.Service/appsettings.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTests.cs
A new endpoint has been added that returns data that is required by the decline-application-by-invited-user page.
Corresponding PR in CD with new config-values for the applicationStatusIds that allow decline of application by the invited user: https://github.com/eclipse-tractusx/portal-cd/pull/136
When a company is being invited to catena-x a user that received an invitation email shall be able to decline the application that is being created with the invitation. The page that implements this functionality shall display the application-status, the company-name and users of the respective company
N/A (CPLP-3549)
> feat(registration): add endpoint for decline registration data

- src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationWithStatus.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
As a follow-up to https://github.com/eclipse-tractusx/portal-backend/pull/388 the current logged-in user has been added to response of endpoint 'applications/declinedata'
Unit-tests for repository and businesslogic have been added respectively adjusted.
application-decline-page needs to display currently logged-in user.
N/A
> feat(registration): add current user to applicationDeclineData

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json
db seeding data need to get enhanced.
Adding required db seeding data for further enhancement in table portal.agreements
N/A Ref: CPLP-3580
> feat(conformity): enable conformity approval services

- DEPENDENCIES
- src/keycloak/Keycloak.ErrorHandling/Keycloak.ErrorHandling.csproj
Updated the Newtonsoft.Json package to fix a high security finding
The referenced package used by an external package has an high security finding.
n/A
> chore: fix security vulnerability

- src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
Changing the search query for notifications instead of and to or
to enable a better searchability for the notifications
Refs: CPLP-3045
> feat: change search for notifications to or

- src/framework/Framework.Models/SearchSemanticTypeId.cs
- src/notifications/Notifications.Service/BusinessLogic/INotificationBusinessLogic.cs
- src/notifications/Notifications.Service/BusinessLogic/NotificationBusinessLogic.cs
- src/notifications/Notifications.Service/Controllers/NotificationController.cs
- src/notifications/Notifications.Service/Models/NotificationFilters.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/INotificationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
- tests/notifications/Notifications.Service.Tests/BusinessLogic/NotificationBusinessLogicTests.cs
- tests/notifications/Notifications.Service.Tests/Controllers/NotificationControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
the search-filters of view_notifications endpoint now allows to combine the given search-criteria by OR instead of AND. An additional parameter 'searchSemantic' (valid values 'AND', 'OR', defaults to AND) has been added to control the behavior.
So far search-criteria were always combined by AND. That allows to narrow down a bigger result-set (with no filters specified the endpoint would return all notification for the specified user). The OR-semantic starts with an empty result-set (when no filter-parameters are specified) that can be increased by adding filters.
N/A
> feat(notifications): add (optional) OR-semantics to search-query

- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
when submitting agreements with endpoint
/api/registration/application/{applicationId}/companyRoleAgreementConsents we only check for active agreements
currently there is a inactive agreement in the database, which results in the endpoint throwing an error the user can't fix
N/A - Jira Issue: CPLP-3667
> fix(registration): exclude inactive agreements

- src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
- src/registration/Registration.Common/RegistrationValidation.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
disable the duplicate bpn check for endpoint /api/registration/application/{applicationId}/companyDetailsWithAddress
currently one can't update there date within the registration
N/A - Jira Issue: CPLP-3665
> fix(registration): disable duplicate bpn check

- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/AgreementRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/AgreementViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRolesRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/NetworkRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/agreement_assigned_company_roles.test.json
only return agreements with assigned companyRoles for endpoint /api/registration/application/{applicationId}/companyRoleAgreementConsents
Currently all consents are returned, even those for appMarketplace. The endpoint should only return consents which are related to agreements with companyRoles assigned
N/A - Jira Issue: CPLP-3677
> fix(agreement): adjust GET: companyRoleAgreementConsents endpoint

- src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/notifications.test.json
the search-query to retrieve all notification-details for the logged in user has been changed in respect to logical grouping and operator-precedence.
Unit-tests (both code and data) have been adjusted to cover the condition causing the error that has been fixed.
the given search-query runs into ef-core-error: 'Sequence contains more than one element' in case SearchSemantcTypeId.OR is being specified.
This error was introduced by https://github.com/eclipse-tractusx/portal-backend/pull/405
N/A
> fix(notifications): fix search-query resulting in 'Sequence contains more than one element'

- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
allow same status as existing status for endpoint Put: /api/registration/application/{applicationId}/status
When trying to call the endpoint with the same status as the existing one it fails.
N/A - Jira Issue: CPLP-3709
> feat(registration): allow same status update

- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
set the companyId of the logged in user for
POST: /api/apps/appreleaseprocess/consent/{appId}/agreementConsents
POST: /api/services/servicerelease/consent/{serviceId}/agreementConsents
The user receives a 400 error because the company id is not set properly
N/A - Jira Issue: CPLP-3722
> fix(marketplace): set company policy for agreementConsents

- src/administration/Administration.Service/BusinessLogic/IServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ServiceAccountController.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
adjust endpoint GET: api/administration/serviceaccount/owncompany/serviceaccounts to filter for active service accounts by default
Currently if not setting a filter only inactive service accounts will get responded from the endpoint. The default should be only active service accounts.
N/A - Jira Issue: TEST-1799
> fix(sa): adjust filter for inactive service accounts

- src/externalsystems/Clearinghouse.Library/ClearinghouseService.cs
- tests/externalsystems/Clearinghouse.Library.Tests/ClearinghouseServiceTests.cs
Save the error content of the clearinghouse service
To display the user why the request to clearinghouse failed
N/A - Jira Issue: CPLP-3730
> fix(clearinghouse): save error message when failing

- CHANGELOG.md
- src/Directory.Build.props
* update changelog for v1.8.0-RC3
* bump version for v1.8.0-RC3
To have all changes of the latest release available in the changelog and have a new version
N/A
> chore:  update changelog for v.1.8.0-RC3

- src/administration/Administration.Service/BusinessLogic/IUserBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/administration/Administration.Service/Controllers/UserController.cs
- src/framework/Framework.Async/ToImmutableDictionaryAsyncExtension.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyUserData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyUserDetails.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyUserIdentityProviderProcessData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
- src/portalbackend/PortalBackend.PortalEntities/Enums/ProcessTypeId.cs
- src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
- src/processes/Processes.Worker/Processes.Worker.csproj
- tests/administration/Administration.Service.Tests/BusinessLogic/IdentityProviderBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/InvitationBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
- tests/processes/NetworkRegistration.Library.Tests/NetworkRegistrationHandlerTests.cs
- tests/processes/Synchronization.Executor.Tests/IdentityProviderDisplayNameSyncProcessTypeExecutorTests.cs
- tests/processes/Synchronization.Executor.Tests/Synchronization.Executor.Tests.csproj
- tests/processes/Synchronization.Executor.Tests/Usings.cs
* save the userid for each idp for a specific the user
* add displayName to iamIdentityProvider
* return userid of an idp with the idps display name
* create new process to sync the display name of the iamIdentityProvider
to improve transparency
support the user in error cases 
allows us in future to also support "change" on the same
#430
> feat(user): save userid of ipd

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
- src/administration/Administration.Service/Controllers/UserController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
allow lowercase bpns to uppercase.
If a lowercase bpn is send to the backend the bpn should be transformed to all uppercase.
N/A Ref: CPLP-3440
> feat(uppercase): allow lowercase bpn

- src/administration/Administration.Service/BusinessLogic/InvitationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/framework/Framework.Models/ValidationExpressions.cs
- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/InvitationBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
adjust existing endpoints where company name is getting inserted with the same pattern as used for search of company names.
Changes occur in below endpoints:
POST: api/administration/invitation
GET: api/administration/registration/applicationsWithStatus?page=0&amp;size=15</remarks>
GET: api/administration/registration/applications?page=0&amp;size=4
POST: api/administration/registration/network/partnerRegistration
POST: api/registration/application/{applicationId}/companyDetailsWithAddress
PUT: /api/apps/appreleaseprocess/15507472-dfdc-4885-b165-8d4a8970a3e2
POST: /api/apps/appreleaseprocess/createapp
Pattern harmonization across all endpoints where the company name is entered.
N/A Ref: CPLP-3564
N/A Ref: CPLP-3562
> feat(searchpost): update pattern search same company name for post endpoint

- CHANGELOG.md
- src/Directory.Build.props
* update changelog for v1.8.0-RC4
* bump version for v1.8.0-RC4
To have the latest changes for the release within the changelog
[#151](https://github.com/eclipse-tractusx/portal-cd/issues/151)
> build: update changelog for v1.8.0-RC4

- src/framework/Framework.Async/Directory.Build.props
- src/framework/Framework.Cors/Directory.Build.props
- src/framework/Framework.DBAccess/Directory.Build.props
- src/framework/Framework.DateTimeProvider/Directory.Build.props
- src/framework/Framework.ErrorHandling.Library/Directory.Build.props
- src/framework/Framework.ErrorHandling.Web/Directory.Build.props
- src/framework/Framework.HttpClient/Directory.Build.props
- src/framework/Framework.IO/Directory.Build.props
- src/framework/Framework.Linq/Directory.Build.props
- src/framework/Framework.Logging/Directory.Build.props
- src/framework/Framework.Models/Directory.Build.props
- src/framework/Framework.Seeding/Directory.Build.props
- src/framework/Framework.Swagger/Directory.Build.props
- src/framework/Framework.Token/Directory.Build.props
- src/framework/Framework.Web/Directory.Build.props
Add Directory.Build.props to the framework projects
To have a valid check for the nugget packages
Refs: CPLP-3400
> feat(nuget): add directory builds props to framework

- src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationWithStatus.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
adjust endpoint GET /api/registration/applications to response the registrationType as well
The additional information is needed to decide which path the frontend should take.
Refs: #477
> feat(registration): add registrationType to response

- src/administration/Administration.Service/appsettings.json
- src/provisioning/Provisioning.Library/ProvisioningManager.cs
- tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
to be able to successfully delete a realm a new user was introduced to the shared idp
The user which is used for shared idp interactions is missing the admin role, to add a bit of security a new user was introduced with only the admin role, which is only used for the delete action.
Refs: #451
[#161](https://github.com/eclipse-tractusx/portal-cd/pull/161)
> fix(decline): adjust user rights for keycloak user

- tests/endtoend/InterfacePartnerHealthCheck/WalletEndPointTests.cs
set bpn to match the validation schema for wallet creation test
e2e test step WalletCreationInterface_CreateAndDuplicationCheck fails due to an invalid bpn
N/A
> fix(e2e): adjust bpn for wallet creation test

- src/framework/Framework.Web/Framework.Web.csproj
- src/keycloak/Keycloak.Authentication/Keycloak.Authentication.csproj
- tests/endtoend/EndToEnd.Tests.csproj
Downgrade the Authentication.JwtBearer package
The version upgrade of the nuget package results in an error for the health check 
N/A
> fix(jwt): adjust Authentication.JwtBearer version

- src/administration/Administration.Service/appsettings.json
- src/mailing/Mailing.SendMail/MailSettings.cs
- src/mailing/Mailing.SendMail/Mailing.SendMail.csproj
- src/mailing/Mailing.SendMail/MailingService.cs
- src/marketplace/Apps.Service/appsettings.json
- src/marketplace/Services.Service/appsettings.json
- src/processes/Processes.Worker/appsettings.json
- src/registration/Registration.Service/appsettings.json
- tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
- tests/marketplace/Apps.Service.Tests/appsettings.IntegrationTests.json
- tests/marketplace/Services.Service.Tests/appsettings.IntegrationTests.json
The sender mail is now configurable for all services
To give the possibility to configure the sender mail
Refs: #425
[#157](https://github.com/eclipse-tractusx/portal-cd/pull/157)
> fix(mailing): make sender email configurable

- src/keycloak/Keycloak.Authentication/Keycloak.Authentication.csproj
remove explicit dependencies on Microsoft.IdentityModel.JsonWebTokens and System.IdentityModel.Tokens.Jwt
those dependencies cause the authentication-framework to fail as they refer to incorrect versions. They are redundant as they are implicitly defined be the reference to Microsoft.AspNetCore.Authentication.JwtBearer
#325
> fix(keycloak): remove redundant package-references

- src/registration/Registration.Service/Controllers/NetworkController.cs
Add ValidCompany Attribute to endpoint POST: api/registration/network/{externalId}/decline to initialise the companyId of the current user correctly 
When sending a request to the endpoint it always returns `Org.Eclipse.TractusX.Portal.Backend.Web.Identity "companyId should never be null here (endpoint must be annotated with the a company policy)` as an error
Refs: #505
> fix(network): add validCompany to network registration

- .github/workflows/release.yml
- .github/workflows/release_release_candidate.yml
do not run release workflow when a new framework version was published
When pushing a new framework tag the release workflow gets triggered which should not happen.
Refs: CPLP-3400
> fix(release): adjust release workflow

- src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
Ignoring the inactive agreements which are assigned to company roles.
When submitting an external registration where an inactive agreement is assigned to one of the company roles of the company you won't be able to submit the registration successfully. Now the inactive agreements are filtered out.
Refs: #505
> fix(n2n): ignore inactive agreements

- .github/workflows/nuget-package-push.yml
- scripts/get_current_version.sh
Adjust the get_current_version script to only return the tag name
The push Nuget Packages workflow fails due to an invalid tag name
N/A
> build: adjust get version script

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/provisioning/Provisioning.Library/ProvisioningManager.cs
* get users to send mails to before deactivating them
* cleanup delete shared realm call
No mail is send when declining an application because all users got set to deleted before getting them for the mail sending
Refs: #525
> fix(decline): adjust mail sending

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/administration/Administration.Service/appsettings.json
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyCertificateRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyCertificateRepositoryTests.cs
Enable companies to fetch any company certificate(s) via the document ID
GET /api/administration/companydata/companyCertificates/documents/{documentId}
user can fetch documents of other companies as long as the document is "ACTIVE"
document type of the fetched document must be "Company_Certificate" (table documents.document_type)
Exception Cases / Error:
trying to fetch a document which does not exist
trying to fetch a document which is not in status "LOCKED"
trying to fetch a document of another document type
#462 
> feat(document): get company certificate by document id

- src/keycloak/Keycloak.Library/Models/Clients/ClientConfig.cs
- src/keycloak/Keycloak.Library/Models/ProtocolMappers/Config.cs
- src/keycloak/Keycloak.Seeding/BusinessLogic/ClientsUpdater.cs
- src/keycloak/Keycloak.Seeding/BusinessLogic/ProtocolMappersUpdater.cs
add user.session.note from client protocol mapper to iam seeding
needed for realm config upgrade
https://github.com/eclipse-tractusx/portal-iam/issues/47
> chore(iam): add user.session.note from client protocol mapper to seeding

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IConnectorsBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ConnectorsController.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/ConnectorsControllerTests.cs
connector discovery endpoint without body
connector discovery endpoint without body returns results
N/A : CPLP-2957
> feat: connector discovery endpoint without body

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_assigned_collections.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRoleCollectionRolesViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
added seeding data
added seeding data for userRoleAssignedCollection table
N/A : CPLP-3582
> feat: added seeding data for userRoleAssignedCollection

- src/administration/Administration.Service/Controllers/RegistrationController.cs
Fixed the routing for the /retrigger-validate-did endpoint
Swagger isn't loading because of a duplicate route.
N/A
> fix(administration): fix routing for retrigger-validate-did

- src/marketplace/Offers.Library/Service/OfferService.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferReleaseData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
The current implementation of the app release process expects at least 1 technical user role selected for connecting the app(s) to central applications.
Till now a technical user was mandatorily needed - BUT changed recently and we need to allow with 24.05. that an user can release an app even without technical user connection.
To allow the same on backend side, following endpoints need to get adjusted:
PUT /api/apps/AppReleaseProcess/{appId}/submit
Update the endpoint business logic - in the current implementation the technicalUserProfile is set as MUST to allow the user to run PUT /api/apps/AppReleaseProcess/{appId}/submit for a specific app.
This logic needs to get removed. It is allowed to submit an app request without technicalUserProfile configured
#497 
Please delete options that …
> feat(app): allow app release without technical user profile

- src/processes/Processes.Worker/appsettings.json
Add subject for mail template
The process worker fails when starting due to the missing subject
Refs: #483
> fix(mailing): add subject for NewUserExternalIdpTemplate

- src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
- tests/processes/NetworkRegistration.Library.Tests/NetworkRegistrationHandlerTests.cs
Adjusting the mail template that's send out after the network registration from 'CredentialRejected' to 'OspWelcomeMail'
To send out the correct template
N/A
> fix(networkRegistration): adjust mail tempalte

- docker/Dockerfile-iam-seeding
- docker/Dockerfile-maintenance-service
- docker/Dockerfile-portal-migrations
- docker/Dockerfile-processes-worker
- docker/Dockerfile-provisioning-migrations
adjust runtime version for docker images
The docker images are currently failing because of a wrong runtime version
Refs: #456
> fix: adjust runtime version for docker images

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/application_checklist.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_applications.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/identities.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/process_steps.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/processes.consortia.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/AppInstanceRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/app_instance_assigned_company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
- remove service account sa-cl5-custodian-1 and adjust tests
- rename service account sa-cl5-custodian-2
- onboard CX-Test-Access (consortia-test-data)
https://github.com/eclipse-tractusx/portal-iam/issues/66
> chore(iam-seeding): remove service-account and onboard CX-Test-Access(consortia)

- src/portalbackend/PortalBackend.Migrations/Seeder/BatchUpdateSeeder.cs
Add CompanyApplications to the batchUpdateSeeder
To set the checklistProcessId for seeded companyApplications
N/A
> fix(seeding): add companyApplication to update seeder

- src/registration/Registration.Common/RegistrationValidation.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/NetworkBusinessLogicTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Skip validation for bpn is empty
The registration validation is always failing when no bpn is set because the regex validation jumps in place
Refs: #639
> fix(registration): skip validation for bpn is empty

- src/mailing/Mailing.SendMail/SendMail.cs
remove disposal of mimeMessage
Mail isn't send correctly because the mime message is disposed before the mail gets send
Refs: #579
> fix(mail): remove disposal of mimeMessage

- src/externalsystems/Bpdm.Library/BpnAccess.cs
Remove the leading slash from the api of the bpn access
when setting a leading slash in the url for the http client the url path is overwritten
#632
> feat(bpdm): fix /api/registration/legalEntityAddress/{bpn} endpoint

- src/externalsystems/Bpdm.Library/BpdmService.cs
- src/externalsystems/Bpdm.Library/DependencyInjection/BpdmServiceCollectionExtension.cs
- src/externalsystems/Bpdm.Library/DependencyInjection/BpnAccessCollectionExtension.cs
- tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs
- tests/shared/Tests.Shared/Extensions/IFixtureExtensions.cs
- tests/shared/Tests.Shared/Tests.Shared.csproj
Fix the bpdm request urls
When registering the base url it must end with an /. This has been added to the registration of the bpdm http clients
Refs: #632
> fix(bpdm): adjust bpdm request urls

- src/externalsystems/Bpdm.Library/DependencyInjection/BpdmServiceCollectionExtension.cs
- src/framework/Framework.Async/Directory.Build.props
- src/framework/Framework.Cors/Directory.Build.props
- src/framework/Framework.DBAccess/Directory.Build.props
- src/framework/Framework.DateTimeProvider/Directory.Build.props
- src/framework/Framework.DependencyInjection/Directory.Build.props
- src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
- src/framework/Framework.ErrorHandling.Web/Directory.Build.props
- src/framework/Framework.ErrorHandling/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/HttpClientExtensions.cs
- src/framework/Framework.IO/Directory.Build.props
- src/framework/Framework.Linq/Directory.Build.props
- src/framework/Framework.Logging/Directory.Build.props
- src/framework/Framework.Models/Directory.Build.props
- src/framework/Framework.Seeding/Directory.Build.props
- src/framework/Framework.Swagger/Directory.Build.props
- src/framework/Framework.Token/Directory.Build.props
- src/framework/Framework.Web/Directory.Build.props
- src/marketplace/Apps.Service/Apps.Service.csproj
- src/marketplace/Apps.Service/Program.cs
- src/marketplace/Offers.Library/DependencyInjection/OfferSetupServiceExtensions.cs
- src/marketplace/Services.Service/Program.cs
- src/marketplace/Services.Service/Services.Service.csproj
- src/processes/OfferSubscription.Executor/DependencyInjection/OfferSubscriptionProcessCollectionExtensions.cs
Move the configuration of the dim to the app and services service
The dim is registered multiple times for the processes worker.
N/A
> fix(dim): move registration of dim to app and services service

- src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
- src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityOutputData.cs
- tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs
In BpdmService.FetchInputLegalEntity map bpdm-identifier-types to string instead of BpdmIdentifierTypeId
This PR is an alternative solution for PR #619
Bpdm internally uses DUNS-identifier which is not compliant with Gaja-X. This results in failures deserializing the response from calls querying existing legal entities. On the other hand in the response to those calls only the BPN is being used, the bpdm-identifier-types are not of relevance. Mapping the values of bpdm-identifier-types to string instead of BpdmIdentifierTypeId does allow deserialization the response ignoring all unknown identifiers
#618 
> fix(bpdm): ignore bpdm-identifiers in FetchInputLegalEntity

- src/externalsystems/Dim.Library/BusinessLogic/DimBusinessLogic.cs
- src/externalsystems/Dim.Library/Schemas/DidDocument.schema.json
- tests/externalsystems/Dim.Library.Tests/DimBusinessLogicTests.cs
Adjusting the did schema validation
The current schema returned from the did middle layer isn't valid
N/A
> feat(did): adjust did schema

- src/externalsystems/Dim.Library/DependencyInjection/DimServiceCollectionExtension.cs
- src/externalsystems/Dim.Library/DimService.cs
- tests/externalsystems/Bpdm.Library/BPNAccessTest.cs
- tests/externalsystems/Dim.Library.Tests/DimServiceTests.cs
- tests/shared/Tests.Shared/Extensions/IFixtureExtensions.cs
Setting the base address for the universal revolver correctly
The request of the universal resolver is failing because the base address isn't set correctly
N/A
> fix(universalResolver): set base address for universal resolver

- src/administration/Administration.Service/BusinessLogic/MailBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
- src/processes/Processes.Worker/appsettings.json
- src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
- src/registration/ApplicationActivation.Library/DependencyInjection/ApplicationActivationSettings.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
Saving the mail processes after they are created
The mail processes are created, but not saved in the database, therefore no mail will be send out.
N/A
> fix(mailing): add save calls after creating mail processes

- .github/dependabot.yml
- src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRolesRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
created an endpoint to fetch user roles for an app provider
The endpoint provides app providers an overview of configures app roles
Ref : #575
> fix(appRelease): created an endpoint to fetch user roles for an app provider

- src/externalsystems/BpnDidResolver.Library/BusinessLogic/BpnDidResolverBusinessLogic.cs
- src/externalsystems/IssuerComponent.Library/BusinessLogic/IssuerComponentBusinessLogic.cs
Set the IDENTITY_WALLET step to done after the transmittion of the bpn / did to the resolver
The process stays in IN_PROGRESS, even after all steps are executed successfully
N/A
> fix(applicationChecklist): set correct state for IDENTITY_WALLET step

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/Models/DimUrlsResponse.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
* adjust the response of the endpoint /api/administration/companydata/decentralidentity/urls
The urls were mixed up.
#674
> fix(didUrls): adjust response of companydata/decentralidentity/urls

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/externalsystems/IssuerComponent.Library/BusinessLogic/IIssuerComponentBusinessLogic.cs
- src/externalsystems/IssuerComponent.Library/BusinessLogic/IssuerComponentBusinessLogic.cs
- src/externalsystems/IssuerComponent.Library/Models/CreateFrameworkCredentialRequest.cs
- src/externalsystems/IssuerComponent.Library/Models/UseCaseFrameworkId.cs
- src/externalsystems/IssuerComponent.Library/Service/IIssuerComponentService.cs
- src/externalsystems/IssuerComponent.Library/Service/IssuerComponentService.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
- tests/externalsystems/IssuerComponent.Library.Tests/IssuerComponentBusinessLogicTests.cs
* adjust framework creation endpoint to call the ssi credential issuer
The user doesn't has all necessary data available to call the ssi-credential-issuer directly, therefore the portal backend provides an endpoint to than create a framework credential
N/A
[#70](https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/70)
> feat(ssi): adjust framework creation endpoint

- src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
- src/administration/Administration.Service/Models/IdentityProviderDetails.cs
- src/administration/Administration.Service/Models/PartnerRegistrationData.cs
- src/administration/Administration.Service/appsettings.json
- src/provisioning/Provisioning.Library/Extensions/ClientManager.cs
- src/provisioning/Provisioning.Library/Extensions/IdentityProviderManager.cs
- src/provisioning/Provisioning.Library/Extensions/RealmManager.cs
- src/provisioning/Provisioning.Library/Extensions/RoleManager.cs
- src/provisioning/Provisioning.Library/Extensions/ServiceAccountManager.cs
- src/provisioning/Provisioning.Library/Extensions/UserManager.cs
- src/provisioning/Provisioning.Library/IProvisioningManager.cs
- src/provisioning/Provisioning.Library/Models/IdentityProviderConfigOidc.cs
- src/provisioning/Provisioning.Library/Models/IdentityProviderConfigSaml.cs
- src/provisioning/Provisioning.Library/ProvisioningManager.cs
- src/provisioning/Provisioning.Library/Service/IUserProvisioningService.cs
- src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/IdentityProviderBusinessLogicTests.cs
change response-type-definition of endpoint GET / POST /api/administration/identityprovider/owncompany/identityproviders to allow null-values
as clientId is not a mandatory parameter when creating a new identityprovider right after its creation the identityproviders config-property clientId is not set when querying the keycloak api. ClientId being null results in an InvalidKeycloakResponse-exception being thrown. As a result the response when creating a new identityProvider despite the actual creation is successful an internal error is being returned.
#682 
> fix(identityprovider): allow null values in get- or create identityprovider response

- src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
fixed isOwner filter
when hitting GET: api/administration/serviceaccount/owncompany/serviceaccounts with isOwner flag as true it results
companyServiceAccountTypeIds as Managed Type records instead of showing only Own Type records, now it is fixed by adding additional check condition
Ref : #563
> fix: fixed isOwner filter

- src/notifications/Notifications.Service/Controllers/NotificationController.cs
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/identities.json
- tests/externalsystems/IssuerComponent.Library.Tests/IssuerComponentServiceTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
Adding the sa-cl24-01 technical user to the database seeding
When calling the portal from the ssi credential issuer, the call fails with a 401 because the technical user isn't existing in the database
[#66](https://github.com/eclipse-tractusx/portal-iam/issues/66)
> fix(seeding): add missing service accounts and improve descriptions

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/Models/DimUrlsResponse.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
Instead of throwing an error when a specific value isn't set, return null for those values.
To always return data for the customer, even if some values are not set.
Refs: #710
> fix: adjust error tolerance for GET companyData/decentralidentity/urls

- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
The shortDescription is not fetched from the backend. Instead we always receive "ERROR".
Per app the short description is expected to get fetched from offer_descriptions.description_short
Based on the submitted language parameter. If no language parameter is provided fetch the "en" description_short.
#590 
> fix(app): fix app short description getting error

- src/administration/Administration.Service/appsettings.json
- src/externalsystems/Clearinghouse.Library/BusinessLogic/ClearinghouseBusinessLogic.cs
- src/externalsystems/Clearinghouse.Library/ClearinghouseSettings.cs
- src/externalsystems/Custodian.Library/BusinessLogic/CustodianBusinessLogic.cs
- src/externalsystems/Custodian.Library/CustodianService.cs
- src/externalsystems/Custodian.Library/CustodianSettings.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/processes/Processes.Worker/appsettings.json
- tests/externalsystems/Clearinghouse.Library.Tests/ClearinghouseBusinessLogicTests.cs
* get the did of the company from the database if the dim wallet is enabled instead of requesting it from the miw
Since the portal enabled the configuration to use the dim wallet instead of the miw wallet, the did is saved in the database for a company after the wallet is created. Therefore the call to the miw to receive the did for the bpn of the company can be skipped.
Refs: #695
[#297](https://github.com/eclipse-tractusx/portal/pull/297)
> fix(registration): adjust clearinghouse data post

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/app_instances.consortia.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/app_instances.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRoleCollectionRolesViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/app_instances.test.json
fix: add clients with composite roles to app_instances base seeding; Registration, Portal and technical_roles_management were accidentally maintained in consortia test data seeding
#718
> fix: add clients to app_instances base seeding

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/externalsystems/IssuerComponent.Library/BusinessLogic/IIssuerComponentBusinessLogic.cs
- src/externalsystems/IssuerComponent.Library/BusinessLogic/IssuerComponentBusinessLogic.cs
- src/externalsystems/IssuerComponent.Library/Service/IIssuerComponentService.cs
- src/externalsystems/IssuerComponent.Library/Service/IssuerComponentService.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
- tests/externalsystems/IssuerComponent.Library.Tests/IssuerComponentBusinessLogicTests.cs
- tests/externalsystems/IssuerComponent.Library.Tests/IssuerComponentServiceTests.cs
- tests/shared/Tests.Shared/Extensions/ControllerExtensions.cs
* adjust framework credential creation to call the ssi issuer with the current user instead of the technical user
The calling user of the framework credential creation is stored in the database as requester on the ssi issuer site. Therefore it needs to be the calling user of the endpoint on portal side instead of a generic technical user. 
Refs: #712
[101](https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/101)
> fix(credential): call ssi with current user for framework credentials

- src/portalbackend/PortalBackend.Migrations/Migrations/20240514145358_2.0.0-rc8.Designer.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20240514145358_2.0.0-rc8.cs
existing migration 593-AdjustDimTechnicalusers  has been renamed to 2.0.0-rc8
release- and release-candidate migrations shall aggregate all intermediate migrations and be named according to the respective release
https://github.com/eclipse-tractusx/portal/issues/318
> chore(update): rename migration for rc8

- src/processes/Invitation.Executor/DependencyInjection/InvitationSettings.cs
- src/processes/Invitation.Executor/InvitationProcessService.cs
Add decline url to invite mail template
The decline url is empty in the mail template
Refs: #701
https://github.com/eclipse-tractusx/portal/pull/311
> fix(decline): add decline url for invite process

- src/portalbackend/PortalBackend.DBAccess/Models/OfferRoleInfos.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
added roleId for exitisting activeRoleDetails
added roleId field for exiting get endpoints in app marketplace
Ref : #705 
> feat(app): add roleId for exitisting activeRoleDetails

- src/portalbackend/PortalBackend.DBAccess/Models/UserRoleData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IServiceAccountRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- src/processes/DimUserCreationProcess.Executor/DimUserCreationProcessService.cs
- src/provisioning/Provisioning.Library/Service/ServiceAccountCreation.cs
- tests/processes/DimUserCreationProcess.Executor.Tests/DimUserCreationProcessServiceTests.cs
- tests/provisioning/Provisioning.Library.Tests/Extensions/ServiceAccountCreationTests.cs
technical user creation has been adjusted such that no keycloak-serviceaccount is created in case only the dim-role is being  requested.
The additional keycloak service-account that was created before this change is useless and therefore confuses the user.
#593 
> fix(dim): do not create keycloak sa for dim

- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
The query being used to determine roles to be assigned has been adjusted to not include unassigned but not requested and assignable roles.
update of core-offer-roles would result in all roles to be assigned that are assignable in respect to the assigned company-roles
#748 
> fix(role assignment): fix query for core offer role assignment

- src/marketplace/Services.Service/Controllers/ServicesController.cs
Need to change permission for below mentioned endpoints:
Endpoint: GET /api/services/subscribed/subscription-status
Change permission check to view_service_subscriptions
Endpoint: GET /api/services/{serviceId}/subscription/{subscriptionId}/subscriber
Change permission check to subscribe_service
Endpoint: GET /api/services/{serviceId}/subscription/{subscriptionId}/provider
Change permission check to service_management
updated permission roles for api endpoints as mentioned in description.
#750 
> feat(permission): add fix for permission check on api endpoints

- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyInvitationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- src/processes/Processes.Worker.Library/IProcessTypeExecutor.cs
queries that return a single guid from a joined table are adjusted to join in the where-condition instead of the selection
EF throws 'System.InvalidOperationException: Nullable object must have a value' in case the where-condition of a query is not fulfilled and the query selects a single guid from a joined table.
#754 
> fix(processes): fix offersubscription process initialization

- src/administration/Administration.Service/BusinessLogic/IServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ServiceAccountController.cs
- src/administration/Administration.Service/Models/ServiceAccountConnectorOfferData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IServiceAccountRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/ServiceAccountControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
endpoint GET /api/administration/serviceaccount/owncompany/serviceaccounts
* now returns serviceaccounts in status ACTIVE and PENDING. (Before the change only ACTIVE serviceaccounts were returned).
* A new optional parameter userStatus is added to the endpoint that can be used to filter for specific UserStatusIds. Multiple values are allowed (e.g. ...&userStatus=ACTIVE&userStatus=INACTIVE&userStatus=PENDING)
* if set the parameter userStatus has higher priority than the existing parameter 'filterForInactive'
* a new property 'status' (type UserStatusId) is added to the endpoint.
endpoint GET /api/administration/serviceaccount/owncompany/serviceaccounts/<serviceAccountId>
* a new property 'status' (type UserStatusId) is added to the endpoint.
* serviceAccounts in status …
> feat(serviceaccounts): include pending serviceaccounts and add userstatus to result

- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
query of endpoint GET /api/administration/serviceaccount/owncompany/serviceaccounts was adjusted
in case the result contains serviceaccounts in different status the query results in error "Sequence contains more than one element".
#760
> fix(serviceAccount): fix error "Sequence contains more than one element"

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/Models/ServiceAccountConnectorOfferData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
endpoint GET /api/administration/serviceaccount/owncompany/serviceaccounts/<serviceaccountid> has been adjusted to allow null clientId, iamClientAuthMethod and secret.
SERVICE_UNDEFINED_CLIENTID_CONFLICT is not raised any more in case clientId is null
when calling this endpoint for serviceaccounts in status PENDING or INACTIVE the iamClientAuthMethod and secret cannot be retrieved from keycloak and should be returned as null but error SERVICE_UNDEFINED_CLIENTID_CONFLICT was raised (which is only appropriate for status ACTIVE).
#760 
> fix(serviceaccount): fix conflict errors for inactive and pending serviceaccounts

- src/portalbackend/PortalBackend.Migrations/Migrations/20240517135403_2.0.0-rc10.Designer.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20240517135403_2.0.0-rc10.cs
migration 20240517135403_CPLP-3548-declineRegistration is renamed to 20240517135403_2.0.0-rc10
released migrations should refer to the release-name, not individual tickets
https://github.com/eclipse-tractusx/portal/issues/328
> chore(migrations): rename migration for rc10

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/marketplace/Offers.Library/Service/IOfferSetupService.cs
- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- src/provisioning/Provisioning.Library/Service/IServiceAccountCreation.cs
- src/provisioning/Provisioning.Library/Service/ServiceAccountCreation.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
Added the process id to the offer subscription for the dim user to retrieve the offer subscription
Currently the process to create the dim technical users fails because it is not linked to a offer subscription
Refs: #762
> fix(sa): fix old autosetup process for dim technical user creation

- src/administration/Administration.Service/BusinessLogic/SubscriptionConfigurationBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ProviderDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/SubscriptionConfigurationBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
Adjust endpoint PUT /api/administration/SubscriptionConfiguration/owncompany to allow the deletion of the configured url
To allow the deletion of the configured url
Refs: #764
> fix(ownCompany): allow deletion of configured url for own company

- src/registration/Registration.Service/Controllers/RegistrationController.cs
Add valid company policy to POST: /api/registration/application/{applicationId}/declineregistration
Since the companyId of the user is used in the endpoint the policy needs to be added
N/A
> fix(policy): add valid company policy

- DEPENDENCIES
- src/administration/Administration.Service/BusinessLogic/SubscriptionConfigurationBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/SubscriptionConfigurationBusinessLogicTests.cs
adjust handling if url null is send when no provider company detail is set
when trying to set url to null if no provider company detail is existing the endpoint throws a 500 error
N/A
> fix(subscriptionConfig): adjust url null case

- src/processes/Invitation.Executor/InvitationProcessTypeExecutor.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
- tests/processes/Invitation.Executor.Tests/InvitationProcessTypeExecutorTests.cs
Add locking to the invite process
If the process worker runs parallel with multiple instances, it leads to an error in the invite process due to an duplicate creation of a shared idps client
Refs: #787
> fix(invite): add locking to invite process

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ConnectorsSettings.cs
- src/externalsystems/SdFactory.Library/BusinessLogic/SdFactoryBusinessLogic.cs
- src/externalsystems/SdFactory.Library/SdFactoryService.cs
- src/externalsystems/SdFactory.Library/SdFactorySettings.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/externalsystems/SdFactory.Library.Tests/SdFactoryBusinessLogicTests.cs
- tests/externalsystems/SdFactory.Library.Tests/SdFactoryServiceTests.cs
Add feature toggle to disable all sd factory calls for the application checklist and connector registration
To be able to switch off the sd factory connection
#792
https://github.com/eclipse-tractusx/portal/pull/344
> feat(clearinghouse): add feature toggle for sd connectivity

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Moved the validation of blank or null comment from child method to parent method.
fixes #820  closes #820 
There is a required validation on the comment field at a later stage in this API. Before this, the code makes a call to Keycloak to delete the client for this company.
If we call this API with a blank comment, it throws an exception after deleting the data from Keycloak.
and after that its impossible to cancel the application process
[#820](https://github.com/eclipse-tractusx/portal-backend/issues/820)
> fix(decline): moved email validation in decline application process api

- src/marketplace/Apps.Service/Controllers/AppChangeController.cs
- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
`view_clinet_roles` is supposed to get used when it comes to actual role assignment. Since the App Manager is not supposed to assign roles to company users, the permission is not expected to be assigned.
Instead the permission of the following endpoints need to get switched
- GET /api/apps/AppChange/{appId}/roles => new permission validation `edit_apps`
- GET /api/apps/AppReleaseProcess/{appId}/roles => new permission validation `add_apps`
App manager encounters 403 error on Technical Integration while registering an app.
[Refs: 826](https://github.com/eclipse-tractusx/portal-backend/issues/826)
> fix(getAppRoles): change permissions

- src/portalbackend/PortalBackend.Migrations/Migrations/20240527114938_2.1.0-rc1.Designer.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20240527114938_2.1.0-rc1.cs
migration 20240527114938_538-RemoveSsiDetails is renamed to 20240527114938_2.1.0-rc1
https://github.com/eclipse-tractusx/portal/issues/350
> chore(2.1.0-rc1): rename migration

- src/marketplace/Apps.Service/Controllers/AppsController.cs
the apps service routing definition of endpoint PUT /subscription/{subscriptionId}/activate is changed to PUT /api/apps/subscription/{subscriptionId}/activate
the service-internal definition of endpoint PUT /subscription/{subscriptionId}/activate is missing the path-prefix /api/apps and is therefore inaccessible as it is not routed to the service be the ingress.
https://github.com/eclipse-tractusx/portal-backend/issues/856
> fix(apps): remove leading '/' from the activate subscription endpoint

- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- src/portalbackend/PortalBackend.DBAccess/Models/TriggerProviderInformation.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/identities.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
the query that retrieves the to-be-activated-on-keycloak service-accounts is being restricted to return service-accounts of CompanyServiceAccountKindId.INTERNAL only and the subscription is not being activated.
on activation of an autosetup-offersubscription that includes the creation of external (dim-) serviceaccounts the process-step ACTIVATE_SUBSCRIPTION tries to activate all serviceaccounts on keycloak. this includes the external-serviceaccounts that do not exist on keycloak which results in an error 'clientId <external client id>not found in central keycloak'
https://github.com/eclipse-tractusx/portal-backend/issues/856
> fix(offersubscription): suppress activation of external serviceaccounts on activation of offersubscription

- src/externalsystems/Dim.Library/BusinessLogic/DimBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- tests/externalsystems/Dim.Library.Tests/DimBusinessLogicTests.cs
Fix the logic for the dim callback.
When more than one company with the same bpn exists the callback of the dim fails.
Refs: #862
> fix(dim): fix callback logic for dim requests

- src/administration/Administration.Service/Administration.Service.csproj
- src/framework/Framework.DBAccess/Framework.DBAccess.csproj
- src/framework/Framework.DateTimeProvider/Framework.DateTimeProvider.csproj
- src/framework/Framework.DependencyInjection/Framework.DependencyInjection.csproj
- src/framework/Framework.HttpClientExtensions/Framework.HttpClientExtensions.csproj
- src/framework/Framework.Seeding/Framework.Seeding.csproj
- src/maintenance/Maintenance.App/Maintenance.App.csproj
- src/marketplace/Apps.Service/Apps.Service.csproj
- src/portalbackend/PortalBackend.DBAccess/PortalBackend.DBAccess.csproj
- src/portalbackend/PortalBackend.Migrations/PortalBackend.Migrations.csproj
- src/portalbackend/PortalBackend.PortalEntities/PortalBackend.PortalEntities.csproj
- src/processes/Processes.ProcessIdentity/Processes.ProcessIdentity.csproj
- src/processes/Processes.Worker/Processes.Worker.csproj
- src/provisioning/Provisioning.DBAccess/Provisioning.DBAccess.csproj
- src/provisioning/Provisioning.Migrations/Provisioning.Migrations.csproj
- src/provisioning/Provisioning.ProvisioningEntities/Provisioning.ProvisioningEntities.csproj
- src/registration/ApplicationActivation.Library/ApplicationActivation.Library.csproj
- src/registration/Registration.Service/Registration.Service.csproj
- tests/portalbackend/PortalBackend.DBAccess.Tests/PortalBackend.DBAccess.Tests.csproj
- tests/portalbackend/PortalBackend.Migrations.Tests/PortalBackend.Migrations.Tests.csproj
- tests/provisioning/Provisioning.DBAccess.Tests/Provisioning.DBAccess.Tests.csproj
increase efcore version to latest 8.0.7
efcore 8.0.2 has transitive dependency System.Text.Json 8.0.0 which has a security-vulerability that is clasified as high. Upgrade to efcore 8.0.7 implicitly upgrades this dependency to System.Text.Json 8.0.4 which resolves the vulnerability.
[Link to Github issue.](https://github.com/eclipse-tractusx/portal/issues/369)
> chore(dependencies): bump efcore to 8.0.7

- src/externalsystems/OfferProvider.Library/BusinessLogic/OfferProviderBusinessLogic.cs
- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- src/portalbackend/PortalBackend.DBAccess/Models/TriggerProviderInformation.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/externalsystems/OfferProvider.Library/BusinessLogic/OfferProviderBusinessLogicTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
skip creation of TRIGGER_PROVIDER_CALLBACK processstep in case no callback-url is configured in ProviderCompanyDetails
skip execution of TRIGGER_PROVIDER_CALLBACK processstep in case no callback-url is configured in ProviderCompanyDetails
in processstep TRIGGER_PROVIDER_CALLBACK skip retrieval of service-account secret for external serviceaccounts
in ProviderCompanyDetails the callbackurl is declared as optional (nullable). If it is not set the process-step TRIGGER_PROVIDER_CALLBACK is nevertheless created and executed but fails with error-message 'Callback Url should be set here'
#856 
> fix(offersubscription): skip optional autosetupprovidercallback  if it is not configured

- src/processes/Processes.Worker/appsettings.json
default clientPrefix has been added to Process-workers appsettings.json
ProcessWorker would create new clients with pure numerical clientid without prefix
#856
> fix(processWorker): add default clientPrefix

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
- src/marketplace/Offers.Library/Models/WalletConfigData.cs
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/appsettings.IntegrationTests.json
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
Enhance endpoint GET /api/apps/{appId}/subscription/{subscriptionId}/provider to also return external service for the edc
To provide useful information for the edc connection
Rest: #841
https://github.com/eclipse-tractusx/portal/pull/385
> fix: enhance subscription/provider endpoint with external Service data

- src/externalsystems/SdFactory.Library/BusinessLogic/SdFactoryBusinessLogic.cs
set process step to skipped if ClearinghouseConnectDisabed is true
The process step was set to done before, but should be set to skipped
Refs: #792
> fix(sdDoc): set process step to skipped if ClearinghouseConnectDisabed is true

- CHANGELOG.md
- src/Directory.Build.props
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_role_descriptions.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
https://github.com/eclipse-tractusx/portal/issues/380
> build(2.1.0-rc2): merge main into main

- src/externalsystems/Bpdm.Library/Models/BpdmAddressDto.cs
- src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
- tests/externalsystems/Bpdm.Library/BPNAccessTest.cs
- tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs
Nullable double for altitude in coordinates allowed. Test case adjusted.
As per BPDM specification.
Null altitude breaks onboarding. Altitude is rarely set.
Refs: #881
> fix(bpdm): allow null values for geographic coordinate altitude

- src/administration/Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/administration/Administration.Service/Models/CompanyDetailsOspOnboarding.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyApplication.cs
- src/portalbackend/PortalBackend.PortalEntities/Enums/CompanyApplicationStatusFilter.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/administration/Administration.Service.Tests/Controllers/RegistrationControllerTest.cs
GET endpoint should be accessible at /api/administration/registration/network/companies.
Paginated response with max 20 records per page along with sorting, filtering and authorisation is required.
Need this api  to retrieve a list of all Onboarded OSP (Onboarding Service Provider) companies along with their current ### status
#808
> feat(osp): endpoint to get onboarding osp companies details

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServicesController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
* enhance endpoint `GET /api/apps/subscribed/subscription-status` with subscription status filter
* enhance endpoint `GET: /api/services/subscribed/subscription-status` with subscription status filter
To give the customer the possibility to filter the app / service subscriptions by it's status 
Refs: #592
> feat(subscription): add optional subscription status filter

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
Removed active flag to get the user details in case of declined application
fixes #871 closes #871 
Currently in portal ‘Invite a new partner’ page shows blank in Full name if user declines the registration.
Because user is no longer active in DB so this code just returns null .
[Issue 871](https://github.com/eclipse-tractusx/portal-backend/issues/871)
> fix(decline): removed active flag to get the name

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/Models/CompanyApplicationDetails.cs
Enhance the /api/administration/registration/applications?size=10&page=0 endpoint by adding a new attribute "type" to the response, which indicates whether the application is "external" or "internal". This information is available at the application level in the database.
Retrieve the "type" information from the application-level data in the database.
Ensure the "type" attribute is properly mapped and included in the endpoint response.
Update the existing response structure to include the new "type" attribute for each application in the "content" array.
#842 
> feat(registration): new attribute type added in registration application endpoint

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
enhanced the filter according to offerTypeId
For the api `api/services/servicerelease/{serviceId}/serviceStatus` leadPictureId in response is blank GUID.
This method has been called from app as well as service so it requires a filtering whether to choose AppLeadImage or ServiceLeadImage
NA
> fix(service): fix the lead picture id

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
When creating a connector the correct connector status is set
Currently the wrong state is set
Refs: #918
> fix(connector): create connector with correct state

- src/administration/Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/administration/Administration.Service/Models/CompanyApplicationStatusFilter.cs
- src/administration/Administration.Service/Models/CompanyDetailsOspOnboarding.cs
- src/administration/Administration.Service/Models/DateCreatedOrderFilter.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyApplication.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/administration/Administration.Service.Tests/Controllers/RegistrationControllerTest.cs
Change endpoint GET /api/administration/registration/network/companies
- Add externalID field to the response body to represent the external identifier of the company.
- Add dateCreated field to the response body to represent the creation date of the company record.
- Add new (optional) query-parameter externalID to facilitate lookup using external identifiers.
- Add new (optional) query parameter dateCreatedOrderFilter (values ASC, DESC) to specify order of result.
- Implement sorting by dateCreated in both ascending (ASC) and descending (DESC) order.
The response body should include the new fields externalID and dateCreated.
The API should support query parameters for searching by companyName and externalID.
The API should support query parameters for sorting by dateCreated in both ASC …
> feat(osp): add externalID and datecreated in registration network companies api

- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/identities.test.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
Update the backend logic for /api/administration/Connectors to allow the registration of connectors with technical users in the "PENDING" status.
Update the backend logic for /api/administration/Connectors/managed to allow the registration of connectors with technical users in the "PENDING" status.
This change is temporary change till long term solution still in discussion as mentioned in ticket for allowing registration of connectors with technical users status as "PENDING".
#843 
> fix(connectors): allowing registration of connectors with pending status technical users

- tests/framework/Framework.Tests.Shared/Framework.Tests.Shared.csproj
Remove deprecated package Microsoft.AspNetCore.Mvc.Abstractions
The package is deprecated and wasn't used.
Refs: #582
> chore(dependencies): remove Microsoft.AspNetCore.Mvc.Abstractions

- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
Added a model to get the Identity provider type
Modified the `GetCompanyAndApplicationDetailsForApprovalAsync` method to get Identity provider type 
Added condition on setting up shared theme for shared IDP only
fix #848 close #848 
Earlier if we use Managed idp(eg using Azure AD) then application activation was failing because code was trying to set theme on shared realm, which don't exist.
[Issue 848](https://github.com/eclipse-tractusx/portal-backend/issues/848)
> fix(OSP Invite): Handle theme for shared realm

- src/notifications/Notifications.Service/BusinessLogic/NotificationBusinessLogic.cs
- src/notifications/Notifications.Service/Controllers/NotificationController.cs
- src/notifications/Notifications.Service/Models/NotificationRequest.cs
- tests/notifications/Notifications.Service.Tests/BusinessLogic/NotificationBusinessLogicTests.cs
Adjust the create notification request type
The request parameter should be receiver instead of requester, since it is the person who receives the notification
Refs: #812
https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/233
https://github.com/eclipse-tractusx/portal-iam/pull/169
> feat(notification): adjust create notification endpoint

- src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
Renamed the property `OwnCompanyData` to `IsOwnCompanyData` as per[ BPDM api specifications](https://eclipse-tractusx.github.io/docs-kits/next/kits/Business%20Partner%20Kit/Software%20Development%20View/Gate%20Api/upsert-business-partners-input)
BPDM was having issues as this flag `IsOwnCompanyData` was always false as Portal was sending wrong flag
#927  
> fix(BPDM): fixed the request structure of BPDM api

- CHANGELOG.md
- src/Directory.Build.props
- src/administration/Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationSettings.cs
- src/administration/Administration.Service/BusinessLogic/UserRolesBusinessLogic.cs
- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/administration/Administration.Service/Models/CompanyApplicationStatusFilter.cs
- src/administration/Administration.Service/Models/CompanyDetailsOspOnboarding.cs
- src/administration/Administration.Service/Models/DateCreatedOrderFilter.cs
- src/administration/Administration.Service/appsettings.json
- src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
- src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/Extensions/AppExtensions.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyApplication.cs
- src/processes/ApplicationChecklist.Library/ApplicationChecklistEntryTypeIdExtensions.cs
- src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/administration/Administration.Service.Tests/Controllers/RegistrationControllerTest.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
https://github.com/eclipse-tractusx/portal/issues/398
> build(2.2.0-rc2): merge release into main

- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/IntegrationTests/ConnectorsControllerIntegrationTests.cs
When requesting connectors via GET: /api/administration/connectors with existing managed connectors, the managed connectors are also getting with own need to change the filter
The endpoint should only return connectors of type COMPANY_CONNECTOR so that own type can get only there types connectors and managed will get there type.
#945 
> fix(connectors): add company connectors type filter to get connectors

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
Removed the authentication details from logs DIM response and only logged the DIM document
It was exposing the client id and secret of Dim wallet
NA
> fix(DID): removed authentication details from logs DIM response

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
When creating a managed connector via POST: /api/administration/connectors/managed the host company is set as the provider and the provider company is set as the host
The correct provider and host should be set.
#944 
> fix(connectors): add updation for provider and host company id in managed endpoint

- src/administration/Administration.Service/BusinessLogic/IInvitationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/InvitationBusinessLogic.cs
- src/administration/Administration.Service/Controllers/InvitationController.cs
- src/administration/Administration.Service/Models/CompanyInvitationResponse.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/InvitationBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/InvitationControllerTests.cs
Added the company id and application id in Invite api return response
In automation and CRM for self registration (Hubspot) there was no reference id to track the Invitation .
So now by this change they can track the invitation by company id and application id.
NA
> feat(Invite): added company and application in invite api response

- src/mailing/Mailing.Template/EmailTemplates/serviceprovider_subscription_activation.html
Requester name is null
Requester name is null when requester or subscriber receives the Subscription Activation email.
[Ref: 973](https://github.com/eclipse-tractusx/portal-backend/issues/973)
> fix(subscriptionActivationEmail): null requester name

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServicesController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
* added query param `name` to endpoint `GET: /api/apps/subscribed/subscription-status` to filter for app names
* added query param `name` to endpoint `GET: /api/services/subscribed/subscription-status` to filter for service names
* changed query param `statusId` to `status` of endpoint `GET: /api/apps/subscribed/subscription-status`
To be able to search for specific apps
Refs: #592
> feat(app): adjust status query param for subscription-status

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IServiceAccountManagement.cs
- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ServiceAccountManagement.cs
- src/administration/Administration.Service/Controllers/ConnectorsController.cs
- src/administration/Administration.Service/Program.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ConnectorData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/DeleteServiceAccountData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountManagementTests.cs
- tests/administration/Administration.Service.Tests/Controllers/ConnectorsControllerTests.cs
- tests/administration/Administration.Service.Tests/EndpointSetup/ConnectorsEndpoints.cs
- tests/administration/Administration.Service.Tests/IntegrationTests/ConnectorsControllerIntegrationTests.cs
- tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
* add flag to define whether a linked service account should be deleted
* adjust deletion logic for service accounts when deleting a connector
The deletion logic for connectors currently doesn't support the deletion process of external service accounts
Refs: #966 #967
> feat(connector): adjust connector deletion

- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
change GetConnectorDeleteDataAsync to splitquery
this query returns 2 independent IEnumerables which is inefficient when not being executed as splitquery. This was forgotten in #968 
#966 
> fix(connectordeletion): change GetConnectorDeleteDataAsync to splitquery

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/ErrorHandling/AdministrationConnectorErrorMessageContainer.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
Add check if a combination of name and url is already existing for a connector 
without the check the database throws an error which is unhandled.
Refs: #917
> feat(connector): add duplicate check to connector creation

- src/administration/Administration.Service/appsettings.json
- src/externalsystems/Bpdm.Library/BpdmServiceSettings.cs
- src/externalsystems/Bpdm.Library/BusinessLogic/BpdmBusinessLogic.cs
- src/processes/Processes.Worker/appsettings.json
- tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
- tests/externalsystems/Bpdm.Library/BpdmBusinessLogicTests.cs
add toggle to disable the set sharing state ready call of the bpdm service
Bpdm has a toggle to set the sharing state automatically to ready, for that purpose its useful to have a toggle on the portal side as well.
Refs: #845
https://github.com/eclipse-tractusx/portal/pull/403
> feat(bpdm): add sharing state ready toggle

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
return technical users in state `PENDING_DELETION`
To be able to display the technical users in state pending deletion
Refs: #989
> fix(serviceAccount): return technical user in state pending deletion

- src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
- src/processes/Invitation.Executor/InvitationProcessService.cs
- src/provisioning/Provisioning.Library/Models/UserCreationRoleDataIdpInfo.cs
- src/provisioning/Provisioning.Library/Service/IUserProvisioningService.cs
- src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
- tests/processes/Invitation.Executor.Tests/InvitationProcessServiceTests.cs
- tests/provisioning/Provisioning.Library.Tests/UserProvisioningServiceCreateUsersTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
User(s) didnt receive invite emails when invited via Add Multiple Users. Users has been created but invite email does not sent out to users.
Recently bulk uploaded users were not getting email notifications
[Ref: #920](https://github.com/eclipse-tractusx/portal-backend/issues/920)
> fix(emailNotification): Add Multiple Users | Invite email didnt receive by User(s)

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/Models/ServiceAccountConnectorOfferData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountDetailedData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
* remove subscriptionId from response
The subscription Id is responded twice, it is already present in the offerData
Refs: #897
> fix(serviceAccount): adjust response for get serviceaccount detail

- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Changed the mapping of Region Field with District 
User is sending this data from FE which is sent via BE using District field to BPDM but when user try to fill it again from BPN search it becomes null as it is mapped with another field in BPDM
#979 
> fix(registration): fix region mapping

- .github/dependabot.yml
to capture all dependencies without creating multiple custom groups
grouping into production and development dependencies appears to not be working, example logs: "Skipping update group for 'production-dependencies' as it does not match any allowed dependencies."
no pull requests get created
n/a
relates to https://github.com/eclipse-tractusx/portal/issues/300
> chore(dependabot): change grouping pattern

- src/administration/Administration.Service/BusinessLogic/IServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/ErrorHandling/AdministrationServiceAccountErrorMessageContainer.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OwnServiceAccountData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
Adjust the error messages for `DELETE: api/administration/serviceaccount/owncompany/serviceaccounts/{serviceAccountId}`
To give a more specific error message
Refs: #986
https://github.com/eclipse-tractusx/portal-assets/pull/399
> feat(serviceAccount): adjust error messages

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ServiceAccountSettings.cs
- src/administration/Administration.Service/Models/ServiceAccountConnectorOfferData.cs
- src/administration/Administration.Service/appsettings.json
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountDetailedData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
Add Parameter usertype and authentication_service_url in below mentioned api
GET: api/administration/serviceaccount/owncompany/serviceaccounts/{GetServiceAccountId}
For checking user_type internal or external and valid authenticatio_service_url for specific technical user 
#976 
> feat(technicaluser): new parameters for api expansion for technical user data added 

- src/portalbackend/PortalBackend.Migrations/Seeder/BatchUpdateSeeder.cs
Added the 'agreements' table in update seeder
It is quite possible that operator company may want different name of agreement or enable/disable them.
Currently this table is missing from BatchUpdateSeeder.cs so even if operator company overwrite the seeder file ,agreement data won't get updated.
NA
> fix(Registration): added agreement table in update seeder

- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
App Manager is not receiving the email notification upon approval or rejecting the app.
In the App Request Management section, users are not receiving email notifications when an App Release Request is approved or rejected. This error has been introduced with the refactoring of email-creation by process-worker. The dbcontext now must be saved after creating the email-processes. Before the refactoring email-creating did not involve the database.
[Ref: 1015](https://github.com/eclipse-tractusx/portal-backend/issues/1015)
> fix(appManagement): not getting Emails on the Rejection of App Release Request

- src/portalbackend/PortalBackend.DBAccess/Repositories/IIdentityProviderRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
- src/processes/IdentityProviderProvisioning.Executor/IdentityProviderProvisioningProcessTypeExecutor.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/IdentityProviderRepositoryTests.cs
- tests/processes/IdentityProviderProvisioning.Executor.Tests/IdentityProviderProvisioningProcessTypeExecutorTests.cs
If an iamIdp exists delete it before deleting the idp
The current process fails due to an existing iamIdentityProvider which isn't deleted
Refs: #1025
> fix(idp): delete iam identity provider

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ServiceAccountSettings.cs
- src/administration/Administration.Service/Controllers/ServiceAccountController.cs
- src/administration/Administration.Service/appsettings.json
- src/portalbackend/PortalBackend.DBAccess/Models/UserRoleData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRolesRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
Add type flag to user role to display if an external technical user is created in the frontend
To add an identifier if an external user is created for a user role
Refs: #1022
https://github.com/eclipse-tractusx/portal/pull/435
> feat(userRoles): add type to userRole

- .tractusx
add api specifications from feature branch
should only get merged once https://github.com/eclipse-tractusx/portal-backend/pull/1030 is ready for testing
to the api-hub as it only consider specification references within main branch
https://github.com/eclipse-tractusx/portal-backend/issues/1021
> test(api-hub): add api specifications from feature branch

- .tractusx
change to raw.githubusercontent for openApiSpecs
api-hub runs into error when collecting specification
follow up to https://github.com/eclipse-tractusx/portal-backend/pull/1032
https://github.com/eclipse-tractusx/portal-backend/issues/1021
> test(api-hub): change to raw.githubusercontent for openApiSpecs

- .tractusx
change to filename without .Service
leads to issues when filename is used to determine directory structure at api-hub
follow up to https://github.com/eclipse-tractusx/portal-backend/pull/1032 and https://github.com/eclipse-tractusx/portal-backend/pull/1033
https://github.com/eclipse-tractusx/portal-backend/issues/1021
> test(swagger-hub): change to filename without .Service

- CHANGELOG.md
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_assigned_collections.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_descriptions.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_roles.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRoleCollectionRolesViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
Add `Registration Internal` as new technical user that can be created in portal.
New `technical_roles_management` composite role with name `Registration Internal` with:
- `invite_new_partner`
- `view_submitted_applications`
is also being added as new client role in eclipse-tractusx/portal-iam#189
Operator company wants to integrate 3rd party service to send out invites. Allows inviting and reviewing status via API.
Refs: eclipse-tractusx/portal-backend#932
Related: eclipse-tractusx/portal-iam#189
> feat(tech user): add internal invitation tech user

- src/externalsystems/Dim.Library/Schemas/DidDocument.schema.json
- tests/externalsystems/Dim.Library.Tests/DimBusinessLogicTests.cs
Adjust the did document schema validation to allow multiple entries in the @context array
To fix the validation of the did document schema
Refs: #1054
> fix(schema): adjust did document schema validation

- .github/workflows/marketplace-app-service.yml
- .github/workflows/registration-service.yml
- .github/workflows/services-service.yml
* add externalService to the build of registration, marketplace and services service
To build images of the named services when and external service changes
Refs: #1056
> fix: add external services to workflows

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/administration/Administration.Service/Models/UserRoleWithDescription.cs
- src/marketplace/Apps.Service/Apps.Service.csproj
- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
- src/marketplace/Apps.Service/appsettings.json
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/ServiceSettings.cs
- src/marketplace/Services.Service/appsettings.json
- src/portalbackend/PortalBackend.DBAccess/Models/TechnicalUserProfileInformation.cs
- src/portalbackend/PortalBackend.DBAccess/Models/UserRoleData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ITechnicalUserProfileRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRolesRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/TechnicalUserProfileRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
- tests/endtoend/CreateAppScenario/CreateNewTestAppScenario.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/TechnicalUserProfileRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
* add internal | external flag to the userRoles of an technicalUserProfile
To give the frontend the possibility to show the internal and external roles separately
Refs: #1007
https://github.com/eclipse-tractusx/portal/pull/440
> feat(technicalUser): add internal external flag to profiles

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Currently the endpoint GET: /api/registration/documents/{documentId} only response the document for the user which has uploaded the document. This check should be adjusted with adding check of OPERATOR and company application status confirmed.
These additional check required for getting document to particular user satisfies the check condition.
Link to Github issue.
#1070 
> feat(check): additional checks for OPERATOR and confirmed status added in document request endpoint

- .github/workflows/pre-checks.yml
- docs/api/apps-service.yaml
- docs/api/services-service.yaml
- pre-checks: add step to check for uncommitted files: refers to updated api specifications
see failing example: https://github.com/eclipse-tractusx/portal-backend/actions/runs/11365413480/job/31613546790
see successful example: https://github.com/eclipse-tractusx/portal-backend/actions/runs/11365510125/job/31613850865#step:7:13
- commit updated api specifications
check need due to https://github.com/eclipse-tractusx/portal-backend/issues/1021
> chore: check for uncommitted files and commit api specs

- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
- src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
fixing the query to select the registration roles
The clientClientId of the selection was always null, therefor the process worker can't successfully complete the onboarding
Refs: #1108
> fix: adjust remove registration role query

- src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ProcessStepRepository.cs
fixing the query to get the process steps for external technical user creation / deletion
To fix the callback logic of the external technical user creation / deletion 
Refs: #1112
> fix: adjust query for technical user creation / deletion

- src/framework/Framework.Async/Directory.Build.props
- src/framework/Framework.Cors/Directory.Build.props
- src/framework/Framework.DBAccess/Directory.Build.props
- src/framework/Framework.DateTimeProvider/Directory.Build.props
- src/framework/Framework.DependencyInjection/Directory.Build.props
- src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
- src/framework/Framework.ErrorHandling.Web/Directory.Build.props
- src/framework/Framework.ErrorHandling/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/HttpAsyncResponseMessageExtension.cs
- src/framework/Framework.IO/Directory.Build.props
- src/framework/Framework.Linq/Directory.Build.props
- src/framework/Framework.Logging/Directory.Build.props
- src/framework/Framework.Models/Directory.Build.props
- src/framework/Framework.Seeding/Directory.Build.props
- src/framework/Framework.Swagger/Directory.Build.props
- src/framework/Framework.Token/Directory.Build.props
- src/framework/Framework.Web/Directory.Build.props
- src/processes/Processes.Worker.Library/ProcessExecutionService.cs
- tests/processes/Processes.Worker.Library.Tests/ProcessExecutionServiceTests.cs
Handled the system exception and added the Critical/Fatal log type so that we can monitor the logs for criticality.
It was causing issues for other processes as well .
Eg if a OSP customer sets the wrong callback address or if it is down then it returns the referenced class of SystemException and then it crashed the pod , which stops all other processes.
#1114 
> fix(process worker): fix the crashing of pod

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IConnectorsBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ConnectorsController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ConnectorUpdateInformation.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/ConnectorsControllerTests.cs
in endpoint api/administration/Connectors/{connectorId}/connectorUrl
open the table portal.documents, search for the connectors.self_description_document_id inside the field id and set the status to "INACTIVE"
now trigger the SD factory endpoint 
The backend logic will set the current connector assigned self-description to "INACTIVE" - no matter which status the document has currently (retrieve via the table portal.connectors the linked self-description document from the attribute connectors.self_description_document_id.
#549 
> feat(connector): connector controller change url added

- src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
- src/provisioning/Provisioning.Library/Extensions/IdentityProviderManager.cs
- src/provisioning/Provisioning.Library/IProvisioningManager.cs
- src/provisioning/Provisioning.Library/ProvisioningManager.cs
- src/provisioning/Provisioning.Library/Service/IIdentityProviderProvisioningService.cs
- src/provisioning/Provisioning.Library/Service/IUserProvisioningService.cs
- src/provisioning/Provisioning.Library/Service/IdentityProviderProvisioningService.cs
- src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Added method to update display name and organisation attribute value in Identity provider in keycloak
This was causing mismatch issue in login screen for company name and also in the user profile menu after  login in portal
#942 
> fix(registration): fixed the company name change in IDP

- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTests.cs
Adjusted the query to get users for the initial role assignment
Currently the query filters users which don't have the initial roles assigned out of the result, thus no users gets the roles assigned.
Refs: #1134
> fix: adjust query to get users for role assignment

- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyConnectorViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/connectors.unittest.json
Fixed the EDC discovery endpoint by filtering an grouping it by Host 
Earlier its was filtering by provider which was showing managed connector under provider BPN which is incorrect.
#1089 
> fix(connector): fixed the edc discovery endpoint

- src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
- src/administration/Administration.Service/Models/PartnerRegistrationData.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/NetworkBusinessLogicTests.cs
Added short name in company creation
Api had this field in request but was missing in the code while creating the company
NA
> fix(osp): added short name in company creation

- docs/api/services-service.yaml
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/ViewModels/ServiceDetailResponse.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offers.unittest.json
Responding providerUrl field for service details.
The 'Provider Homepage' field is blank on the Service details page, even though a URL was provided during the service creation process.
Ref: #1125
> fix(providerHomepage): responding providerUrl for service

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/PortalDbContextTests.cs
In endpoint API: GET: /api/administration/connectors/{connectorId} 
As a customer/host company user can't see the details of managed connector getting company {companyId} is not provider of connector {connectorId} error
Only provider and host/customer company should be able to see the details of connector.
#1090 
> fix(connector): change providercompany check to get access for managed connector

- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
On the portal home page, the 'New Apps' section is showing apps in a random order instead of the most recently created four apps, making it difficult to identify the latest additions.
Apps are displayed in a random order rather than the most recent four created apps.
Ref: #1131
> fix(activeApps): respond sorted list of Apps

- src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
- src/provisioning/Provisioning.Library/Extensions/IdentityProviderManager.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/IdentityProviderBusinessLogicTests.cs
Set the correct urls in the config when updating the idp
To have the urls set in keycloak as well as in the database
Refs: #1152
> fix(idp): set urls for idp update

- docs/api/administration-service.yaml
- src/administration/Administration.Service/BusinessLogic/ITechnicalUserBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/TechnicalUserBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ServiceAccountController.cs
- src/administration/Administration.Service/Program.cs
- src/marketplace/Offers.Library/Service/ITechnicalUserProfileService.cs
- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- src/marketplace/Offers.Library/Service/TechnicalUserProfileService.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferCompanySubscriptionStatusData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.PortalEntities/Entities/OfferSubscription.cs
- src/provisioning/Provisioning.Library/Extensions/ServiceAccountCreationExtensions.cs
- src/provisioning/Provisioning.Library/Models/TechnicalUserCreationInfo.cs
- src/provisioning/Provisioning.Library/Service/ITechnicalUserCreation.cs
- src/provisioning/Provisioning.Library/Service/TechnicalUserCreation.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/TechnicalUserBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/ServiceAccountControllerTests.cs
- tests/endtoend/ServiceAccountCUDScenarios/AdministrationEndpointHelper.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
- tests/provisioning/Provisioning.Library.Tests/Extensions/TechnicalUserCreationTests.cs
Remove the limitation to only have one technical user per offer
To create multiple technical users for an offer
Refs: #1136
> feat: enable multiple technical user for offers

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
Please include a summary of the change.
Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.
Ref: #1221
> fix(connector): delete connector when sdFactory is disabled

- docs/api/services-service.yaml
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/ViewModels/ServiceDetailResponse.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
add "displayTechnicalUser": "boolean" to be provided in the following api
/api/services/{serviceId}
As per request changes displayTechnicalUser Api added
#1210 
> feat(parameter): add displaytechnicaluser parameter in get service api

- docs/api/apps-service.yaml
- docs/api/services-service.yaml
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/marketplace/Services.Service/Controllers/ServicesController.cs
Roles `subscribe_apps` and `subscribe_service` has been changed to `view_subscription` and `view_service_subscriptions` on following APIs:
GET: /api/apps/{appId}/subscription/{subscriptionId}/subscriber
GET: /api/services/{serviceId}/subscription/{subscriptionId}/subscriber
App & service subscription details CTA leads to 403 error.
Ref: #987
> fix(offerSubscription): change role (#69)

- src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
The success/error message count displayed after bulk user upload is incorrect. When uploading a list of users, if some entries are duplicates, the popup message incorrectly indicates that all users were successfully uploaded, even though there were failed entries.
Because of incorrect Success/Error Message Count in the response of Bulk user upload API.
Ref: #1225
> fix(bulkUserUpload): Incorrect Success/Error Message Count

- docs/api/administration-service.yaml
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyMissingSdDocumentData.cs
- src/portalbackend/PortalBackend.DBAccess/PortalBackend.DBAccess.csproj
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
Add SdSkipped Date to GET: /api/administration/companyData/missing-sd-document
To get an overview when the process was skipped
Refs: #1179
> feat(companyData): enhance GET: /api/administration/companyData/missing-sd-document

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ConnectorUpdateInformation.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
Updated the validation on update connector api so that only provider can update the connector
Currently it was not possible for provider to update the connector url which provided by themself only
#1085 
> fix(connector): only provider should update connector

- src/framework/Framework.Async/Directory.Build.props
- src/framework/Framework.Cors/Directory.Build.props
- src/framework/Framework.DBAccess/Directory.Build.props
- src/framework/Framework.DateTimeProvider/Directory.Build.props
- src/framework/Framework.DependencyInjection/Directory.Build.props
- src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
- src/framework/Framework.ErrorHandling.Web/Directory.Build.props
- src/framework/Framework.ErrorHandling/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/Directory.Build.props
- src/framework/Framework.IO/Directory.Build.props
- src/framework/Framework.Identity/Directory.Build.props
- src/framework/Framework.Linq/Directory.Build.props
- src/framework/Framework.Logging/Directory.Build.props
- src/framework/Framework.Models/Directory.Build.props
- src/framework/Framework.Models/ValidationExpressions.cs
- src/framework/Framework.Processes.Library.Concrete/Directory.Build.props
- src/framework/Framework.Processes.Library/Directory.Build.props
- src/framework/Framework.Processes.ProcessIdentity/Directory.Build.props
- src/framework/Framework.Processes.Worker.Library/Directory.Build.props
- src/framework/Framework.Seeding/Directory.Build.props
- src/framework/Framework.Swagger/Directory.Build.props
- src/framework/Framework.Token/Directory.Build.props
- src/framework/Framework.Web/Directory.Build.props
- src/registration/Registration.Common/RegistrationValidation.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/NetworkBusinessLogicTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Applied one more validation on `uniqueIds` param through regex.
Currently, request is being validated with invalid data e.g: "VAT ID" --> “value“ : “XYZ“
Ref: #1157
> fix(osp): applied regex validation on uniqueIds param

- src/framework/Framework.Async/Directory.Build.props
- src/framework/Framework.Cors/Directory.Build.props
- src/framework/Framework.DBAccess/CustomNpgsqlHistoryRepository.cs
- src/framework/Framework.DBAccess/Directory.Build.props
- src/framework/Framework.DBAccess/Framework.DBAccess.csproj
- src/framework/Framework.DateTimeProvider/Directory.Build.props
- src/framework/Framework.DependencyInjection/Directory.Build.props
- src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
- src/framework/Framework.ErrorHandling.Web/Directory.Build.props
- src/framework/Framework.ErrorHandling/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/Directory.Build.props
- src/framework/Framework.IO/Directory.Build.props
- src/framework/Framework.Identity/Directory.Build.props
- src/framework/Framework.Linq/Directory.Build.props
- src/framework/Framework.Logging/Directory.Build.props
- src/framework/Framework.Models/Directory.Build.props
- src/framework/Framework.Processes.Library.Concrete/Directory.Build.props
- src/framework/Framework.Processes.Library/Directory.Build.props
- src/framework/Framework.Processes.ProcessIdentity/Directory.Build.props
- src/framework/Framework.Processes.Worker.Library/Directory.Build.props
- src/framework/Framework.Seeding/Directory.Build.props
- src/framework/Framework.Swagger/Directory.Build.props
- src/framework/Framework.Token/Directory.Build.props
- src/framework/Framework.Web/Directory.Build.props
- src/portalbackend/PortalBackend.Migrations/Program.cs
- src/provisioning/Provisioning.Migrations/Program.cs
- src/provisioning/Provisioning.Migrations/Provisioning.Migrations.csproj
- src/provisioning/Provisioning.Migrations/ProvisioningDbContextFactory.cs
* add custom history repository
To overwrite the implementation of Npgsql which is skipping the existing check of the migration table, which leads to an error in our implementation, since the migration history tables are located in the public schema. Since the `portal` and `provisioning` user don't have the create grant the `create if not exists`statement of the nuget package fails. 
Refs: #1262
> fix(migrations): add custom history repository

- docker/Dockerfile-provisioning-migrations
Add Framework.DBAccess to provisioning migration docker
To fix the failing migration docker build
Refs: #1262
> fix(migrations): adjust provisioning docker

- src/portalbackend/PortalBackend.DBAccess/PortalRepositories.cs
- src/portalbackend/PortalBackend.DBAccess/PortalRepositoriesStartupServiceExtensions.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IPortalProcessStepRepository.cs
Adjust the registration for PortalProcessStepRepository
The current registration couldn't be resolved by the dependency injection
Refs: #1268
> fix: adjust registration for processStepRepository

- src/marketplace/Offers.Library/Service/OfferService.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
adjust the check for providerOnlyRoles
currently only technical user with provider only roles can be created
N/A
> fix: adjust technical user creation

- src/framework/Framework.Async/Directory.Build.props
- src/framework/Framework.Cors/Directory.Build.props
- src/framework/Framework.DBAccess/Directory.Build.props
- src/framework/Framework.DateTimeProvider/Directory.Build.props
- src/framework/Framework.DependencyInjection/Directory.Build.props
- src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
- src/framework/Framework.ErrorHandling.Web/BaseHttpExceptionHandler.cs
- src/framework/Framework.ErrorHandling.Web/CustomAuthorizationMiddleware.cs
- src/framework/Framework.ErrorHandling.Web/Directory.Build.props
- src/framework/Framework.ErrorHandling/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/Directory.Build.props
- src/framework/Framework.IO/Directory.Build.props
- src/framework/Framework.Identity/Directory.Build.props
- src/framework/Framework.Linq/Directory.Build.props
- src/framework/Framework.Logging/Directory.Build.props
- src/framework/Framework.Models/Directory.Build.props
- src/framework/Framework.Processes.Library.Concrete/Directory.Build.props
- src/framework/Framework.Processes.Library/Directory.Build.props
- src/framework/Framework.Processes.ProcessIdentity/Directory.Build.props
- src/framework/Framework.Processes.Worker.Library/Directory.Build.props
- src/framework/Framework.Seeding/Directory.Build.props
- src/framework/Framework.Swagger/Directory.Build.props
- src/framework/Framework.Token/Directory.Build.props
- src/framework/Framework.Web/Directory.Build.props
- src/framework/Framework.Web/StartupServiceExtensions.cs
- src/framework/Framework.Web/StartupServiceWebApplicationExtensions.cs
- tests/framework/Framework.ErrorHandling.Web.Tests/CustomAuthorizationMiddlewareTests.cs
Adding the new error message format for 401 and 403 errors
to return a json object for 401 and 403 errors
Refs: #1282
> fix(errorHandling): adjust error structure for 401 and 403 errors

- src/administration/Administration.Service/appsettings.json
- src/externalsystems/SdFactory.Library/Models/SdFactoryRequestModel.cs
- src/externalsystems/SdFactory.Library/SdFactoryService.cs
- src/externalsystems/SdFactory.Library/SdFactorySettings.cs
- src/processes/Processes.Worker/appsettings.json
- tests/externalsystems/SdFactory.Library.Tests/SdFactoryBusinessLogicTests.cs
- tests/externalsystems/SdFactory.Library.Tests/SdFactoryServiceTests.cs
Integration of Gaia-X Tagus release (v2) for Connector.
v1 will be retired as of March 2025. Any API v1 calls will fail with a 400 HTTP Status Code.
Ref: #1288
Link to PR in other repository:
https://github.com/eclipse-tractusx/portal/pull/516
> feat(connector): Integrate the Gaia-X Tagus Updates

- src/externalsystems/Bpdm.Library/BpdmService.cs
- tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs
Remove hardcoded v6 path in bpdm cx-memberships api call. BusinessPartnerPoolBaseAddress should contain base api path including version.
There is a customizable poolApiPath in portal values including API version. Calls are failing if the pool has any path.
Refs: eclipse-tractusx/portal-backend#1299
Depends on: eclipse-tractusx/portal#518
> fix(BpdmService): cx-memberships call to expect custom api path

- docs/api/administration-service.yaml
- src/portalbackend/PortalBackend.DBAccess/Models/ProviderDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/SubscriptionConfigurationBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/SubscriptionConfigurationControllerTests.cs
Added the callback url in GET response of the api `api/administration/subscriptionconfiguration/owncompany`
User is not able to see the current callback url
#1304
> fix(auto-setup): added the callback url in GET

- src/framework/Framework.Async/Directory.Build.props
- src/framework/Framework.Cors/Directory.Build.props
- src/framework/Framework.DBAccess/Directory.Build.props
- src/framework/Framework.DateTimeProvider/Directory.Build.props
- src/framework/Framework.DependencyInjection/Directory.Build.props
- src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
- src/framework/Framework.ErrorHandling.Web/Directory.Build.props
- src/framework/Framework.ErrorHandling/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/Directory.Build.props
- src/framework/Framework.IO/Directory.Build.props
- src/framework/Framework.Identity/Directory.Build.props
- src/framework/Framework.Linq/Directory.Build.props
- src/framework/Framework.Logging/Directory.Build.props
- src/framework/Framework.Models/Directory.Build.props
- src/framework/Framework.Models/ValidationExpressions.cs
- src/framework/Framework.Processes.Library.Concrete/Directory.Build.props
- src/framework/Framework.Processes.Library/Directory.Build.props
- src/framework/Framework.Processes.ProcessIdentity/Directory.Build.props
- src/framework/Framework.Processes.Worker.Library/Directory.Build.props
- src/framework/Framework.Seeding/Directory.Build.props
- src/framework/Framework.Swagger/Directory.Build.props
- src/framework/Framework.Token/Directory.Build.props
- src/framework/Framework.Web/Directory.Build.props
- src/registration/Registration.Common/RegistrationValidation.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/NetworkBusinessLogicTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
UniqueIdentifier's regex updates country wise, as per frontend: https://github.com/eclipse-tractusx/portal-frontend-registration/blob/main/src/types/Patterns.ts
- Currently, umlauts are not being validated when used as CRN: München HRB 42243 and return 400 error.
- As per new Tagus release changes, Commercial registration number needs to be validated with this format: F1103R_HRB98814
Ref: #1314
https://github.com/eclipse-tractusx/portal-frontend-registration/pull/364
> feat(uniqueIdentifier): update country wise regex

- src/externalsystems/OfferProvider.Library/BusinessLogic/OfferProviderBusinessLogic.cs
- src/externalsystems/OfferProvider.Library/Models/OfferProviderCallbackData.cs
- tests/externalsystems/OfferProvider.Library.Tests/BusinessLogic/OfferProviderBusinessLogicTests.cs
Removed the validation which was for single technical users only
Updated the request body sent in the callback URL 
Now the app can have multiple technical users, so this fix is to enable the code to send multiple technical users to the callback URL.
#1307 
> fix(auto-setup): fixed the validation and request for callback url

- src/administration/Administration.Service/BusinessLogic/TechnicalUserBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/TechnicalUserBusinessLogicTests.cs
When creating an external technical user and viewing it's details the service endpoint which is displayed is wrong value that value should be shown only when user status is active 
Proper msg need to show in place of Service Endpoint for existing techincal user with pending user status
#1326 
> fix(userstatus): add Service endpoint msg for pending user status of technical user.

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_assigned_collections.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_descriptions.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_roles.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRoleCollectionRolesViewTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
Add new Connector Manager role to seeding data and update tests. For Active Participant.
Customer want to manage connector registration via API to automate registration flow.
Refs: #1329
Depends on: eclipse-tractusx/portal-iam#271 / eclipse-tractusx/portal-iam#276 by @arnabcx
> feat(technical user role): add connector management

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/ErrorHandling/AdministrationConnectorErrorMessageContainer.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ITechnicalUserRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/TechnicalUserRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/TechnicalUserRepositoryTests.cs
Added a validation for technical user in connector registration so that only available technical user can be used.
In last release database constraints has been removed and hence this api starts accepting same technical user to multiple connectors. 
#1139 
> feat(connector): add validation for technical user in connector registration

- src/administration/Administration.Service/BusinessLogic/TechnicalUserBusinessLogic.cs
- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- src/provisioning/Provisioning.Library/Models/ServiceAccountCreationProcessData.cs
- src/provisioning/Provisioning.Library/Service/ITechnicalUserCreation.cs
- src/provisioning/Provisioning.Library/Service/TechnicalUserCreation.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/TechnicalUserBusinessLogicTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offer_subscriptions.unittest.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/process_steps.unittest.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/processes.unittest.json
adjust the technical user creation callback from dim middle layer
to activate the technical users when a app or service subscription is setup
Refs: #1371
> fix: external technical user creation for app and service subscriptions

- docs/api/services-service.yaml
- src/marketplace/Services.Service/Controllers/ServicesController.cs
Service Subscription | Decline api is throwing 404 error
When a service with valid subscriptionId is tried to be declined then 404 error is displaying.
Ref: https://github.com/eclipse-tractusx/portal-backend/issues/1377
> fix(serviceSubscriptionDecline): resolved the api route issue

- src/externalsystems/OfferProvider.Library/OfferProviderService.cs
- src/externalsystems/OnboardingServiceProvider.Library/OnboardingServiceProviderService.cs
Added scope in token generation in auto setup.
Token generation was failing as most of the IDP requires scope
#1375 
> fix(auto-setup): fix the open id

- .tractusx
- CHANGELOG.md
- docs/api/administration-service.yaml
- docs/api/apps-service.yaml
- docs/api/notifications-service.yaml
- docs/api/registration-service.yaml
- docs/api/services-service.yaml
- src/Directory.Build.props
* bump version
* update docs (merge RC logs and add known knowns)
* 2.4.0 known knowns are all unresolved
To prepare the branch for the release v2.5.0
[#548](https://github.com/eclipse-tractusx/portal/issues/548)
> build(2.5.0): bump version and update docs

- src/framework/Framework.Async/Directory.Build.props
- src/framework/Framework.Cors/Directory.Build.props
- src/framework/Framework.DBAccess/Directory.Build.props
- src/framework/Framework.DateTimeProvider/Directory.Build.props
- src/framework/Framework.DependencyInjection/Directory.Build.props
- src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
- src/framework/Framework.ErrorHandling.Web/Directory.Build.props
- src/framework/Framework.ErrorHandling/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/Directory.Build.props
- src/framework/Framework.IO/Directory.Build.props
- src/framework/Framework.Identity/Directory.Build.props
- src/framework/Framework.Linq/Directory.Build.props
- src/framework/Framework.Logging/Directory.Build.props
- src/framework/Framework.Models/Directory.Build.props
- src/framework/Framework.Models/ValidationExpressions.cs
- src/framework/Framework.Processes.Library.Concrete/Directory.Build.props
- src/framework/Framework.Processes.Library/Directory.Build.props
- src/framework/Framework.Processes.ProcessIdentity/Directory.Build.props
- src/framework/Framework.Processes.Worker.Library/Directory.Build.props
- src/framework/Framework.Seeding/Directory.Build.props
- src/framework/Framework.Swagger/Directory.Build.props
- src/framework/Framework.Token/Directory.Build.props
- src/framework/Framework.Web/Directory.Build.props
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Registration api responding 400 error code "REGION_INVALID"
Registration api is responding 400 error when entring "140" region value
Current regex: `^[A-Z1-9]{1,3}$`
Expected regex: `^[A-Z0-9]{1,3}$`
Ref: #1404
> fix(regex): region regex update

- docs/api/apps-service.yaml
- docs/api/services-service.yaml
- src/marketplace/Offers.Library/Extensions/CompanySubscriptionStatusExtensions.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanySubscriptionStatusData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferCompanySubscriptionStatusData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
Added DateCreated attribute to subscription status response 
To optimise filtering functionality in the frontend, a creation date of the subscription is needed in the response
[1590](https://github.com/eclipse-tractusx/portal-frontend/issues/1590)
> feat: add createdAt to subscription status response

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/ErrorHandling/AdministrationConnectorErrorMessageContainer.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
Added exception handling for connector creation without specifiying a technical user.
A connector needs to have an active technical user assigned during creation. Therefore, if none is specified during the creation process, the API should throw and error and prevent its creation. 
#1409 
> fix: add exception handling for connector with out tech user

- docs/api/administration-service.yaml
- src/administration/Administration.Service/Controllers/NetworkController.cs
- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/administration/Administration.Service/Controllers/ServiceAccountController.cs
- src/administration/Administration.Service/Controllers/UserController.cs
Setting default page and pageSize values to paginated get APIs
We have default page = 0 and size = 15 values in our APIs from where we respond paginated data but there are a few APIs where this default value is not set:
api/administration/registration/network/companies
api/administration/serviceaccount/owncompany/serviceaccounts
api/administration/registration/applications
api/administration/user/owncompany/users
Ref: #1366
> fix(defaultPaginationValues): Set default page and pageSize values paginated get APIs

- src/framework/Framework.Async/Directory.Build.props
- src/framework/Framework.Cors/Directory.Build.props
- src/framework/Framework.DBAccess/Directory.Build.props
- src/framework/Framework.DateTimeProvider/Directory.Build.props
- src/framework/Framework.DependencyInjection/Directory.Build.props
- src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
- src/framework/Framework.ErrorHandling.Web/BaseHttpExceptionHandler.cs
- src/framework/Framework.ErrorHandling.Web/Directory.Build.props
- src/framework/Framework.ErrorHandling/Directory.Build.props
- src/framework/Framework.HttpClientExtensions/Directory.Build.props
- src/framework/Framework.IO/Directory.Build.props
- src/framework/Framework.Identity/Directory.Build.props
- src/framework/Framework.Linq/Directory.Build.props
- src/framework/Framework.Logging/Directory.Build.props
- src/framework/Framework.Models/Directory.Build.props
- src/framework/Framework.Processes.Library.Concrete/Directory.Build.props
- src/framework/Framework.Processes.Library/Directory.Build.props
- src/framework/Framework.Processes.ProcessIdentity/Directory.Build.props
- src/framework/Framework.Processes.Worker.Library/Directory.Build.props
- src/framework/Framework.Seeding/Directory.Build.props
- src/framework/Framework.Swagger/Directory.Build.props
- src/framework/Framework.Token/Directory.Build.props
- src/framework/Framework.Web/Directory.Build.props
add mapping of BadHttpRequestException to BadRequest in BaseHttpExceptionHandler
when during binding of request to controller parameters an error occours (like during json-deserialization) the mvc-framework throws BadHttpRequestException. Currently this exception-type is not handled by the error-handling middleware and is being mapped to the default InternalServerError which is misleading
N/A
> fix(framework-web): fix json deserialization errors resulting in Error 500

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
Added connector type check in validate technical user method for connector creation. 
A 400 error was being thrown when creating a managed connector. This was caused by the introduction of error handling when creating a connector without a technical user #1411 . The method that validates the technical user is shared in both the owned and managed connector creation function, this is problematic as the managed connector is created without the technical user. 
#1426
> fix: add connector type check for validate technical user

- src/marketplace/Offers.Library/Service/OfferService.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
Added Decentralized Identity Management Auth Url check and addition of "oauth/token" incase it does not exist. 
For users to access the Decentralized service, the auth url must contain "oauth/token" suffix. Incase the wallet is missing the suffix in the auth URL, portal will ensure the suffix is added. 
#1424 
> fix: decentralized identity management auth url missing suffix
